import assert from 'node:assert/strict';
let access=0;const regular=()=>{access++;throw Error('unexpected file access')};
function qualify(expected,expectedBytes,callerRoot){
 assert(expected.sealed===true&&expected.runtimeEligible===true&&expected.runtimeRecovery?.complete===true,'SOURCE_ONLY_UNSEALED: complete NEW stage bindings and separately reviewed Root method grant required');
 const grant=JSON.parse(regular(expected.rootMethodGrantPath));assert.equal(grant.schema,'opening-runtime-root-grant-v1');assert.equal(grant.authorized,true);assert.equal(grant.callerRoot,callerRoot);assert.equal(grant.expectedSHA256,sha(expectedBytes));assert.equal(grant.sourceManifestSHA256,sha(regular(callerRoot+'/MANIFEST.json')));assert.equal(grant.sourceSealSHA256,sha(regular(callerRoot+'/SOURCE-SEAL.json')));assert.equal(grant.actualPacket,expected.actualPacket);assert.equal(grant.driverSeconds,60);assert.equal(grant.supervisorWholeSeconds,90);assert.equal(grant.reviews.length,3);assert.deepEqual(grant.reviews.map(r=>r.role).sort(),['gameplay','technical','visual']);
 const seal=JSON.parse(regular(callerRoot+'/SOURCE-SEAL.json'));for(const ref of seal.files){const body=regular(callerRoot+'/'+ref.name);assert.equal(body.length,ref.bytes);assert.equal(sha(body),ref.sha256);}
 for(const ref of grant.reviews){const review=record(ref.path,ref.sha256);assert.equal(ref.accepted,true);assert.equal(review.accepted,true);assert.equal(review.sourceSealSHA256,grant.sourceSealSHA256);}
 const stageInodes=new Set(),stages=expected.runtimes.map(config=>{
  const freeze=record(config.freezePath,config.freezeSHA256),manifest=record(config.stageManifestPath,config.stageManifestSHA256),authority=record(config.stageAuthorityPath,config.stageAuthoritySHA256);
  for(const row of [freeze,manifest])for(const key of ['stage','sourceDigest','outputsDigest','inputCount','outputCount'])assert.equal(row[key],config[key]);
  assert.equal(manifest.schema,'regular-file-stage-v1');assert.equal(manifest.historicalMetadataRestored,false);assert.equal(authority.schema,'recovered-stage-authority-v1');assert.equal(authority.stage,config.stage);assert.equal(authority.acceptedByteExactReconstruction,true);assert.equal(authority.actualFreshBuild,config.authorityActualFreshBuild);assert.equal(authority.historicalMetadataRestored,false);assert.equal(authority.freezeSHA256,config.freezeSHA256);assert.equal(authority.stageManifestSHA256,config.stageManifestSHA256);assert.equal(authority.artDefaultOrFunAccepted,false);record(path.dirname(config.stageAuthorityPath)+'/BODY-COPY-RECEIPT.json',authority.bodyCopyReceiptSHA256);
  const review=record(config.stageReviewPath,config.stageReviewSHA256);assert.equal(review.accepted,true);
  if(config.role==='retainedB'){assert.equal(review.decision,'ACCEPT_EXACT_NEW_REGULAR_FILE_STATIC_RECONSTRUCTION_ONLY');assert.equal(review.newRuntimeFreezeSHA256,config.freezeSHA256);assert.equal(review.newStageManifestSHA256,config.stageManifestSHA256);assert.equal(review.newRootAuthoritySHA256,config.stageAuthoritySHA256);assert.equal(review.sourceDigest,config.sourceDigest);assert.equal(review.outputsDigest,config.outputsDigest);assert.equal(review.exactSource104Verified,true);assert.equal(review.exactOutputs70Verified,true);assert.equal(review.artDefaultGameplayFunApproved,false);const a=record(path.dirname(config.stageReviewPath)+'/AUDIT.json',review.fullAuditSHA256);assert.equal(a.stage,config.stage);assert.equal(a.inputCount,104);assert.equal(a.outputCount,70);}
  else{assert.equal(review.stage,config.stage);assert.equal(review.freezeSHA256,config.freezeSHA256);assert.equal(review.stageManifestSHA256,config.stageManifestSHA256);}
  const membership={...freeze.inputs,...Object.fromEntries(Object.entries(freeze.outputs).map(([k,v])=>['dist/'+k,v]))};assert.deepEqual(Object.keys(manifest.files).sort(),Object.keys(membership).sort());assert.deepEqual(members(config.stage),Object.keys(membership).sort());assert.equal(Object.keys(freeze.inputs).length,config.inputCount);assert.equal(Object.keys(freeze.outputs).length,config.outputCount);
  for(const [rel,pin] of Object.entries(manifest.files)){assert(!path.isAbsolute(rel)&&!rel.split('/').some(p=>!p||p==='.'||p==='..'));assert.equal(pin.sha256,membership[rel]);assert.equal(pin.nlink,1);assert.equal(typeof pin.mtimeNs,'string');assert.equal(typeof pin.ctimeNs,'string');identity(config.stage+'/'+rel,pin);const key=pin.dev+':'+pin.ino;assert(!stageInodes.has(key),'A/B stage bodies must have distinct new inodes');stageInodes.add(key);}
  return {config,stage:config.stage,freeze,manifest,authority};
 });
 assert.deepEqual(grant.stages,expected.runtimes.map(r=>({stage:r.stage,freezeSHA256:r.freezeSHA256,stageManifestSHA256:r.stageManifestSHA256,stageAuthoritySHA256:r.stageAuthoritySHA256})));
 const dependencies=record(expected.dependencies.path,expected.dependencies.sha256);assert.equal(dependencies.schema,'installed-dependency-identities-v1');assert.equal(dependencies.packageVersion,'1.62.0');assert.equal(dependencies.nodeVersion,'v24.19.0');assert.equal(process.version,dependencies.nodeVersion);assert.equal(dependencies.modulePath,expected.dependencies.modulePath);assert.equal(dependencies.nodePath,process.execPath);assert.equal(dependencies.browserExecutablePath,expected.dependencies.browserExecutablePath);
 for(const pin of dependencies.files)identity(pin.path,pin,true);
 return {grant,stages,dependencies};
}

const cases=[{sealed:false,runtimeEligible:false,runtimeRecovery:{complete:false}},{sealed:false,runtimeEligible:true,runtimeRecovery:{complete:true}},{sealed:true,runtimeEligible:false,runtimeRecovery:{complete:true}},{sealed:true,runtimeEligible:true,runtimeRecovery:{complete:false}}];for(const c of cases){assert.throws(()=>qualify(c,Buffer.from('none'),'/synthetic'),/SOURCE_ONLY_UNSEALED/);assert.equal(access,0)}console.log(JSON.stringify({cases:4,fileAccesses:access,externalImportOrCallerExecuted:false}));
