"""Author NEW SOURCE only; no caller/helper/app execution. R1 is read-only origin."""
import pathlib,json,gzip,hashlib,base64,resource,time
P=pathlib.Path(__file__).parent
O=pathlib.Path('/workspace/scratch/opening-cue-late-binding-caller-source-r1')
def sha(b): return hashlib.sha256(b).hexdigest()
def body(name,value): (P/name).write_text(json.dumps(value,separators=(',',':'))+'\n')
if not (P/'R1-SNAPSHOT.json.gz').exists():
 origin={f.name:f.read_text() if f.suffix!='.gz' else {'base64':base64.b64encode(f.read_bytes()).decode()} for f in sorted(O.iterdir())}
 (P/'R1-SNAPSHOT.json.gz').write_bytes(gzip.compress((json.dumps(origin,separators=(',',':'))+'\n').encode(),mtime=0))
 for f in O.iterdir():
  if f.name not in ['SOURCE-SEAL.json','SOURCE-ADMISSION.json','SOURCE-RESOURCE-RECEIPT.json','GRAMMAR-INVERSE-RECEIPT.json','MANIFEST.json']: (P/f.name).write_bytes(f.read_bytes())
 for name in ['driver-cue.mjs','supervise-cue.py','EXPECTED.json']:
  f=P/name;f.write_text(f.read_text().replace('opening-cue-late-binding-caller-source-r1','opening-cue-late-binding-caller-source-r2').replace('opening-cue-late-binding-caller-root-grant-r1','opening-cue-late-binding-caller-root-grant-r2').replace('opening-cue-late-binding-comparison-actual-r1','opening-cue-late-binding-comparison-actual-r2'))
 d=(P/'driver-cue.mjs').read_text()
 d=d.replace("terminal:{heading:","presentation:{settling:document.querySelector('#app')?.classList.contains('settling-combat')??false,sceneBusy:document.querySelector('#scene-ui')?.getAttribute('aria-busy')??null,appClass:document.querySelector('#app')?.className??null,dockHidden:document.querySelector('#dock')?.hidden??null,arenaHidden:document.querySelector('#arena-wrap')?.getAttribute('aria-hidden')??null,dockCommands:[...document.querySelectorAll('#dock button')].map(e=>({disabled:e.disabled,hidden:e.hidden}))},terminal:{heading:")
 d=d.replace("'Consumed/terminal candidate cue still present'","'Consumed battle candidate cue still present'")
 entry="""async function enterFreshContract(){assert.equal(await raw(),null);assert(await page.locator('#app.on-title').count()===1);assert.equal(await page.locator('#dialog').evaluate(e=>e.open),false);assert.equal(await page.locator('#new-game-form').count(),0);const titleNew=page.locator('#scene-ui [data-hunt-entry] [data-ui=\"new\"]');assert.equal(await titleNew.count(),1);assert((await titleNew.innerText()).includes('Take a contract'));await click(titleNew,'open ordinary title contract');assert.equal(await page.locator('#dialog').evaluate(e=>e.open),true);const form=page.locator('#dialog #new-game-form');assert.equal(await form.count(),1);assert(await form.locator('input[name=\"difficulty\"][value=\"0\"]').isChecked());assert.equal(await form.locator('input[name=\"replaceSaved\"]').count(),0);const disclosure=form.locator('[data-hunt-disclosure=\"hunt-seed-panel\"]'),seed=form.locator('#seed');assert.equal(await disclosure.count(),1);assert.equal(await disclosure.getAttribute('aria-expanded'),'false');assert.equal(await form.locator('#hunt-seed-panel').evaluate(e=>e.hidden),true);assert.equal(await seed.isVisible(),false);assert.equal(await raw(),null);await click(disclosure,'show actual modal seed input');assert.equal(await disclosure.getAttribute('aria-expanded'),'true');assert.equal(await form.locator('#hunt-seed-panel').evaluate(e=>e.hidden),false);assert(await seed.isVisible());await click(seed,'focus ordinary modal seed input');const n=events.length;await page.keyboard.press('Control+A');await page.keyboard.type('121',{delay:25});assert.equal(await seed.inputValue(),'121');assert(events.slice(n).some(e=>e.case===active.name&&e.type==='keydown'&&e.trusted&&e.target.id==='seed'));assert.equal(await raw(),null);active.entry={sourceTracedTitleNewAndModalDisclosure:true,seedInitiallyHidden:true,seedVisibleAfterOrdinaryDisclosure:true,typedSeed:121,defaultDifficulty:0,noReplacementSave:true};await click(form.locator('[type=\"submit\"]'),'default Initiate seed121');assert.equal(await page.locator('#dialog').evaluate(e=>e.open),false);}
async function observeOrderCueRetirement(phase){const initial=await sample('post-Order presentation before retirement check');if(phase==='battle'){cueCheck(initial,null);return;}active.terminalPresentationBefore=initial;const before=await raw();check();const waitMs=Math.min(4000,60000-(Date.now()-started)-500);assert(waitMs>0,'No remaining bounded terminal presentation allowance');await page.waitForFunction(terminalPhase=>{const app=document.querySelector('#app'),dock=document.querySelector('#dock'),scene=document.querySelector('#scene-ui');return !!app&&app.classList.contains('phase-'+terminalPhase)&&!app.classList.contains('settling-combat')&&scene?.getAttribute('aria-busy')!=='true'&&dock?.hidden===true&&document.querySelector('#arena-wrap')?.getAttribute('aria-hidden')==='true'&&!!scene?.querySelector('h1');},phase,{timeout:waitMs,polling:100});check();assert.equal(await raw(),before,'Passive terminal presentation wait changed full save');const settled=await sample('observed terminal dock hidden after presentation');assert(settled.presentation.appClass.split(' ').includes('phase-'+phase));assert.equal(settled.presentation.settling,false);assert.notEqual(settled.presentation.sceneBusy,'true');assert.equal(settled.presentation.dockHidden,true);assert.equal(settled.presentation.arenaHidden,'true');assert(settled.terminal.heading);assert(settled.cue.visible!==true,'Terminal cue remains visible/actionable');active.terminalPresentationAfter=settled;active.terminalCueAssessment='Observed terminal dock hidden/nonactionable; retained cue markup is permitted';}
"""
 begin=d.index("assert.equal(await raw(),null);await click(page.locator('#scene-ui")
 end=d.index("await page.waitForTimeout(600);",begin)
 d=d[:begin]+"await enterFreshContract();"+d[end:]
 d=d.replace("cueCheck(await sample('settled first Order cue hidden'),null);","await observeOrderCueRetirement(after.phase);")
 d=d.replace('async function runCase(runtime){',entry+'async function runCase(runtime){')
 (P/'driver-cue.mjs').write_text(d)
 proto=json.loads((P/'PROTOCOL.json').read_text());proto['sequence'][0]='Fresh null-save/title ordinary Take a contract; exact modal form/default Initiate; seed initially hidden, actual disclosure exposes #seed; trusted typed121 and ordinary submit; visible travel if offered'
 proto['sequence'][7]='Record full command outcome; consumed cue absent while battle; naturally terminal result records retained impact then waits at most4s within same60s clock for observed nonbusy terminal heading/hidden dock and arena; hidden/nonactionable cue may remain in DOM'
 proto['cueExpectedC']['afterCommittedOrder']='battle: absent; terminal: observed dock hidden/nonactionable after bounded presentation completion, retained markup allowed'
 proto['terminalPresentationWaitCapMs']=4000;body('PROTOCOL.json',proto)
 readme=(P/'README.md').read_text().replace("Following one committed Order, C's row disappears.","Following one committed Order in battle, C's row disappears. A terminal result retains the actual impact observation, then waits at most4s within the original60s clock for observed presentation completion, terminal heading and hidden dock/arena. Hidden/nonactionable cue markup is permitted; it is not required to be removed. A timeout fails rather than claiming settled terminal coverage.")
 readme+='\nR2 preserves the entire exact sealed R1 in R1-SNAPSHOT and its original directory. R1 gameplay review rejected unconditional terminal DOM removal. Complete source tracing also resolves the preliminary disclosure concern: both exact main modules import the same hunt-entry; seed is initially hidden in the modal and the real disclosure reveals it. R2 explicitly verifies title/new versus modal/form/hidden→visible seed states. No alternate Windows-entry UI is used. Only the confirmed terminal assertion and explicit ordinary entry checks change gameplay observation. New C bindings remain absent; later binding requires another new exact revision.\n'
 (P/'README.md').write_text(readme)
 trace=[]
 for name,path in [('B-main','/workspace/scratch/starter-static-recovered-stage-r1/src/main.ts'),('B-hunt-entry','/workspace/scratch/starter-static-recovered-stage-r1/src/hunt-entry.ts'),('C-main','/workspace/scratch/opening-cue-milestones-source-r1/src/main.ts')]:
  b=pathlib.Path(path).read_bytes();trace.append({'name':name,'path':path,'bytes':len(b),'sha256':sha(b)})
 body('UI-SOURCE-TRACE.json',{'sourceOnly':True,'bodies':trace,'CInheritedHuntEntry':'Candidate source changes only main; hunt-entry is inherited byte-exact B closure, not another UI donor','selectors':[{'selector':'#scene-ui [data-hunt-entry] [data-ui="new"]','origin':'hunt-entry.ts renderHuntTitle; main renderTitle/handleClick case new/openNew'},{'selector':'#dialog #new-game-form','origin':'main openNew/renderHuntContract; hunt-entry.ts63'},{'selector':'input[name="difficulty"][value="0"]','origin':'hunt-entry.ts default difficulty; main openNew difficulty0'},{'selector':'[data-hunt-disclosure="hunt-seed-panel"]','origin':'hunt-entry.ts69 and handler138-143; real modal hidden→visible seed'},{'selector':'#seed','origin':'hunt-entry.ts74; initially ancestor panel hidden'},{'selector':'#new-game-form [type="submit"]','origin':'hunt-entry.ts85; main document submit/readHuntContractForm/start'}],'terminal':'main holdFinalStrike retains old dock while settling; render later sets dock.hidden and arena aria-hidden, leaves innerHTML. Require observed hidden/nonactionable terminal affordance, not DOM removal','runtimeExecuted':False})
 body('SOURCE-ADMISSION.json',{'sourceOnly':True,'sourceFamilyCapBytes':196608,'workBytes':64*1048576,'reserveBytes':512*1048576,'ownDiskCapBytes':24*1048576,'sampleUTCNS':time.time_ns(),'currentSharedCgroupBytes':int(pathlib.Path('/sys/fs/cgroup/memory.current').read_text()),'maximumBytes':int(pathlib.Path('/sys/fs/cgroup/memory.max').read_text()),'qualification':'Point admission sample, shared host; no exclusive attribution or continuous peak','admitted':True})
