import json,hashlib,resource
from pathlib import Path
P=Path(__file__).parent
def sha(q):return hashlib.sha256(q.read_bytes()).hexdigest()
a=json.loads((P/'AUDIT.json').read_bytes());r=json.loads((P/'review-guard/RESULT.json').read_bytes());assert r['exit_code']==0 and r['failure'] is None and r['memory_events_before']==r['memory_events_after']
gate={'decision':a['decision'],'exactTwoPathActionMethodEligible':False,'accepted':False,'actionAuthority':False,'methodPath':'/workspace/scratch/retire-opening-capsule-duplicates-root-r1.py','methodSHA256':a['methodSHA256'],'preferenceGateSHA256':a['preferenceGateSHA256'],'locationMapSHA256':a['locationMapSHA256'],'blockingFindings':[{'id':'optimization-removes-authorization','sourceLines':[23,25,26,37,38,39,40,46,47],'finding':'The assert __debug__ refusal disappears under optimized Python, as do all authorization/body/metadata assertions; compile(optimize=1) retains the sole unlink call. PYTHONOPTIMIZE inheritance can do this with python -B.','required':'Fresh unconditional non-assert refusal plus pinned invocation/environment; independently reviewed successor, no R1 action.'},{'id':'unbounded-network-phase','sourceLine':29,'finding':'Fresh git ls-remote has no timeout and method has no whole monotonic deadline; resource-only outer guard cannot bound resource-light blocking elapsed time.','required':'Fresh reviewed finite phase/deadlines and descendant closure or exact recent confirmed upstream remote receipt; preserve partial results/no resource relaxation.'}],'compileOnlyWitness':a['compileOnlyWitness'],'bodyReads':'Method and bounded historical control JSON only; neither TAR body nor protected ZIP opened.','intendedSoundControls':a['soundIntendedScope'],'partialProgressQualification':a['exceptionQualification'],'publicationPrerequisites':a['publicationDependencyQualification'],'preferenceVerdictUnchanged':True,'canonicalCopiesMustRemain':True,'originalMethodUnchanged':True,'actionExecuted':False,'gameArtDefaultRuntimeApproval':False,'AUDIT_SHA256':sha(P/'AUDIT.json'),'normalSourceGuardSHA256':sha(P/'review-guard/RESULT.json'),'auditAnnotationQualification':'AUDIT network array captures actual AST line29; its handwritten blocker line31 and broader illustrative line list are superseded by exact GATE source references above. No witness or method rerun/correction.','roleDisclosure':a['roleDisclosure']}
(P/'GATE.json').open('x').write(json.dumps(gate,separators=(',',':'))+'\n')
(P/'REVIEW.md').open('x').write('Rejected Root R1 exact two-path retirement method; no deletion or archive-body replay. Ordinary SOURCE guard normal0. Compile-only witness:20 assertion loads normally,0 optimized; one unlink call remains in both. At line23 assert __debug__ is erased rather than refusing optimized Python. Lines25/26 and37–47 authorization/hash/metadata checks also vanish. Existing PYTHONOPTIMIZE can activate optimization with python -B. Requires unconditional refusal and a freshly reviewed successor.\n\nAt line29 git ls-remote is unbounded; there is no whole monotonic deadline or alarm. Resource-only source/action guard does not bound a resource-light stuck remote command. A successor needs finite reviewed action limits and bounded local calls; consuming an exact recent upstream confirmed remote receipt may avoid a network subprocess, while preserving confirmed-push-before-retirement semantics.\n\nThe intended two scratch-only paths, metadata+xattrs/private nlink1/distinct inode/parent symlink checks, canonical SHA/metadata preservation, fsynced PRE/per-path POST and no automatic restoration are otherwise narrow. Sequential deletion can partially complete on an exception; retain PRE/any POST and inspect actual namespaces independently, never imply atomic two-file transaction/global FD or consumer absence/old inode-time restoration. Current preference remains conditional and is not action authority. Publish all exact controls/mapping/decision/new checkpoint and obtain a fresh confirmed clean push plus new Root action grant after successor SOURCE review. Root R1 method and rejection remain immutable.\n\nEarlier preservation/utility/helper reviewer role disclosed; preference author is distinct and Root authored this action method. No art/game/default approval. AUDIT handwritten line annotations are qualified by exact Gate references; compile witness and AST network line are unchanged.\n')
files={str(q.relative_to(P)):{'bytes':q.stat().st_size,'sha256':sha(q)} for q in P.rglob('*') if q.is_file()}
(P/'MANIFEST.json').open('x').write(json.dumps({'files':files,'logicalCapBytes':65536,'allocatedCapClaimed':False,'guardTailReserveBytes':8192,'workMiB':64,'reserveMiB':512,'diskAdmissionMiB':64,'ownRSSKiBLimit':24576,'finalSealGuard':'Separate ADMISSION/RESULT/EXECUTION follows manifest; final pin returned.'},separators=(',',':'))+'\n')
n=sum(q.stat().st_size for q in P.rglob('*') if q.is_file());assert n+8192<=65536 and resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
print(json.dumps({'gateSHA256':sha(P/'GATE.json'),'manifestSHA256':sha(P/'MANIFEST.json'),'reviewSHA256':sha(P/'REVIEW.md'),'auditSHA256':sha(P/'AUDIT.json'),'logicalBeforeFinalGuardTail':n,'tailReserveBytes':8192,'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'noActionExecuted':True}))
