import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {applyActionWithEvents,validateState} from '../../src/engine.ts';
const out='reviews/technical-v0.6-final-evidence';
const fixtures=JSON.parse(fs.readFileSync('reviews/arena-v0.6-contact-prototype/fixtures.json')).cases;
const candidates=[['hound-leftward',1280,720],['hound-rightward',1280,720],['hound-far-left-mutual-death',1280,720],['two-dragons-fourteen-hits',1280,720],['hound-leftward',390,844],['hound-rightward',390,844]];
const versions=[{name:'immutable-v5',base:'http://127.0.0.1:5187',digest:'d6221bf764bad593b04981e87bead7ba6868b72cf361d70671af5c91aac39416'},{name:'actual-v6',base:'http://127.0.0.1:4173',digest:'a502ed48dfb625257acea8d747439bce23be2c2ec346013b6c1a4fd9c8cb14f5'}];
const report={method:'Independent real production Canvas2D, immutable v5 web versus combined v6; actual native UI actions and current canonical reducer. Instrumented native RAF/image/stroke records, not FPS/hardware/human evidence. Diagnostic inventories are authored fixtures.',results:[],errors:[],externalRequests:[]};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-gpu']});
try{for(const [name,width,height] of candidates){const fixture=fixtures.find(f=>f.name===name);assert.ok(validateState(fixture.before));const canonical=applyActionWithEvents(fixture.before,fixture.action);assert.deepEqual(canonical.state,fixture.state);assert.deepEqual(canonical.events,fixture.events);
for(const version of versions){const ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(version.base))report.externalRequests.push(r.url());});
await p.addInitScript(f=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(f.before));localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion:true,mute:true,volume:0}));localStorage.setItem('hollowpact.tutorial.v2','yes');window.auditEpoch=null;window.auditFrames=[];window.auditFrame=null;
const draw=CanvasRenderingContext2D.prototype.drawImage,curve=CanvasRenderingContext2D.prototype.quadraticCurveTo,arc=CanvasRenderingContext2D.prototype.arc;
CanvasRenderingContext2D.prototype.drawImage=function(...args){const r=draw.apply(this,args);if(this.canvas.id!=='arena'||window.auditEpoch===null)return r;if(args[0] instanceof HTMLCanvasElement){window.auditFrame={elapsed:performance.now()-auditEpoch,width:this.canvas.width,height:this.canvas.height,actors:[],impacts:[]};queueMicrotask(()=>{if(auditFrame.elapsed<1250)auditFrames.push(structuredClone(auditFrame));});}else if(args[0] instanceof HTMLImageElement&&args.length===9&&auditFrame){const t=this.getTransform();auditFrame.actors.push({url:args[0].src.split('/').at(-1),source:args.slice(1,5),destination:args.slice(5),matrix:{a:t.a,b:t.b,c:t.c,d:t.d,e:t.e,f:t.f},alpha:this.globalAlpha});}return r;};
CanvasRenderingContext2D.prototype.quadraticCurveTo=function(...args){if(this.canvas.id==='arena'&&auditFrame&&args[1]===args[3]&&args[2]>args[0]+1&&this.lineWidth===1.5){const radius=(args[2]-args[0])/1.7;auditFrame.impacts.push({kind:'physical',color:this.strokeStyle,x:args[0]+radius,y:args[1]+radius,radius});}return curve.apply(this,args);};
CanvasRenderingContext2D.prototype.arc=function(...args){if(this.canvas.id==='arena'&&auditFrame&&this.strokeStyle==='#ddbe80'&&args[2]>=9&&args[2]<35&&this.lineWidth===1.5)auditFrame.impacts.push({kind:'magic',color:this.strokeStyle,x:args[0],y:args[1],radius:args[2]});return arc.apply(this,args);};},fixture);
await p.goto(version.base);assert.equal(await p.evaluate(async()=> (await(await fetch('./build-provenance.json')).json()).sourceDigest),version.digest);await p.locator('[data-ui=resume]').click();await p.waitForTimeout(400);await p.evaluate(()=>window.auditEpoch=performance.now());
if(fixture.action.type==='attack'){await p.locator(`[data-unit="${fixture.action.unit}"]`).click();await p.locator(`[data-unit="${fixture.action.target}"]`).click();}else await p.locator('[data-action=endTurn]').click();
assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('hollowpact.run.v2'))),canonical.state);await p.waitForTimeout(1250);const measured=await p.evaluate(()=>({frames:auditFrames,save:JSON.parse(localStorage.getItem('hollowpact.run.v2')),dialog:document.querySelector('#dialog').open,focus:document.activeElement.tagName}));assert.deepEqual(measured.save,canonical.state);assert.ok(measured.frames.length>5);await p.screenshot({path:`${out}/${width}-${name}-${version.name}-settled.png`});report.results.push({name,viewport:{width,height},version:version.name,digest:version.digest,canonicalSaveExact:true,events:canonical.events,...measured});await ctx.close();}}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);
}finally{await browser.close();fs.writeFileSync(out+'/production-contact.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});}
console.log(JSON.stringify({cases:report.results.length,errors:report.errors,externalRequests:report.externalRequests,canonical:report.results.every(r=>r.canonicalSaveExact)}));
