import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {validateState,applyAction} from '../../src/engine.ts';
const out='reviews/technical-v0.6-final-evidence',base='http://127.0.0.1:4173',digest='a502ed48dfb625257acea8d747439bce23be2c2ec346013b6c1a4fd9c8cb14f5',fixtures=JSON.parse(fs.readFileSync('reviews/arena-v0.6-contact-prototype/fixtures.json')).cases,far=fixtures.find(f=>f.name==='hound-leftward');
const terminal=structuredClone(far);terminal.before.enemies=[terminal.before.enemies[0]];terminal.before.enemies[0].hp=1;terminal.before.enemies[0].block=0;terminal.action.target=terminal.before.enemies[0].uid;terminal.state=applyAction(terminal.before,terminal.action);assert.ok(validateState(terminal.before));assert.equal(terminal.state.phase,'reward');
const report={scope:'Independent combined production host; synthetic hidden event/virtual pad; actual browser reduced-motion and art/canvas failure diagnostics. No physical controller/OS/hardware claim.',digest,checks:[],errors:[]},b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-gpu']});
async function load(f=far,opt={}){const ctx=await b.newContext({viewport:{width:1280,height:720},reducedMotion:opt.reduced?'reduce':'no-preference'});if(opt.missingArt)await ctx.route('**/hound-poses.png',r=>r.abort('failed'));await ctx.addInitScript(({f,opt})=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(f.before));localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion:true,mute:true,volume:0}));localStorage.setItem('hollowpact.tutorial.v2','yes');if(opt.missingCanvas){const g=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(...args){return this.id==='arena'?null:g.apply(this,args);};}if(opt.pad){window.pad={index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{value:()=>[window.pad]});}}, {f,opt});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base);assert.equal(await p.evaluate(async()=> (await(await fetch('./build-provenance.json')).json()).sourceDigest),digest);await p.locator('[data-ui=resume]').click();await p.waitForTimeout(300);return{ctx,p};}
const save=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('hollowpact.run.v2')));
async function act(p,f){await p.locator(`[data-unit="${f.action.unit}"]`).click();await p.locator(`[data-unit="${f.action.target}"]`).click();assert.deepEqual(await save(p),f.state);}
try{
let {ctx,p}=await load(terminal);await act(p,terminal);assert.ok(await p.locator('#app').evaluate(e=>e.classList.contains('settling-combat')));await p.keyboard.press('Escape');assert.equal(await p.locator('#dialog-title').textContent(),'Campaign paused');assert.equal(await p.locator('#app').evaluate(e=>e.classList.contains('settling-combat')),false);await p.waitForTimeout(1350);assert.equal(await p.locator('#dialog-title').textContent(),'Campaign paused');assert.deepEqual(await save(p),terminal.state);await p.keyboard.press('Escape');assert.equal(await p.locator('#dialog').evaluate(e=>e.open),false);assert.equal(await p.locator('#app').evaluate(e=>e.classList.contains('settling-combat')),false);report.checks.push({name:'terminal final-kill pause cancels hold and stale epoch cannot replace modal',passed:true});await ctx.close();
({ctx,p}=await load(terminal));await act(p,terminal);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('#app').evaluate(e=>e.classList.contains('settling-combat')),false);await p.waitForTimeout(300);assert.deepEqual(await save(p),terminal.state);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.waitForTimeout(1100);assert.deepEqual(await save(p),terminal.state);report.checks.push({name:'synthetic hidden final result settles and visibility return preserves accepted save',passed:true,syntheticVisibility:true});await ctx.close();
({ctx,p}=await load(terminal,{reduced:true}));await act(p,terminal);assert.equal(await p.locator('#app').evaluate(e=>e.classList.contains('settling-combat')),false);assert.deepEqual(await save(p),terminal.state);report.checks.push({name:'browser reduced motion uses immediate canonical result without final hold',passed:true});await ctx.close();
({ctx,p}=await load(far,{missingArt:true}));await act(p,far);await p.waitForTimeout(900);assert.deepEqual(await save(p),far.state);assert.ok(await p.locator(`[data-unit="${far.before.allies[1].uid}"]`).isEnabled());report.checks.push({name:'failed hound pose keeps static art and exact accepted command with live next controls',passed:true});await ctx.close();
({ctx,p}=await load(far,{missingCanvas:true}));assert.match(await p.locator('.arena-fallback').textContent(),/All cards, companions and enemy commands remain available/);await act(p,far);assert.deepEqual(await save(p),far.state);report.checks.push({name:'missing 2D context exposes fallback and preserves exact command',passed:true});await ctx.close();
({ctx,p}=await load(far,{pad:true}));const before=await save(p);assert.match(await p.locator('.keyboard-hint').textContent(),/Hostiles/);await p.locator(`[data-unit="${far.action.unit}"]`).click();assert.match(await p.locator('.keyboard-hint').textContent(),/Targets/);await p.keyboard.press('Escape');assert.match(await p.locator('.keyboard-hint').textContent(),/Hostiles/);assert.deepEqual(await save(p),before);await p.evaluate(()=>window.pad.buttons[9]={pressed:true,value:1});await p.waitForTimeout(120);assert.equal(await p.locator('#dialog-title').textContent(),'Campaign paused');await p.keyboard.press('Escape');await p.evaluate(()=>window.pad.buttons[9]={pressed:false,value:0});await p.waitForTimeout(100);await p.evaluate(()=>window.pad.buttons[4]={pressed:true,value:1});await p.waitForTimeout(100);assert.match(await p.locator('.keyboard-hint').textContent(),/Start Pause/);assert.deepEqual(await save(p),before);report.checks.push({name:'Targets/Hostiles hints contextual and virtual Start pauses without save rewrite',passed:true,physicalControllerTested:false});await ctx.close();
assert.deepEqual(report.errors,[]);
}finally{await b.close();fs.writeFileSync(out+'/lifecycle.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});}console.log(JSON.stringify(report));
