import hashlib,json,pathlib
P=pathlib.Path(__file__).parent
def h(q):return hashlib.sha256(pathlib.Path(q).read_bytes()).hexdigest()
def put(n,v):(P/n).write_text(json.dumps(v,indent=2)+'\n')
base=pathlib.Path('/workspace/scratch/native128-empty-intent-stage-r1')
candidate=pathlib.Path('/workspace/scratch/starter-family-native128-materialized-source-root-r1')
planpath=pathlib.Path('/workspace/scratch/starter-family-native128-build-controls-source-author-r1/PLAN.json')
plan=json.loads(planpath.read_bytes());assert h(planpath)=='753be1feac8d1e112f10a1f29c795c4648386670d171d8983795e31156e59f8c'
gatepath=pathlib.Path('/workspace/scratch/starter-family-native128-wiring-source-independent-r2/GATE.json')
assert h(gatepath)=='d9e11d101944af80ada2f36cf7137633742aeff1d601d6bdf823ef924ade9beb'
for rel in ('src/engine.ts','src/content.ts'):
 assert h(base/rel)==plan['expectedInputs'][rel]
helper=(candidate/'coherent-native128.ts').read_text()
assert 'if (config.allies > 2 || config.enemies > 2' in helper
assert 'images.length === 13' in helper
assert "id === 'ashwidow' ? 7 : id === 'fenstalker' ? 9 : id === 'briarcolossus' ? 11" in helper
arena=(base/'src/arena.ts').read_text()
assert "setNativeMode(!!available && (nativeMode || previous?.phase !== 'battle'))" in arena
actual=pathlib.Path('/workspace/scratch/opening-turn-payoff-wording-actual-comparison-root-r1')
retained={}
for label,name in [('initial','A-cue-C0-OPAQUE-SAVE.json'),('afterOrdinaryEndTurn','A-cue-C-endTurn-OPAQUE-SAVE.json')]:
 q=actual/name;s=json.loads(json.loads(q.read_bytes())['raw']);retained[label]={'path':str(q),'sha256':h(q),'turn':s['turn'],'hand':s['hand'],'draw':s['draw'],'energy':s['energy'],'allies':[{'uid':u['uid'],'cardId':u['cardId'],'hp':u['hp']} for u in s['allies']]}
assert retained['initial']['hand']==['survey','scour','cairnhound','scour','ironward']
assert retained['afterOrdinaryEndTurn']['hand']==['cairnhound','ironward','ashwidow','sutures','fenstalker']
assert retained['afterOrdinaryEndTurn']['draw']==['sunder','briarcolossus']
pins={str(q):h(q) for q in [planpath,gatepath,candidate/'main.ts',candidate/'coherent-native128.ts',candidate/'art.ts',candidate/'coherent-native128-manual-crop-view-manifest.json',base/'src/arena.ts',base/'src/engine.ts',base/'src/content.ts',pathlib.Path('/workspace/scratch/opening-turn-payoff-wording-actual-caller-source-final-r1/driver-paired-r1.mjs')]}
put('SOURCE-PROOF.json',{'pins':pins,'candidateUnbuiltSource':plan['expectedSourceDigest'],'candidateExpectedInputCount':plan['expectedInputCount'],'candidateOutputCountPredicted':70,'baselineSource':plan['donorSourceDigest'],'baselineOutputs':plan['donorOutputsDigest'],'retainedOrdinaryObservedDraws':retained,'rulesAndDeckIdenticalToCandidateExpectedMaps':True,'sourceBlocker':'Native layout rejects >2 allies/enemies; engine legal summon cap remains6. Assets READY alone cannot prevent layout fallback.','latch':'If fallback turns nativeMode false during battle, nativeMode||previous.phase!==battle prevents same-battle recovery even after slots free; no reentry repair proposed.','futureBuildAndCallerGatesRequired':True,'sourceInspectionOnly':True})
protocol={
 'status':'SOURCE_ONLY_PROTOCOL_NOT_EXECUTABLE_OR_ACTUAL_GRANTED',
 'hypothesis':'With thirteen native assets ready before ordinary encounter admission, starter hand portraits and one legally summoned second ally retain coherent native presentation; all-three starter body continuity is outside current layout capacity.',
 'pair':{'A':'Frozen seven-image baseline76e5/2547,98inputs64outputs','B':'Future starter65b31,104inputs70outputs predicted; requires actual fresh strict freeze/gate','queryBoth':'?targetClearGhost=1&coherentNative128=1','seed':'Ordinary typed937240, default Initiate, fresh independent browser context; no fixture/reroll','viewport':[1440,900],'classification':'Short source-informed opening diagnostic, not completed first300 or novice play'},
 'timeAccount':{'firstSessionOrigin':'Record real page/title load UTC and monotonic elapsed; include asset wait/menu entry/gestures/response/captures in uninterrupted account','driverWholeSeconds':60,'supervisorWholeSeconds':90,'first300Status':'Only actually elapsed prefix observed; remaining time NOT_OBSERVED, no artificial clock or unearned300 claim','pairScheduling':'One attempt; same finite ordinary action policy in both contexts, no state-dependent favorable reroll','budgetExit':'Before branch if remaining driver budget cannot safely finish ordinary release and owned close, record NOT_ATTEMPTED reason and stop normally/qualify incomplete; no extra wait to force a transient'},
 'steps':[
  {'id':'entry','input':'Ordinary title seed typing/default Initiate after passive actual decode readiness receipt','observe':'All7 A/all13 B decoded source hashes/native128 contracts and actual battle admission/native class; full fresh save/RNG; time-to-entry','branch':'If unavailable assets/readiness, latch or unsupported/layout fallback occurs, preserve observation and record native continuity gap; no reload/start-over or forcing mode'},
  {'id':'cairn','input':'Native neutral point outside actual hand, genuine Cairn hover; bind current enabled Cairn occurrence','observe':'Live cost/title/rules/portrait, trusted input and owned occurrence, new canonical UID and near-row body/native draw/field readouts; complete save','branch':'No legal Cairn/current usable UI: stop branch with gap, no injected hand/card'},
  {'id':'choice','input':'Select READY Cairn; inspect two actual enemy intents/preview alternatives, choose Ironjaw Reaver then ordinary free Order','observe':'Decision rationale: unarmored Reaver admits Hound bonus; alternative Gloam threat/intent remains documented. Actual issued source/target text, HP/energy/acted/hand/damage attribution','branch':'Use current observed UID/geometry/legal preview, never assumed label ordinal; missing legal target aborts branch'},
  {'id':'cardCancelAndPlay','input':'Genuine current Scour lift/Escape/release cancellation, then one ordinary legal Scour release onto current Reaver','observe':'Complete raw cancellation purity, trusted source/index/buttons1/current UID/legal pre-up, exact-once spend/HP change and350ms noqueued-action receipt','branch':'Natural disabled/ready transition not required or fabricated; absent transient remains NOT_OBSERVED'},
  {'id':'turn2','input':'Ordinary visible enabled End turn','observe':'Complete post-enemy-phase raw save, actual intent log/source-target HP/block consequences, refreshed energy/hand/READY; elapsed includes presentation','branch':'Unexpected terminal phase: preserve actual outcome and skip later branches; never force victory or turn'},
  {'id':'starterHand','input':'Ordinary hover first actually drawn Ash and Fen cards if present; no play yet','observe':'Current card ID/index/live ability/cost/stats/ARIA, native portrait src/hash/decode geometry and field native class; first appearance timings','branch':'Seed937240 prior actual drew both in turn2; source prediction only for new run. Missing either records DRAW_NOT_OBSERVED, no Survey/extra turn solely to manufacture it'},
  {'id':'secondAlly','input':'Bind Ash only if actually enabled/current hand/energy>=2/actual allies<2; otherwise Fen if legal under same guards, else skip','observe':'Full before/after raw state and new matching UID/role, portrait-to-near-rear body draw, all actor/name/HP/intent visible geometry; record actual fallback','branch':'With Cairn+one starter allies=2. Do not bind the other turn2 starter: three allies would invalidate native layout even though legally permitted by engine'},
  {'id':'turn3Briar','input':'If budget/phase/current End turn permit, ordinary second End turn, then hover actually drawn Briar','observe':'Actual next enemy response/full hand/energy/phase; first Briar portrait appearance plus unchanged native class/field geometry','branch':'Remaining retained turn2 draw=[sunder,briarcolossus], engine pop draws Briar before reshuffle. This is source prediction, not future observation. Binding Briar with2 living allies is NOT_ATTEMPTED: third ally forces fallback; do not force an ally death or restart'},
 ],
 'evidence':{'fullRawCheckpoints':['fresh encounter','Cairn bound','free Order','held cancelled','Scour played','ordinary End turn2','second ally bound if attempted','ordinary End turn3 if attempted'],'comparison':'Full corresponding opaque saved strings must match A/B under identical inputs; branch/availability mismatch is a reported failed comparison, not normalized away','trustedNativeEvents':'Bounded existing trusted pointer/key references/current source acquisition/latestUID/preup/noqueue/close methods; no synthetic dispatch/global/app/DOM/clock mutation','images':'Four originals total, two per context: turn2 Ash/Fen hand before binding and immediately settled second ally field. Native1440x900 q80, JPEG2MiB cap unchanged. Initial Cairn/Fen/Briar hover remains passive geometry/draw evidence if not photographed; no visual-quality claim for uncaptured states','proof':'Physical5MiB cap; full logical serialized domain separately counted; full gzip byte readback. Complete raw saves remain intact. Store snapshot once with references; selected19 style fields+inner leaf fragments only as explicitly scoped R2 proposal, no complete computedCSS claim','omittedFromOldCorpseProtocol':['1.2s retained corpse and4s expiry captures','duplicate Cairn rich snapshots','all-scene rich snapshot at every gesture'],'retained':'Fixed>=250ms fallen observer if reused; no actionauthority or lifecycle weakening; root/external aliases/fullserved maps/support controls still exact future bindings'},
 'resourcePlan':{'actualWorkMiB':896,'reserveMiB':512,'diskMiB':71,'heapMiB':256,'driverSeconds':60,'wholeSeconds':90,'JPEGBytes':2097152,'physicalProofBytes':5242880,'originalAllocationFailure':'R1 aggregate delta exceeded896MiB; reduced probes are hypothesis, no proven CSS/game cause or increased allowance'},
 'coverageLimits':['Cairn+one second starter body only; Fen/Briar summoned body and upgraded variants unobserved','Whole-native style after third legal binding unsupported by current layout; separate focused layout/hit/readability hypothesis required','Unsupported future enemies/summons may still trigger whole fallback;13 readiness does not certify campaign','Battle-entry asset latch/loading/reentry and1440x900 fit must be observed, cannot be overridden','No complete encounter/campaign, articulated attack animation, continuous motion/readability, human attention/enjoyment or300seconds proven','Gameplay/visual/technical independent reviews may reject; author cannot approve own method or scene'],
 'nextEligibility':'Fresh exact starter strict build/freeze/current alias maps/build gate, proportionate executable caller source+inverse+independent review, Root driver grammar and exact actual resource grant remain mandatory; this protocol alone grants none.'}
put('PROTOCOL.json',protocol)
(P/'PROTOCOL.md').write_text('SOURCE-only proposal: compare the seven-image baseline with the future thirteen-image starter build through genuine Cairn binding, target choice, one Scour, End turn/enemy response, naturally drawn starter hand portraits and one second native ally. Preserve complete timed event/save evidence.\n\nThe accepted source has a concrete capacity limit: native128Layout returns null above two allies or two enemies. A third legal ally triggers whole painted fallback; the unchanged encounter latch can keep it painted for that battle. Therefore bind only Ash (or legal observed Fen fallback) beside Cairn, and hover naturally drawn Fen/Briar without claiming their summoned-body continuity. This is a source-informed60-second prefix, not300-second play or human enjoyment.\n\nPROTOCOL.json contains exact observed branches, resource/evidence limits and coverage losses. Candidate outputs/build/actual remain pending. No runtime, assembly, media decode or canonical mutation occurred.\n')
status={x.split(':')[0]:x.split(':')[1].strip() for x in pathlib.Path('/proc/self/status').read_text().splitlines() if x.startswith(('VmRSS:','VmHWM:'))}
assert all(int(v.split()[0])<24576 for v in status.values())
put('SOURCE-MANIFEST.json',{'protocolSHA256':h(P/'PROTOCOL.json'),'proofSHA256':h(P/'SOURCE-PROOF.json'),'prepareSHA256':h(__file__),'ownRSS':status,'sourceOnly':True,'logicalCapBytes':65536})
assert sum(q.stat().st_size for q in P.rglob('*') if q.is_file())+8192<65536
print(json.dumps({'normal':True,'logicalBeforeTail':sum(q.stat().st_size for q in P.rglob('*') if q.is_file()),'own':status}))
