import json,hashlib,resource
from pathlib import Path
P=Path(__file__).parent;A=Path('/workspace/scratch/starter-family-native128-build-controls-source-author-r1')
def sha(q):return hashlib.sha256(q.read_bytes()).hexdigest()
a=json.loads((P/'AUDIT.json').read_bytes());r=json.loads((P/'review-guard/RESULT.json').read_bytes());assert r['exit_code']==0 and r['failure'] is None and r['memory_events_before']==r['memory_events_after']
gate={'decision':a['decision'],'accepted':True,'controlsSourceEngineeringEligible':True,'controlsPlanSHA256':a['controlsPlanSHA256'],'authorFinalSHA256':a['authorFinalSHA256'],'authorManifestSHA256':a['manifestSHA256'],'candidateSourceDigest':a['candidateSourceDigest'],'methods':{x['name']:x['candidateSHA256'] for x in a['fourMethodDiffForwardInverseVerified']},'fourMethodFullByteInversesVerified':True,'source104To98AndHeld65To59FullInversesVerified':True,'inputCountPrediction':104,'outputCountUnbuiltPrediction':70,'heldOutputCount':65,'originalHeldRowsUnchanged':58,'derivedAliasCountOnly':121,'actualNewAliasCatalogueAccepted':False,'donor115LiteralAliasChainsAndSupport30Checked':True,'actualMaterializationGrant5f57AndNormalClosureVerified':True,'strict13ResourceChecksAndOwnershipUnchanged':True,'resourcePlan':a['resourcePlan'],'activationRequirements':a['activationRequirements'],'RootGOFreshAdmissionAssemblyBuildFinalizeAndIndependentActualFreezeRequired':True,'dependencyQualification':a['dependencyQualification'],'mediaHashQualification':a['mediaHashQualification'],'authorityQualification':a['authorityQualification'],'freshnessRequirements':a['freshness'],'artDefaultRuntimeGameAnimationFunApproval':False,'actualAssemblyBuildCopyPerformed':False,'AUDIT_SHA256':sha(P/'AUDIT.json'),'normalReviewGuardSHA256':sha(P/'review-guard/RESULT.json'),'roleDisclosure':a['roleDisclosure']}
(P/'GATE.json').open('x').write(json.dumps(gate,separators=(',',':'))+'\n')
(P/'REVIEW.md').open('x').write('SOURCE accepted only for a separately granted fresh private starter assembly/strict build. Independently checked author manifest/final/normal guards, all four saved gzip diffs by full forward and reverse byte application, complete104→98 source and65→59 held-output map inverses, exact accepted wiring d9e tuple and four actual materialized sources/5f57 grant/normal closure. Old58 held rows unchanged; replacementview plus6 new PNGs yields65 held rows and unbuilt70 outputs with five future measured code bodies. Derived121 alias keys are a predicted complete domain, not an actual catalogue. Current donor115 literal chains and full input/output memberships/freeze/support30 checked; bulk donor media hashes inherited rather than reread. New6 PNG and materialized source SHA renewed without image decode.\n\nStrict runner and bounded supervisor differ from exact predecessor only by stage path: installed full TSC --noEmit/support30 and Vite publicDirfalse/private cache retained, heap256/work384+reserve512/disk64/stop55/whole60/all13 checks and original root-PID/starttime ownership retained. Assembly64/finalize64 remain; current TSC/Vite package metadata/shared module target checked, no full dependency Merkle claim. Actual full build/readiness/alias/freeze/quality still require later independent review.\n\nAssembly requires explicit Root authorization and exact independent controls gate/PlanSHA plus accepted source tuple/materialization pins; fresh fixed stage only. Code/JSON/new6 PNG input bodies copied to new private regular inodes, old media leaf aliases frozen, support copied and shared node_modules linked without writes. Finalizer requires normal strict closure, rechecks inputs/donor/support, mounts65 held outputs after five actual code outputs, counts104/70 and measures full actual chains exactly against derived keys. No old stage/media/partial output overwrite. Rules/save/input/UID/Cairn7/floor/corpse and private cue behavior unchanged by accepted wiring; current canonical cue composition pending.\n\nReviewer older utility/witness/helper-related work and wiring review disclosed; Cairn authors controls. No assembly/import/method execution/Node/build/browser/Pillow/assetscopy/canonical edits. Source engineering eligibility alone, no scene/art/default/animation/first300/fun approval.\n')
files={str(q.relative_to(P)):{'bytes':q.stat().st_size,'sha256':sha(q)} for q in P.rglob('*') if q.is_file()}
(P/'MANIFEST.json').open('x').write(json.dumps({'files':files,'logicalCapBytes':131072,'allocatedCapClaimed':False,'guardTailReserveBytes':8192,'sourceWorkMiB':64,'reserveMiB':512,'diskAdmissionMiB':64,'ownRSSKiBLimit':24576,'finalGuard':'Separate seal guard ADMISSION/RESULT/EXECUTION follows; final normal closure pin returned.'},separators=(',',':'))+'\n')
n=sum(q.stat().st_size for q in P.rglob('*') if q.is_file());assert n+8192<=131072 and resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
print(json.dumps({'gateSHA256':sha(P/'GATE.json'),'manifestSHA256':sha(P/'MANIFEST.json'),'reviewSHA256':sha(P/'REVIEW.md'),'auditSHA256':sha(P/'AUDIT.json'),'authorFinalSHA256':a['authorFinalSHA256'],'logicalBeforeFinalGuardTails':n,'tailReserveBytes':8192,'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss}))
