import json,hashlib,resource
from pathlib import Path
P=Path(__file__).parent
def sha(q):return hashlib.sha256(q.read_bytes()).hexdigest()
a=json.loads((P/'AUDIT.json').read_bytes());r=json.loads((P/'audit-guard/RESULT.json').read_bytes());assert r['exit_code']==0 and r['failure'] is None and r['memory_events_before']==r['memory_events_after']
assert a['authorR2LogicalBytes']==26524
gate={'decision':a['decision'],'accepted':True,'sourceEngineeringEligible':True,'authorFinalSHA256':'5d8395a94db71d439ba87f9cb3c33bbf37a1d59bf7dfac95c1aa08caea5f9413','controlsPlanSHA256':'7f40607b43f820e0e738b3899b0ab66c61c6acfc3ec42e6af9b6ee362e5b908f','materializeMethodSHA256':'37d70748744934b5b2bd2ef2a23486d5a76b118614c4f0cd27fff6c2836ffb45','candidateSourceDigest':a['candidateSourceDigest'],'mainDecodedSHA256':'d1e71626b4c70679f4ba692b62ccb2aea0dbe5ce74e9a1426b6208fc26a45fe2','helperDecodedSHA256':'17b0ae71bd36d9803d5dd4ddea2e8070a200bbe11ea08ada4ad142bd292c42a9','artSHA256':'28f20bc5118668b0d1570c38078847026b4109f8518726b09d4d4390024e34ab','manifestSHA256':'1e0699b76dc3543b5374df5ff8e33aa81254c6d05c94fe7483247d183308b8af','fourFullByteInversesVerified':True,'all13NativeImageIdentitiesVerifiedWithoutDecode':True,'predictedInputs':104,'predictedOutputsUnbuilt':70,'actualBuildAccepted':False,'privateFitArtScopeOnly':True,'unsupportedFallback':a['unsupportedFamilies'],'canonicalGuidanceCompositionPending':True,'artGameDefaultAnimationFunApproved':False,'materializationRequiresSeparateRootGOExactPrivateDirectoryAndExternalPinCheck':True,'futureStrictBuildAndActualSceneReviewRequired':True,'originalR1FailureGuardsRetained':a['authorFailedGuardsRetained'],'R1LogicalCapQualification':'Original129374 logical≤128KiB retained including three failures; final reserve refusal retained. Active R2 adds fresh26524 logical≤128KiB without modifying R1 or duplicating candidate. Allocation is qualified separately, not physical128KiB claim.','priorRoleDisclosure':a['priorRoleDisclosure'],'AUDIT_SHA256':sha(P/'AUDIT.json'),'normalReviewerGuardSHA256':sha(P/'audit-guard/RESULT.json')}
(P/'GATE.json').open('x').write(json.dumps(gate,separators=(',',':'))+'\n')
(P/'REVIEW.md').open('x').write('Accepted exact R2 starter wiring SOURCE for separately granted private materialization and strict build. Independently decoded bounded gzip main/helper with stored/decoded identities, lengths andmtime0; checked complete immutable R1 membership, all three failed guard histories, R2 final tuple/guards, and four full byte inverses. Predicted104 map equals frozen98 inputs with only main/helper/art/manifest changed plus6 exact assets:94 original entries unchanged. Actual outputs70 are unbuilt.\n\nAll13 PNG byte identities checked without decoding; seven baseline rows unchanged. CorrectedAsh e02e/21be pair used, rejected oldAsh absent; Fen/Briar four asset private-fit eligibility retained. Indexed mapping Cairn0/4,Ash7/8,Fen9/10,Briar11/12 and their single+upgrades aligns body/portrait descriptors. EnemyReaver1/dead6,Gloam2,hunter3/5 remain unchanged. Invalid/missing decoded asset retains all-or-baseline readiness; unsupported summons/allies/enemies reject existing whole-scene eligibility. Main changes only native portrait HTML choice: input buttons/attributes/live rules/save/reducer/accessibility/reduced-motion and floor/corpse sources remain exact frozen spans. Existing admission latch limitations remain; no new readiness, facing, scene or continuous animation claim.\n\nFuture materializer is inert source here. Root must bind exact method/PLAN and select a new private source directory under a fresh source guard; its4 source/manifest body writes are not an independent authorization gate and do not build/copy media. Fresh full TypeScript/build/freeze/alias audit and separately granted scene trial remain. Private baseline cue flag is unchanged; canonical guidance composition pending, no default promotion approval. Reviewer older converter/witness/helper role disclosed; Cairn authors new wiring, this engineering adaptation review does not approve own old art/design. Original caps/failures retained and allocation qualified.\n')
files={str(q.relative_to(P)):{'bytes':q.stat().st_size,'sha256':sha(q)} for q in P.rglob('*') if q.is_file()}
(P/'MANIFEST.json').open('x').write(json.dumps({'files':files,'logicalCapBytes':131072,'allocatedCapClaimed':False,'guardTailReserveBytes':8192,'sourceWorkMiB':64,'reserveMiB':512,'diskAdmissionMiB':64,'ownRSSKiBLimit':24576,'finalSealGuard':'ADMISSION/RESULT/EXECUTION generated after manifest; separate final closure pin returned.'},separators=(',',':'))+'\n')
n=sum(q.stat().st_size for q in P.rglob('*') if q.is_file());assert n+8192<=131072 and resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
print(json.dumps({'gateSHA256':sha(P/'GATE.json'),'manifestSHA256':sha(P/'MANIFEST.json'),'reviewSHA256':sha(P/'REVIEW.md'),'auditSHA256':sha(P/'AUDIT.json'),'logicalBeforeFinalGuardTail':n,'tailReserveBytes':8192,'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss}))
