import json,hashlib,pathlib,os
p=pathlib.Path(__file__).parent
def h(q):return hashlib.sha256(q.read_bytes()).hexdigest()
def put(n,v):(p/n).write_text(json.dumps(v,indent=2)+"\n")
r=json.loads((p/"REVIEW-R2-GUARD/RESULT.json").read_text());assert r["exit_code"]==0 and r["failure"] is None and r["memory_events_before"]==r["memory_events_after"]
proof=json.loads((p/"PROOF.json").read_text())
(p/"REVIEW.md").write_text("""Accept this exact preservation SOURCE method for a later separately granted archive attempt, subject to the final Root input-manifest contract. This is not an archive COMPLETE gate.

The final wrapper makes one pinned spec-loader substitution into the pinned r2 implementation. Five r2 changes reverse exactly to r1; seven original deltas plus the authorization block reverse exactly to the prior pinned preserver. The effective fixed allowlist excludes protected release ZIP/Git packs and prior archive bodies. The prior4513 Tar receives stat-only checks; its coverage inherits the exact INDEX/COMPLETE identities. Inputs are opened read-only; fresh output is confined to the one exclusive new canonical review/archive path, with no original removals or writes. O_NOATIME fallback/ordinary document atime changes are qualified.

The future method copies exact final manifest and grant bodies, streams a single gzip/Tar, compares every new unique body to its representative original bytes on readback, then fsyncs all output. Logical and allocated output totals include controls and must stay under12MiB; timer includes authorization and final receipt work. Terminal totals are printed after the saved RESULT, so a normal outer128+512 return, complete terminal tool-return binding and independent COMPLETE review remain necessary. No subprocess is launched by the publisher.

Trusted manifest boundary: the helper does not full-hash every duplicate logical input path or compare every runtime row hash against freeze maps. Root explicitly commits to full-hashing every row, binding every runtime SHA/size to frozen maps, literal runtimeAuthorities equality to effective SPEC and verified held-media/installed-dependency references. Those checks and closed-input metadata must be pinned in the final manifest; they cannot be claimed as automatic helper guarantees. All now-closed Ash report trees must be truthfully included; NOT_RUN is only for genuinely absent phases. Independent review evidence must remain a pinned external prerequisite or enter via a separately authorized scope successor.

This SOURCE review did not execute/import the publisher, read any Tar/ZIP body, decode media, run Node/build/browser/Git, or create the canonical archive. No self-contained release, game/default/art quality, continuous observation,300-second play or human enjoyment is certified. Original author metadata-locator failure and the reviewer predicate-token failure are preserved. Source sparse aggregate cgroup samples are not exclusive process attribution.
""")
put("GATE.json",{"decision":"ACCEPT_EXACT_PRESERVATION_SOURCE_METHOD_CONDITIONAL_ON_ROOT_FINAL_MANIFEST","methodSHA256":proof["sourcePins"]["preserve-direct-final.py"],"implementationSHA256":proof["sourcePins"]["preserve-direct-r2.py"],"specSHA256":proof["sourcePins"]["SOURCE-SPEC-final.json"],"authorFinalSealSHA256":proof["sourcePins"]["FINAL-SEAL.json"],"PROOF_SHA256":h(p/"PROOF.json"),"sourceEngineeringEligible":True,"finalRootManifestAndGrantRequired":True,"perLogicalRowAndFreezeBindingDelegatedToVerifiedRootManifest":True,"archiveExecuted":False,"COMPLETE":False,"noSelectionOrQualityAcceptance":True,"normalSourceGuardSHA256":h(p/"REVIEW-R2-GUARD/RESULT.json"),"originalFailurePreserved":True})
put("MANIFEST.json",{"files":{str(q.relative_to(p)):{"sha256":h(q),"bytes":q.stat().st_size} for q in sorted(p.rglob("*")) if q.is_file() and q.name not in ("MANIFEST.json","CLOSURE.json","FINAL-SEAL.json")},"lateControls":["SEAL-GUARD/*","CLOSURE.json","FINAL-SEAL.json"],"logicalCapBytes":131072,"sourceOnly":True})
assert sum(q.stat().st_size for q in p.rglob("*") if q.is_file())+8192<=131072
print(json.dumps({"normal":True,"GATE_SHA256":h(p/"GATE.json"),"MANIFEST_SHA256":h(p/"MANIFEST.json"),"logicalBeforeGuardTail":sum(q.stat().st_size for q in p.rglob("*") if q.is_file())}))
