import json,hashlib,resource
from pathlib import Path
P=Path(__file__).parent
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
audit=json.loads((P/'AUDIT.json').read_bytes());r=json.loads((P/'audit-r2-guard/RESULT.json').read_bytes())
assert r['exit_code']==0 and r['failure'] is None and r['memory_events_before']==r['memory_events_after']
a=(P/'audit.py').read_bytes();b=(P/'audit-r2.py').read_bytes();old=b"assert ad['command']==['python','/workspace/scratch/native-checkpoint-root-manifest-r3.py']";new=b"assert ad['command']==['python3','-B','/workspace/scratch/native-checkpoint-root-manifest-r3.py']"
assert a.count(old)==1 and b==a.replace(old,new,1)
gate={'decision':audit['decision'],'accepted':True,'RootFinalManifestEligibleForSeparateArchiveGrant':True,'inputManifestPath':'/workspace/scratch/native-checkpoint-final-input-manifest-root-r3.json','inputManifestSHA256':audit['inputManifestSHA256'],'sourceGateSHA256':'698daceaa2775a0934f825fdf20020050937cf7d2450cf9627114a8485fd97','methodSHA256':'5ad10c515b362ac6434ad6041565a13d74551f53e658c1f65c5ab4a08c10dd0f','implementationSHA256':'9818bfbbb52ff3f4ad173c6c29071c77531011c95bda404f61636f9b3fad0568','specSHA256':'13d1c918f57c103929e098a03ce90ba7574161e1e0ae75e598960812e7ec6e0f','roots':141,'logicalRows':1278,'runtimeCodeRows':86,'fullLogicalHashesIndependentlyVerified':True,'runtimeAuthoritiesLiterallyEqualToEffectiveSPEC':True,'closedPhases':'All six future Ash roots CLOSED_INCLUDED; no NOT_RUN phases','priorArchiveBodyOpened':False,'mediaQualification':audit['mediaQualification'],'closureQualification':audit['closureQualification'],'AUDIT_SHA256':sha(P/'AUDIT.json'),'normalReviewerGuardSHA256':sha(P/'audit-r2-guard/RESULT.json'),'failedReaderPreserved':'audit.py and audit-guard; incorrect python vs python3 -B expected argv. Fresh audit-r2.py changes only exact argv assertion. Root R1/R2 failures remain outside fixed archive scope and require separately pinned publication handling.','rootManifestFailuresCertified':False,'archiveExecuted':False,'artGameDefaultReleaseApproved':False,'prerequisites':'Root fresh archive-only grant, current push, source actors closed, 128+512 admission, ordinary disk64 and internal76MiB; conditional preserver SOURCE gate still applies. New actual archive COMPLETE needs separate full streaming verification.'}
assert gate['sourceGateSHA256']!=audit['pins']['/workspace/scratch/native-aftermath-starter-checkpoint-source-independent-r1/GATE.json']
# Exact gate pin correction is authored here, before any gate exists.
gate['sourceGateSHA256']=audit['pins']['/workspace/scratch/native-aftermath-starter-checkpoint-source-independent-r1/GATE.json']
(P/'GATE.json').open('x').write(json.dumps(gate,separators=(',',':'))+'\n')
(P/'REVIEW.md').open('x').write('Accepted the corrected R3 input manifest for a separately granted archive. Full logical body SHA/length and whole named regular memberships, both exact 43-code freeze maps, literal effective runtimeAuthorities, all 230 current alias chains, both support30 maps and four tool-package metadata pins per stage verified. Media bodies were not independently reopened here; Root R3 and prior build body checks are relied upon. Prior4513 pinned index/COMPLETE read and archive STAT only; no protected archive body opened. All six completed Ash phases included. Root source guard normal0 and events unchanged. No dependency-tree Merkle, self-contained release, full metadata preservation, archive completion, art, game/default or fun approval.\n\nEarlier converter/witness/helper involvement disclosed; preservation implementation belongs to a different author. This checks that preservation contract and Root manifest, not creative approval of the old utility. Original reviewer argv failure and Root R1/R2 failures remain qualified; corrected reader exact one-assertion inverse checked. Root declares named phase closure; no universal workspace PID claim.\n')
leaves={str(p.relative_to(P)):{'sha256':sha(p),'bytes':p.stat().st_size} for p in P.rglob('*') if p.is_file()}
m={'files':leaves,'familyLogicalCapBytes':65536,'allocationCapClaimed':False,'sourceWorkMiB':64,'reserveMiB':512,'diskAdmissionMiB':64,'ownRSSKiBLimit':24576,'guardTailReserveBytes':8192,'archiveExecuted':False,'finalGuardClosure':'Separate seal guard RESULT/ADMISSION/EXECUTION follows this manifest; all earlier guard files pinned.'}
(P/'MANIFEST.json').open('x').write(json.dumps(m,separators=(',',':'))+'\n')
total=sum(p.stat().st_size for p in P.rglob('*') if p.is_file());assert total+8192<=65536;assert resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
print(json.dumps({'gateSHA256':sha(P/'GATE.json'),'manifestSHA256':sha(P/'MANIFEST.json'),'logicalBytesBeforeSealGuardTails':total,'tailReserveBytes':8192,'allocatedBytesBeforeSealGuardTails':sum(p.stat().st_blocks*512 for p in P.rglob('*') if p.is_file()),'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'inverse':'Only expected Root interpreter argv corrected; original failed reader retained.'}))
