import{chromium,expect}from'/workspace/Roguelike-deckbuilder/node_modules/@playwright/test/index.mjs';import{tsImport}from'/workspace/Roguelike-deckbuilder/node_modules/tsx/dist/esm/api/index.mjs';import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import assert from'node:assert/strict';import{pathToFileURL}from'node:url';
const root='/workspace/Roguelike-deckbuilder',prototype='/workspace/scratch/ui-v07-root',out='/workspace/scratch/ui-v07-independent';const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const paths=['src/main.ts','src/input.ts','src/arena.ts','src/style.css','dist/index.html','dist/build-provenance.json'];const fingerprints=directory=>Object.fromEntries(paths.map(p=>[p,hash(fs.readFileSync(path.join(directory,p)))]));
const report={scope:'Independent actual browser old0.6.1 vs isolated hold-hint prototype; synthetic standard pad/visibility, no physical/native claim',before:{baseline:fingerprints(root),prototype:fingerprints(prototype)},results:[],pageErrors:[]};const{createGame,applyAction,validateState}=await tsImport(pathToFileURL(root+'/src/engine.ts').href,import.meta.url);
const fixture=applyAction(createGame(121),{type:'travel',choice:'battle'});fixture.enemies=fixture.enemies.slice(0,1);fixture.enemies[0].hp=1;fixture.enemies[0].block=0;const pool=[...fixture.hand,...fixture.draw,...fixture.discard];const scour=pool.indexOf('scour');assert.ok(scour>=0);fixture.hand=[pool.splice(scour,1)[0]];fixture.draw=pool;fixture.discard=[];assert.ok(validateState(fixture));const expected=JSON.stringify(applyAction(fixture,{type:'play',index:0,target:fixture.enemies[0].uid}));const fixtureEvidence={scope:'Structurally valid diagnostic1HP opponent and actualScour moved from conserved pile; not earned playthrough',fixture,expected:JSON.parse(expected)};if(fs.existsSync(out+'/fixture.json'))assert.deepEqual(JSON.parse(fs.readFileSync(out+'/fixture.json','utf8')),fixtureEvidence);else fs.writeFileSync(out+'/fixture.json',JSON.stringify(fixtureEvidence,null,2)+'\n',{flag:'wx'});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
async function load(port,trial,width=1280){const context=await browser.newContext({viewport:{width,height:720}}),page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(e.message));await page.addInitScript(({fixture,trial})=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(fixture));localStorage.setItem('hollowpact.tutorial.v2','yes');localStorage.setItem('hollowpact.settings.v2',JSON.stringify({mute:true,volume:0,motion:trial!=='initial-reduced'}));window.__pad={index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(window.__pad,'id',{get(){throw Error('Review device ID accessed');}});window.__reads=0;Object.defineProperty(navigator,'getGamepads',{value:()=>{window.__reads++;return[window.__pad];}});window.__motionEvents=[];window.matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',event=>window.__motionEvents.push({matches:event.matches,time:performance.now()}));window.__hints=[];const descriptor=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');Object.defineProperty(Element.prototype,'innerHTML',{...descriptor,set(value){descriptor.set.call(this,value);if(this.classList.contains('keyboard-hint'))window.__hints.push({text:this.textContent,held:document.querySelector('#app')?.classList.contains('settling-combat'),time:performance.now()});}});},{fixture,trial});await page.goto(`http://127.0.0.1:${port}`);await page.bringToFront();await page.locator('[data-ui="resume"]').click();await page.waitForFunction(()=>window.__reads>=2);return{context,page};}
async function snapshot(page){return page.evaluate(()=>{const hint=document.querySelector('.keyboard-hint'),rect=hint?.getBoundingClientRect(),parent=hint?.closest('.turn-controls')?.getBoundingClientRect();return{held:document.querySelector('#app').classList.contains('settling-combat'),hint:hint?.textContent,aria:hint?.getAttribute('aria-label'),hintVisible:!!rect&&rect.height>0&&!!hint.closest('#dock:not([hidden])'),font:hint?parseFloat(getComputedStyle(hint).fontSize):null,insideParent:!!rect&&!!parent&&rect.left>=parent.left-1&&rect.right<=parent.right+1&&rect.top>=parent.top-1&&rect.bottom<=parent.bottom+1,dialog:document.querySelector('dialog').open,save:localStorage.getItem('hollowpact.run.v2'),storage:{...localStorage},busy:document.querySelector('#scene-ui').getAttribute('aria-busy'),announcer:document.querySelector('#announcer').textContent,reads:window.__reads};});}
async function pad(page,index,pressed,sample=true){const reads=await page.evaluate(({index,pressed})=>{window.__pad.buttons[index]={pressed,value:pressed?1:0};return window.__reads;},{index,pressed});if(sample)await page.waitForFunction(reads=>window.__reads>=reads+2,reads,{timeout:1000});}
async function kill(page,controller=false){if(controller){await page.locator('[data-ui="play-card"]').focus();await pad(page,0,true);await pad(page,0,false);await pad(page,0,true);}else{await page.locator('[data-ui="play-card"]').click();await page.locator('.enemy.valid-target').click();}const snap=await snapshot(page);assert.equal(snap.save,expected);return snap;}
async function stableStorage(page,before){const now=(await snapshot(page)).storage;const expectedStorage={...before.storage,'hollowpact.run.v2':expected};assert.deepEqual(now,expectedStorage);}
try{
for(const{label,port}of[{label:'baseline',port:4173},{label:'prototype',port:4189}]){
 for(const trial of['keyboard-settle','controller-pause','mode-switch','initial-reduced','media-reduce','hidden-boundary']){
  const{context,page}=await load(port,trial);const before=await snapshot(page);const controller=['controller-pause','mode-switch','hidden-boundary'].includes(trial);const immediate=await kill(page,controller);const result={label,port,trial,immediate};
  if(trial==='initial-reduced'){assert.equal(immediate.held,false);assert.equal(immediate.hintVisible,false);}
  else{
   assert.equal(immediate.held,true);assert.equal(immediate.busy,'true');assert.equal(immediate.hintVisible,true);assert.ok(immediate.insideParent);assert.equal(immediate.announcer,'Contract cleared.');
   if(label==='prototype'){assert.match(immediate.hint,/Final impact resolving/);assert.match(immediate.hint,controller?/Start Pause/:/Esc.*Pause/);assert.doesNotMatch(immediate.hint,/Choose|Back|Inspect|End turn|Targets|Move|Regions/);}else assert.match(immediate.hint,/End turn/);
   if(trial==='keyboard-settle'){await page.keyboard.press('e');assert.equal((await snapshot(page)).save,expected);await page.screenshot({path:out+'/'+label+'-keyboard-hold.png'});}
   if(trial==='controller-pause'||trial==='mode-switch'){
    await pad(page,0,false);await pad(page,1,true);const blocked=await snapshot(page);assert.equal(blocked.held,true);assert.equal(blocked.dialog,false);assert.equal(blocked.save,expected);result.afterB=blocked;await pad(page,1,false);
    if(trial==='mode-switch'){await page.keyboard.press('e');const keyboard=await snapshot(page);assert.equal(keyboard.held,true);assert.equal(keyboard.save,expected);result.keyboardSwitch=keyboard;if(label==='prototype')assert.match(keyboard.hint,/Esc.*Pause/);}
    await pad(page,9,true);await expect(page.locator('#dialog-title')).toHaveText('Campaign paused');assert.equal((await snapshot(page)).held,false);assert.equal((await snapshot(page)).save,expected);result.hintHistory=await page.evaluate(()=>window.__hints);
    if(label==='prototype')assert.ok(result.hintHistory.some(h=>h.held&&h.text==='Final impact resolvingStart Pause'),'Accepted Start did not refresh controller held hint before safe pause');
    await pad(page,9,false);await page.locator('[data-ui="close"]').first().click();
   }
   if(trial==='media-reduce'){await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>window.__motionEvents.some(event=>event.matches),undefined,{timeout:500});assert.equal((await snapshot(page)).held,false);}
   if(trial==='hidden-boundary'){await page.evaluate(()=>{window.__hidden=true;Object.defineProperty(document,'hidden',{configurable:true,get:()=>window.__hidden});document.dispatchEvent(new Event('visibilitychange'));});const hidden=await snapshot(page);assert.equal(hidden.held,false);await pad(page,0,true,false);assert.equal((await snapshot(page)).reads,hidden.reads);assert.equal((await snapshot(page)).save,expected);await page.evaluate(()=>{window.__hidden=false;document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(()=>window.__reads>=2);await pad(page,0,true);assert.equal((await snapshot(page)).save,expected);await pad(page,0,false);result.visibilityEmulated=true;}
  }
  await expect(page.locator('[data-action="reward"]').first()).toBeVisible();const final=await snapshot(page);assert.equal(final.held,false);assert.equal(final.save,expected);assert.equal(final.hintVisible,false);await stableStorage(page,before);result.final={held:final.held,hintVisible:final.hintVisible,saveSHA256:hash(final.save),announcer:final.announcer,storageUnchangedApartFromAcceptedKill:true};report.results.push(result);await context.close();
 }
}
assert.deepEqual(report.pageErrors,[]);report.after={baseline:fingerprints(root),prototype:fingerprints(prototype)};assert.deepEqual(report.after,report.before);report.sourcesUnchanged=true;report.status='All12 independent behavior/comparison paths passed; readability still to inspect';
}catch(error){report.failure=error.stack;process.exitCode=1;}finally{await browser.close();fs.writeFileSync(out+'/results-r2.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:report.status,failure:report.failure,cases:report.results.length,sourcesUnchanged:report.sourcesUnchanged,heldFonts:report.results.filter(r=>r.immediate.held).map(r=>({label:r.label,trial:r.trial,font:r.immediate.font,hint:r.immediate.hint})),pageErrors:report.pageErrors},null,2));}
