import {chromium} from '/workspace/Roguelike-deckbuilder/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
const root='/workspace/Roguelike-deckbuilder',out=root+'/reviews/arena-v0.4-depth-prototype';
const base=JSON.parse(readFileSync(root+'/reviews/screenshots-v0.3/weak-binding-fixture.json'));const duel=structuredClone(base);duel.allies[0]={...duel.allies[0],hp:20,maxHp:20,attack:7,acted:false};duel.enemies=duel.enemies.slice(0,1);duel.enemies[0]={...duel.enemies[0],hp:30,maxHp:30,block:0,species:'warlord',cardId:'ironjaw'};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-gpu']});const page=await browser.newPage({viewport:{width:1280,height:1120}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/src/arena.ts');await page.setContent('<style>body{margin:0;background:#111}canvas{width:1280px;height:540px;display:block}</style><canvas id="baseline"></canvas><canvas id="candidate"></canvas>');
await page.evaluate(async()=>{window.clock=1000;window.q=new Map();window.seq=0;window.requestAnimationFrame=cb=>{const id=++seq;q.set(id,cb);return id};window.cancelAnimationFrame=id=>q.delete(id);window.step=ms=>{for(let t=0;t<ms;t+=16.6666667){clock+=Math.min(16.6666667,ms-t);const callbacks=[...q.values()];q.clear();callbacks.forEach(cb=>cb(clock))}};const b=await import('/src/arena.ts'),c=await import('/reviews/arena-v0.4-depth-prototype/arena.ts');window.shadows=[];const original=CanvasRenderingContext2D.prototype.createRadialGradient;CanvasRenderingContext2D.prototype.createRadialGradient=function(...args){if(this.canvas.id)shadows.push({canvas:this.canvas.id,t:clock,args,alpha:this.globalAlpha});return original.apply(this,args)};window.engine=await import('/src/engine.ts');window.factories=[b.createArena,c.createArena];window.arenas=factories.map((f,i)=>f(document.querySelectorAll('canvas')[i]));window.reset=before=>{arenas.forEach(a=>a.dispose());window.arenas=factories.map((f,i)=>f(document.querySelectorAll('canvas')[i]));arenas.forEach(a=>a.render(before));step(450)};});await page.waitForTimeout(400);
const report={method:'Own isolated A/B implementation experiment, actual artwork and two renderers sharing controlled16.67ms RAF. Not independent, production cadence, or human playtest.',cases:[],errors};
async function capture(name){const snaps={};for(const id of ['baseline','candidate']){await page.locator('#'+id).screenshot({path:`${out}/${name}-${id}.png`});snaps[id]=await page.locator('#'+id).evaluate(c=>c.toDataURL())}return snaps.baseline===snaps.candidate;}
await page.evaluate(before=>reset(before),duel);await capture('idle');
let event=await page.evaluate(before=>{const action={type:'attack',unit:before.allies[0].uid,target:before.enemies[0].uid};const result=engine.applyActionWithEvents(before,action);arenas.forEach(a=>a.playAction(action,before,result.state,result.events));return result.events},duel);let prev=0;for(const at of [100,240,350,580]){await page.evaluate(ms=>step(ms),at-prev);prev=at;const identical=await capture('attack-'+at);report.cases.push({name:'attack-'+at,identical,events:event});}
const terminal=structuredClone(duel);terminal.allies[0].hp=2;terminal.enemies[0].hp=2;terminal.enemies[0].block=3;await page.evaluate(before=>{reset(before);const action={type:'attack',unit:before.allies[0].uid,target:before.enemies[0].uid},r=engine.applyActionWithEvents(before,action);arenas.forEach(a=>a.playAction(action,before,r.state,r.events));window.terminal=r},terminal);await page.evaluate(()=>step(420));await capture('mutual-death-420');report.terminal=await page.evaluate(()=>({events:terminal.events,phase:terminal.state.phase,busy:arenas.map(a=>a.busyMs())}));
const full=structuredClone(duel);full.allies=Array.from({length:6},(_,i)=>({...duel.allies[0],uid:'aQ'+i,species:['hound','stalker','colossus','spider','hound','stalker'][i]}));full.enemies=Array.from({length:6},(_,i)=>({...duel.enemies[0],uid:'eQ'+i,species:['warlord','necromancer','wraith','dragon','thrall','warlord'][i]}));await page.evaluate(before=>{reset(before);const action={type:'attack',unit:before.allies[0].uid,target:before.enemies[2].uid},r=engine.applyActionWithEvents(before,action);arenas.forEach(a=>a.playAction(action,before,r.state,r.events));step(240)},full);await capture('full12-contact');
report.factories=await page.evaluate(()=>factories.map(f=>f.toString().includes('paintFloor')));report.shadowSamples=await page.evaluate(()=>shadows);report.checks=await page.evaluate(async()=>{const promises=arenas.map(a=>a.waitForPresentation());document.documentElement.dataset.reducedMotion='true';await Promise.resolve();await Promise.all(promises);const before=[...document.querySelectorAll('canvas')].map(c=>c.toDataURL());step(500);const after=[...document.querySelectorAll('canvas')].map(c=>c.toDataURL());return{busy:arenas.map(a=>a.busyMs()),reducedStable:before.map((s,i)=>s===after[i])}});writeFileSync(out+'/comparison.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
