import os,json,hashlib,resource
from pathlib import Path
P=Path(__file__).parent;S=Path('/workspace/scratch/wording-grounded-trials-checkpoint-source-independent-r2');A=Path('/workspace/scratch/wording-grounded-trials-checkpoint-source-author-r1');O=Path('/workspace/scratch/wording-grounded-trials-checkpoint-output-root-r1')
def pin(p):
 h=hashlib.sha256();n=0
 with p.open('rb')as f:
  while b:=f.read(65536):h.update(b);n+=len(b)
 return {'path':str(p),'sha256':h.hexdigest(),'bytes':n}
def body(v):return(json.dumps(v,indent=2,sort_keys=True)+'\n').encode()
c=json.loads((P/'COMPLETE-CHECKS.json').read_bytes());guards=[]
for d in sorted(P.glob('*guard-*')):
 r=json.loads((d/'RESULT.json').read_bytes());assert r['memory_events_before']==r['memory_events_after'];assert 'all child group processes closed'in r['scope']
 guards.append({'path':str(d),'resultSHA256':pin(d/'RESULT.json')['sha256'],'exitCode':r['exit_code'],'samples':len(r['samples']),'minimumSampledHeadroomBytes':min(x['headroom']for x in r['samples']),'eventsUnchanged':True,'observedChildGroupClosed':True})
assert [x['exitCode']for x in guards].count(0)==2 and [x['exitCode']for x in guards].count(1)==1
assert pin(S/'GATE.json')['sha256']=='8a260e2815faa8e54671b1d4e7c03df61ebaaea2dc6b4958c3798a12cf83e7f4'
support=json.loads((A/'MANIFEST.json').read_bytes())['baselineRequiredPublishedSupport'];assert pin(Path(support['path']))['sha256']==support['sha256']
review={'decision':'ACCEPT_COMPLETE_WORDING_AND_GROUNDED_TRIALS_BYTE_PRESERVATION_ONLY','completePreservationAccepted':True,
 'findings':['Fresh compressed archive SHA/length and all receipt hashes match the completed Root run. The full archive was streamed and all 711 regular blobs/<SHA256> members decoded, hashed and compared byte-for-byte with retained originals. No duplicate, unexpected, link or unsafe member was found; decoded original bytes total 14,555,377.',
 'All 952 logical original paths freshly match full SHA and length (18,255,971 aggregate logical bytes). Exactly 722 logical rows use 711 new unique bodies, so eleven are duplicate logical identities. Exactly 227 ce0f and three f912 rows use older capsules; their current original bodies and exact prior-index identities match. Both older compressed archives/indexes were freshly fully hashed; exact accepted prior COMPLETE gates bind inherited member readback, which was not replayed.',
 'INDEX roots, all rows, roles, domains and runtime authorities exactly reproduce the pinned PLAN. All three complete frozen runtime input/output maps (wording 89/56, grounded pixel 98/64, selected rollback 88/56) bind preserved logical source/code entries or explicitly pinned external media entries. Both eight-JPEG actuals, both forty-control sets, nested stored gzip bodies, raw checkpoint identities and original review/control/failure histories are retained.',
 'All seven original review decisions remain verbatim, including the pixel default/courtyard/payoff rejection and rejected expiry source. All four held metadata docs retain exact bytes. Optional generated starter master, failed alpha diagnostic and negative source prototype remain unimplemented; the mutable successor is excluded.',
 'Root actual guard is normal0, six sampled rows, unchanged memory events and recorded child-group closure. The exact terminal stdout supplies final elapsed 0.507944636978209 seconds, own peak RSS 15,855,616 bytes, output logical 8,408,132 bytes and allocated 8,421,376 bytes. Current output file membership and both sizes independently match. The 128+512/disk64 grant, own24/time60/16MiB limits passed in their recorded scope.'],
 'qualifications':['This accepts byte and logical preservation only. It neither publishes/selects the candidate nor authorizes deletion, storage retirement, canonical edits or quality promotion.',
 'Prior-capsule member decoding is inherited from the exact accepted COMPLETE gates, not a new old-capsule replay. Nested logical gzip equality is inherited from retained independent actual/source byte receipts; stored gzip bytes are freshly hashed. Complete saved-string and wrapper hash domains remain distinct; no new gameplay/motion proof is claimed.',
 'Game media, historical master references, installed node_modules and both earlier capsule/index/COMPLETE authorities remain external dependencies. The exact published predecessor preserver remains required and freshly matches. The whole immutable source-author and SOURCE-review families, including failed r1, actual grant/guard/terminal and this COMPLETE family must accompany later publication; this archive alone is not a self-contained release.',
 'Root read observations contain four prior archive/index reads, 711 writes and 711 byte-readbacks. No O_NOATIME fallback is recorded. Own full-source and decoded-member read file stats stayed equal, but this is not a universal metadata, inode/rights replay or parent-directory race proof. Original paths remain physical; no timestamp was explicitly reset.',
 'Archive files were fsynced; the reviewed helper lacks directory-entry fsync after mkdir/rename. No crash-durable directory transaction, automatic restoration or full rollback guarantee is inferred from normal readback. Sparse guard samples are not continuous or exclusive resource attribution.',
 'Pixel depth, sustained corpse contact, transient coverage and default selection remain rejected/qualified by their retained reviews. No animation, first300, human enjoyment, fully pixel presentation or wider interaction reliability is approved.'],
 'reviewMethodFailure':{'originalScript':'verify-complete-r2.py','originalGuard':'complete-guard-r2','exitCode':1,'reason':'After completing new archive and all logical original byte checks, reviewer incorrectly required write-specific stat fields on readback observations. No archive/source mutation occurred. Exact failed script/log/guard remain unchanged. Fresh r3 checks write/readback scopes separately and passed normal0.','bootstrapAndToolReadbacksUnmetered':True},
 'independentOwnResources':{'profileMiB':[64,512,64],'maxRecordedOwnRSSBytes':c['ownRSSBytes'],'observedGuards':guards,'finalSealerForkedSourceChildUnmetered':True,'toolTransportResourcesUnmetered':True},'checks':pin(P/'COMPLETE-CHECKS.json'),'ownObservedGuardChildrenClosed':True}
gate={'decision':review['decision'],'completePreservationAccepted':True,'archiveSHA256':'451347c174a3fe78e5f7b6ef22736b7cfbbd33b39fd04ea20556730bb3b15a8b','archivePath':str(O/'evidence-451347c174a3fe78e5f7b6ef22736b7cfbbd33b39fd04ea20556730bb3b15a8b.tar.gz'),'index':pin(O/'INDEX.json'),'readObservations':pin(O/'READ-OBSERVATIONS.json'),'result':pin(O/'RESULT.json'),'plan':pin(A/'PLAN.json'),'method':pin(A/'preserve-checkpoint.py'),'sourceGate':pin(S/'GATE.json'),'publishedBaselineSupport':pin(Path(support['path'])),'fullDecodedNewMemberByteReadback':True,'all952LogicalOriginalBodiesMatched':True,'old230ReferenceReadbackInheritedAndFreshOriginalHashes':True,'allOriginalPathsRetained':True,'notSelfContainedRelease':True,'publicationOrSelectionAuthorized':False,'retirementAuthorized':False,'gameOrArtQualityApproved':False,'requiresSeparateRootJudgmentAndConfirmedCurrentPushForAnyLaterPublicationSelection':True,'TOOL_GUARD_CLOSED':True}
pending={'REVIEW.json':body(review),'GATE.json':body(gate)}
existing=[dict(pin(x),relativePath=str(x.relative_to(P)))for x in sorted(P.rglob('*'))if x.is_file()]
manifest={'completePreservationReview':True,'familyLogicalCapBytes':131072,'failedSourceAssertionPreserved':True,'bodies':existing+[{'path':str(P/k),'relativePath':k,'bytes':len(v),'sha256':hashlib.sha256(v).hexdigest()}for k,v in pending.items()]}
pending['MANIFEST.json']=body(manifest);base=sum(x['bytes']for x in existing)+sum(len(v)for v in pending.values())
final={'sealed':True,'completePreservationAccepted':True,'TOOL_GUARD_CLOSED':True,'archiveCreatedByReviewer':False,'gateSHA256':hashlib.sha256(pending['GATE.json']).hexdigest(),'reviewSHA256':hashlib.sha256(pending['REVIEW.json']).hexdigest(),'manifestSHA256':hashlib.sha256(pending['MANIFEST.json']).hexdigest(),'familyLogicalCapBytes':131072,'familyLogicalBytes':0,'finalSealerOwnRSSBytes':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024,'finalSealerGuarded':False}
for _ in range(5):final['familyLogicalBytes']=base+len(body(final))
pending['FINAL-SEAL.json']=body(final);assert base+len(pending['FINAL-SEAL.json'])==final['familyLogicalBytes']<=131072;assert final['finalSealerOwnRSSBytes']<24*1048576
for k,v in pending.items():
 with(P/k).open('xb')as f:f.write(v);f.flush();os.fsync(f.fileno())
fd=os.open(P,os.O_DIRECTORY|os.O_RDONLY);os.fsync(fd);os.close(fd)
assert sum(x.stat().st_size for x in P.rglob('*')if x.is_file())==final['familyLogicalBytes']
print(json.dumps(final,sort_keys=True))
