import{createGame,applyActionWithEvents,legalActions,validateState}from'../../src/engine.ts';import{cuesForTransition}from'./routing.mjs';import fs from'node:fs';import assert from'node:assert/strict';
let state=createGame(1,1);const rows=[];
function accepted(action){const previous=state;const snapshot=JSON.stringify(previous);const transition=applyActionWithEvents(previous,action);assert.equal(JSON.stringify(previous),snapshot);assert.ok(validateState(transition.state));const observed=JSON.stringify(transition);const cues=cuesForTransition(previous,transition.state,transition.events,action);assert.equal(JSON.stringify(previous),snapshot);assert.equal(JSON.stringify(transition),observed);rows.push({action,events:transition.events,cues,validState:true,inputUnchanged:true,observerInputsAndRngUnchanged:true});state=transition.state;return{events:transition.events,cues};}
accepted(legalActions(state).find(action=>action.type==='travel'&&action.choice==='battle'));
const summon=legalActions(state).find(action=>action.type==='play'&&state.hand[action.index]==='cairnhound');assert.ok(summon,'Seed1 actual legal hound summon');const arrival=accepted(summon);assert.ok(arrival.events.some(event=>event.type==='summon'));assert.ok(arrival.cues.some(cue=>cue.cue==='summon_arrival'));
const command=legalActions(state).find(action=>action.type==='attack');assert.ok(command);const strike=accepted(command);assert.ok(strike.events.some(event=>event.type==='hit'&&event.kind==='command'));assert.ok(strike.cues.some(cue=>cue.cue==='hound_bite'));
if(state.phase==='battle')accepted({type:'endTurn'});
const selected=JSON.parse(fs.readFileSync('reviews/arena-v0.5-evidence/fixtures.json','utf8')).filter(fixture=>['dragon-area-seven-hits','dragon-one-target-bite','dragon-area-fully-blocked','two-dragons-fourteen-hits'].includes(fixture.name));const multi=[];
for(const fixture of selected){assert.ok(validateState(fixture.before));const before=JSON.stringify(fixture);const transition=applyActionWithEvents(fixture.before,fixture.action);assert.ok(validateState(transition.state));assert.deepEqual(transition.state,fixture.state);assert.deepEqual(transition.events,fixture.events);const observed=JSON.stringify(transition);const cues=cuesForTransition(fixture.before,transition.state,transition.events,fixture.action);assert.equal(JSON.stringify(transition),observed);assert.equal(JSON.stringify(fixture),before);assert.equal(cues.filter(cue=>cue.cue==='dragon_breath').length,fixture.name==='two-dragons-fourteen-hits'?2:1);if(fixture.name==='dragon-area-fully-blocked')assert.equal(cues.filter(cue=>cue.cue==='hunter_wound').length,0);multi.push({name:fixture.name,schema:fixture.before.schema,scope:'Preserved legacy schema2 fixture recomputed with current frozen dual-generation reducer',canonicalStateAndEventsMatch:true,observerInputAndRngUnchanged:true,eventCount:transition.events.length,cues});}
fs.writeFileSync('scratch/audio-v07/source-fixtures.json',JSON.stringify(selected,null,2)+'\n');
fs.writeFileSync('scratch/audio-v07/actual-event-evidence.json',JSON.stringify({seed:1,difficulty:1,scope:'Actual pure reducer schema3 hound transitions plus canonical recomputation of preserved legacy multitarget fixtures. No runtime audio integration or listening.',rows,multitarget:multi},null,2)+'\n');console.log('Actual schema3 hound and canonical legacy multitarget events routed correctly; observer inputs/RNG unchanged.');
