/** Isolated audio controller. No autoplay, idle loop, telemetry or runtime storage keys. */
export class PrototypePlayer{
 constructor(){this.context=null;this.master=null;this.cache=new Map();this.active=new Set();this.variant=0;this.muted=false;this.volume=.35;this.enabled=false;this.events=[];}
 async enable(){this.context??=new AudioContext({sampleRate:48000});if(!this.master){this.master=this.context.createGain();const limiter=this.context.createDynamicsCompressor();limiter.threshold.value=-12;limiter.knee.value=6;limiter.ratio.value=4;limiter.attack.value=.003;limiter.release.value=.14;this.master.connect(limiter);limiter.connect(this.context.destination);}await this.context.resume();this.enabled=true;this.settings(this.muted,this.volume);}
 settings(muted,volume){this.muted=!!muted;this.volume=Math.max(0,Math.min(1,volume));if(this.master){this.master.gain.cancelScheduledValues(this.context.currentTime);this.master.gain.setTargetAtTime(this.muted?0:this.volume,this.context.currentTime,.008);}if(this.muted||!this.volume){for(const source of this.active){try{source.stop(this.context.currentTime+.03);}catch{}}}}
 async load(cue,variant){const key=`${cue}-${variant}`;if(!this.cache.has(key)){const context=this.context;const promise=fetch(new URL(`wav/${key}.wav`,import.meta.url)).then(response=>{if(!response.ok)throw new Error('Offline prototype asset unavailable');return response.arrayBuffer();}).then(bytes=>context.decodeAudioData(bytes)).catch(error=>{this.cache.delete(key);throw error;});this.cache.set(key,promise);}return this.cache.get(key);}
 schedule(buffer,cue,variant,gain,at){if(!this.enabled||this.muted||!this.volume||this.active.size>=8)return false;const source=this.context.createBufferSource();source.buffer=buffer;const voice=this.context.createGain();voice.gain.value=Math.min(1,Math.max(0,gain));source.connect(voice);voice.connect(this.master);this.active.add(source);source.onended=()=>{this.active.delete(source);source.disconnect();voice.disconnect();};source.start(at);this.events.push({cue,variant,gain,at});return true;}
 async play(cue,gain=.8,offset=0){if(!this.enabled||this.muted||!this.volume)return false;const variant=(this.variant++%3)+1;const buffer=await this.load(cue,variant);if(!this.context)return false;return this.schedule(buffer,cue,variant,gain,this.context.currentTime+Math.min(.4,Math.max(0,offset)));}
 async playBatch(cues){if(!this.enabled||this.muted||!this.volume)return[];const prepared=await Promise.all(cues.slice(0,8).map(async cue=>{const variant=(this.variant++%3)+1;return{...cue,variant,buffer:await this.load(cue.cue,variant)};}));if(!this.context)return[];const start=this.context.currentTime+.02;return prepared.map(cue=>this.schedule(cue.buffer,cue.cue,cue.variant,cue.gain??.8,start+Math.min(.4,Math.max(0,cue.offset??0))));}
 async dispose(){this.settings(true,0);if(this.context)await this.context.close();this.active.clear();this.context=null;this.master=null;this.enabled=false;this.cache.clear();}
}
