import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import {createHash} from 'node:crypto';
const paths=['src/main.ts','src/style.css','src/arena.ts','src/engine.ts','src/content.ts','index.html'];const hashes=async()=>Object.fromEntries(await Promise.all(paths.map(async p=>[p,createHash('sha256').update(await fs.readFile(p)).digest('hex')])));
const before=await hashes();const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const context=await browser.newContext({viewport:{width:1440,height:900}});await context.addInitScript(()=>{localStorage.setItem('lanternbound.settings.v1',JSON.stringify({motion:false,mute:true,volume:.25}));});const page=await context.newPage();const captureCanvas=async()=>page.screenshot({clip:await page.locator('#arena').boundingBox()});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173/');await page.locator('[data-ui=new]').click();await page.locator('#seed').fill('117');await page.getByRole('button',{name:'Light the lantern'}).click();await page.locator('[data-ui=learned]').click();await page.locator('[data-action=travel][data-choice=battle]').click();await page.locator('[data-ui=play-card][data-index="0"]').click();
await page.waitForTimeout(120);await page.screenshot({path:'reviews/screenshots-v0.1/recheck-battle-1440.png'});
await page.locator('[data-ui=settings]').click();await page.locator('#motion').check();await page.locator('[data-ui=close]').first().click();await page.waitForTimeout(120);const onA=await captureCanvas();await page.waitForTimeout(250);const onB=await captureCanvas();await page.locator('[data-ui=settings]').click();await page.locator('#motion').uncheck();await page.locator('[data-ui=close]').first().click();await page.waitForTimeout(150);const offA=await captureCanvas();await page.waitForTimeout(250);const offB=await captureCanvas();
const result={sourceBefore:before,errors,motion:{enabledFramesDiffer:!onA.equals(onB),disabledFramesIdentical:offA.equals(offB)},layouts:{}};
for(const[w,h]of[[1280,720],[390,844]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(200);await page.screenshot({path:`reviews/screenshots-v0.1/recheck-battle-${w}.png`,fullPage:true});result.layouts[w]={nav:await page.locator('nav').ariaSnapshot(),metrics:await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,canvas:{w:document.querySelector('#arena').clientWidth,h:document.querySelector('#arena').clientHeight},fonts:[...document.querySelectorAll('.unit-status,.card-description')].map(e=>({txt:e.textContent,font:getComputedStyle(e).fontSize,scrollHeight:e.scrollHeight,height:e.clientHeight}))}))};}
await page.locator('.ally.ready').focus();await page.keyboard.press('Enter');result.keyboardTarget={selected:await page.locator('.ally.selected').count(),focus:await page.evaluate(()=>document.activeElement.getAttribute('aria-label'))};await page.keyboard.press('Enter');result.keyboardAttack=await page.evaluate(()=>JSON.parse(localStorage.getItem('lanternbound.run.v1')).allies[0].acted);await page.locator('[data-ui=deck]').click();result.deckDialog={open:await page.locator('dialog').evaluate(e=>e.open),cardCount:await page.locator('dialog .game-card').count()};await page.keyboard.press('Escape');result.deckClosed=await page.locator('dialog').evaluate(e=>!e.open);result.sourceAfter=await hashes();result.sourceStable=JSON.stringify(result.sourceBefore)===JSON.stringify(result.sourceAfter);await fs.writeFile('reviews/screenshots-v0.1/recheck.json',JSON.stringify(result,null,2));console.log({motion:result.motion,sourceStable:result.sourceStable,keyboardTarget:result.keyboardTarget,keyboardAttack:result.keyboardAttack,layouts:result.layouts});}finally{await browser.close();}
