import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/');await page.waitForTimeout(400);
await page.screenshot({path:'reviews/screenshots-v0.1/title-1440.png'});
await page.locator('[data-ui=new]').click();await page.locator('#seed').fill('117');await page.getByRole('button',{name:'Light the lantern'}).click();
await page.screenshot({path:'reviews/screenshots-v0.1/tutorial-1440.png'});
await page.locator('[data-ui=learned]').click();await page.screenshot({path:'reviews/screenshots-v0.1/map-1440.png'});
await page.locator('[data-action=travel][data-choice=battle]').click();await page.waitForTimeout(250);await page.screenshot({path:'reviews/screenshots-v0.1/battle-1440.png'});
const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('lanternbound.run.v1')));
let summon=await page.locator('.game-card:not([disabled])').evaluateAll(elements=>elements.find(e=>e.textContent.includes('COMPANION'))?.getAttribute('data-index'));
if(summon!==undefined&&summon!==null){await page.locator(`[data-ui=play-card][data-index="${summon}"]`).click();}
await page.waitForTimeout(300);await page.screenshot({path:'reviews/screenshots-v0.1/battle-summon-1440.png'});
const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('lanternbound.run.v1')));
const ready=page.locator('.ally.ready').first(); if(await ready.count()){await ready.focus();await page.keyboard.press('Enter');await page.screenshot({path:'reviews/screenshots-v0.1/targeting-1440.png'});await page.keyboard.press('Enter');}
await page.locator('[data-ui=settings]').click();await page.locator('#motion').uncheck();await page.locator('[data-ui=close]').first().click();
await page.waitForTimeout(120);const a=await page.locator('#arena').screenshot();await page.waitForTimeout(250);const b=await page.locator('#arena').screenshot();
const focus=[];await page.locator('[data-action=endTurn]').focus();for(let i=0;i<6;i++){focus.push(await page.evaluate(()=>({tag:document.activeElement.tagName,txt:document.activeElement.textContent,outline:getComputedStyle(document.activeElement).outline})));await page.keyboard.press('Tab');}
const results={errors,seed:117,startingHand:before.hand,playedSummonIndex:summon,alliesAfterSummon:state.allies,ambientMotionOffFramesIdentical:a.equals(b),focus};
for(const [w,h] of [[1280,720],[390,844]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(130);await page.screenshot({path:`reviews/screenshots-v0.1/battle-${w}.png`,fullPage:true});results[`layout${w}`]=await page.evaluate(()=>({viewport:innerWidth,documentWidth:document.documentElement.scrollWidth,documentHeight:document.documentElement.scrollHeight,buttons:[...document.querySelectorAll('button')].map(e=>({txt:e.textContent,label:e.getAttribute('aria-label'),font:getComputedStyle(e).fontSize,bounds:{x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}})),fonts:[...document.querySelectorAll('.card-description,.unit-status,.unit strong,.battle-guidance')].map(e=>({txt:e.textContent,font:getComputedStyle(e).fontSize}))}));}
await page.setViewportSize({width:1280,height:720});await page.locator('[data-ui=settings]').click();await page.screenshot({path:'reviews/screenshots-v0.1/settings-1280.png'});
await page.keyboard.press('Tab');results.dialogFocus=await page.evaluate(()=>({tag:document.activeElement.tagName,id:document.activeElement.id,dialog:document.activeElement.closest('dialog')!==null}));await page.keyboard.press('Escape');results.dialogEscClosed=await page.locator('dialog').evaluate(e=>!e.open);
const fb=await browser.newContext({viewport:{width:1280,height:720}});await fb.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /^webgl/.test(type)?null:original.call(this,type,...args)}});const fp=await fb.newPage();await fp.goto('http://127.0.0.1:5173/');await fp.locator('[data-ui=new]').click();await fp.locator('#seed').fill('117');await fp.getByRole('button',{name:'Light the lantern'}).click();await fp.locator('[data-ui=learned]').click();await fp.locator('[data-action=travel][data-choice=battle]').click();await fp.screenshot({path:'reviews/screenshots-v0.1/battle-gpu-fallback-1280.png'});results.gpuFallback={canvasHidden:await fp.locator('#arena').evaluate(e=>e.hidden),text:await fp.locator('.arena-fallback').innerText(),hand:await fp.locator('.game-card').count(),roster:await fp.locator('.enemy').count()};await fp.keyboard.press('e');results.gpuFallback.turnAfterKeyboardEnd=await fp.evaluate(()=>JSON.parse(localStorage.getItem('lanternbound.run.v1')).turn);
await fs.writeFile('reviews/screenshots-v0.1/ui-inspection.json',JSON.stringify(results,null,2));console.log({errors,motion:results.ambientMotionOffFramesIdentical,keyboardSummon:summon,dialog:results.dialogFocus,narrowWidth:results.layout390.documentWidth,gpuFallback:results.gpuFallback});await browser.close();
