import json,hashlib,resource
from pathlib import Path
P=Path(__file__).parent
def sha(q):return hashlib.sha256(q.read_bytes()).hexdigest()
a=json.loads((P/'AUDIT.json').read_bytes());r=json.loads((P/'review-guard/RESULT.json').read_bytes());assert r['exit_code']==0 and r['failure'] is None and r['memory_events_before']==r['memory_events_after']
gate={'decision':a['decision'],'accepted':True,'actualComparisonEngineeringEligible':True,'stage':a['stage'],'sourceDigest':a['sourceDigest'],'outputsDigest':a['outputsDigest'],'inputCount':104,'outputCount':70,'freezeSHA256':a['freezeSHA256'],'aliasCatalogueSHA256':a['aliasCatalogueSHA256'],'actualAliasCount':121,'all174ActualMappedBodiesSHA256Verified':True,'all162DonorMappedBodiesUnchangedSHA256Verified':True,'support30BodiesBothStageAndDonorVerified':True,'source104To98AndHeld65To59FullInversesVerified':True,'heldOutputCount':65,'originalHeldRowsUnchanged':58,'measuredBuiltCodeBodies':5,'strict13ChecksNormal':True,'wholeSeconds':a['wholeSeconds'],'outerSamples':5,'innerSamples':11,'outerMaxDeltaBytes':a['maxDeltaBytes'],'outerMinHeadroomBytes':a['outerMinHeadroomBytes'],'RootActivationSHA256':a['activationSHA256'],'controlsSourceGateSHA256':a['sourceGateSHA256'],'canonicalHoldVerified':a['canonicalHoldVerified'],'nativeAdmissionAndScope':a['native13Admission'],'resourceQualification':a['resourceQualification'],'installedDependencyQualification':'Actual installed TSC/Vite metadata and module chain pinned; whole noEmit evidence includes support30. No full dependency tree Merkle or browser/test execution claim.','actualBrowserDecodeSceneArtDefaultAnimationFunApproved':False,'newBrowserRunRequiresSeparateReviewedCallerAndRootFreshGrant':True,'AUDIT_SHA256':sha(P/'AUDIT.json'),'normalReviewGuardSHA256':sha(P/'review-guard/RESULT.json'),'priorRoles':a['priorRoles'],'canonicalOrHeldMutation':False}
(P/'GATE.json').open('x').write(json.dumps(gate,separators=(',',':'))+'\n')
(P/'REVIEW.md').open('x').write('Accepted exact ACTUAL104/70 starter strict build for a separately reviewed restricted private comparison. Independently full-hashed all174 stage mapped bodies and162 donor mapped bodies; complete tree memberships, source/output digests, full104→98 source and65→59 held maps verified.65 held rows preserve58 originals plus replacementview/six nativePNGs; five actual code outputs measured. Both support30 sets unchanged. All121 actual current leaf chains and115 donor chains verified against exact catalogues; new PNG inputs regular private inodes, outputaliases point to their own public copies, manifest regular copy. No PNG decode.\n\nExact Root activation binds controls Source gate d13/Plan753be; assembly and freeze64 guards normal0. Actual installed full TSC --noEmit and Vite built successfully under strict384+512/heap256/disk64 stop55/whole60, all13 checks normal, outer1.3813678789883852s/five samples/max225497088/min1175814144; inner11 samples and events unchanged, observed tracked processes closed. Installed TSC/Vite metadata/module chain and tsconfig src/tests/scripts/config includes verified; support30 supplied. No full dependency Merkle/test execution/continuous peak/universal escape claim. Canonical89 source bodies match64c2 map; held56 dist bodies match existing8bba map, no canonical writes.\n\nAll13 image byte identities/manifest/descriptor/loader contract intact; readiness and admission have not been exercised in browser. Native layout still rejects above two allies/enemies despite engine summon cap6; existing phase latch/fallback retained. Private firstCairn+Ash≤2/hand portraits only; thirdbinding continuity remains separate. Original enemy/Cairn/floor/corpse/rules/save/input/cueOFF authority unchanged; current canonical cue composition pending. Need separate reviewed caller, fresh native grant and actual fit/quality reviews. No art/default/animation/first300/fun approval.\n\nOlder utility/witness/helper and Source/control review roles disclosed; Cairn authors adaptation. This checks saved actual build data and operational receipts independently; no build/Node/browser/Pillow/runtime rerun, media decode, canonical or held mutation. Point-sampled resource final check occurs after cleanup before outer RESULT write; all receipts/guards subsequently normal, no all-last-write continuous resource claim.\n')
files={str(q.relative_to(P)):{'bytes':q.stat().st_size,'sha256':sha(q)} for q in P.rglob('*') if q.is_file()}
(P/'MANIFEST.json').open('x').write(json.dumps({'files':files,'logicalCapBytes':131072,'allocatedCapClaimed':False,'guardTailReserveBytes':8192,'sourceWorkMiB':64,'reserveMiB':512,'diskAdmissionMiB':64,'ownRSSKiBLimit':24576,'finalSealGuard':'Separate ADMISSION/RESULT/EXECUTION follows; exact normal closure returned.'},separators=(',',':'))+'\n')
n=sum(q.stat().st_size for q in P.rglob('*') if q.is_file());assert n+8192<=131072 and resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
print(json.dumps({'gateSHA256':sha(P/'GATE.json'),'manifestSHA256':sha(P/'MANIFEST.json'),'reviewSHA256':sha(P/'REVIEW.md'),'auditSHA256':sha(P/'AUDIT.json'),'logicalBeforeFinalGuardTails':n,'tailReserveBytes':8192,'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss}))
