import ast,gzip,hashlib,io,json,pathlib,resource,tarfile
P=pathlib.Path(__file__).parent
def sha(b):return hashlib.sha256(b).hexdigest()
def read(n):return (P/n).read_bytes()
plan=json.loads(read('PLAN.json'));assert plan['exact40Controls']['count']==40 and len(plan['actualComparisons'])==2 and all(a['originalJPEGCount']==8 and len(a['sixCompleteRawPairs'])==6 for a in plan['actualComparisons']);assert plan['proposedArchive']['workMiB']==128 and plan['proposedArchive']['reserveMiB']==512 and plan['proposedArchive']['physicalOutputCapBytes']==16*1048576
for p in P.glob('*.py'):ast.parse(p.read_text())
history=json.loads(read('AUTHOR-REFINEMENT-HISTORY.json'));source=read('author-plan.py').decode();preCap=source.replace('size+8192<=192*1024','size+8192<=128*1024');assert sha(preCap.encode())=='e5919785502b97342532f7b6bbe0e0b75eae275a817fac8a5ebf893e8f7ef6ae';original=preCap.replace(history['inverseLiteral'],history['forwardLiteral']);assert sha(original.encode())==history['originalAuthorSHA256']
payloads=[b'original raw state with  spaces and literal \\n\n',json.dumps({'unicode':'猫é','raw':'{ "escaped": "\\n", "space": "  " }'},ensure_ascii=False).encode(),bytes(range(256))*5];unique={sha(b):b for b in payloads};memory=io.BytesIO()
with gzip.GzipFile(fileobj=memory,mode='wb',filename='',mtime=0) as compressed:
 with tarfile.open(fileobj=compressed,mode='w|',bufsize=65536) as archive:
  for h,b in sorted(unique.items()):t=tarfile.TarInfo('blobs/'+h);t.size=len(b);t.mtime=0;archive.addfile(t,io.BytesIO(b))
memory.seek(0);seen=set()
with tarfile.open(fileobj=memory,mode='r|gz',bufsize=65536) as archive:
 for t in archive:b=archive.extractfile(t).read();h=t.name[6:];assert b==unique[h] and len(b)==t.size and sha(b)==h;seen.add(h)
assert seen==set(unique);assert json.loads(payloads[1])['raw']=='{ "escaped": "\\n", "space": "  " }'
guards={n:json.loads(read(n+'/RESULT.json')) for n in ['GUARD-PLAN-R1','GUARD-PLAN-R2','GUARD-PLAN-R3']};assert [guards[n]['exit_code'] for n in guards]==[1,1,0]
protocol=('SOURCE ONLY. This plan preserves immutable default+prior opt-in cue actuals,16 originalJPEGs/sixpairedraws each/all actual reviews including failed originals/current default source/build/freeze/caller/control identities and selectedc4 rollback. It does not select/publish runtime or art; clarity successor remains separate. Exact ce0f canonical archive/index supplies already-preserved SHA blobs; no duplicate archive. PNG/WAV bodies/node_modules excluded with exact external maps/dependencies.\nRoot future archive argv: python '+str(P/'preserve-checkpoint.py')+' '+str(P/'PLAN.json')+' '+sha(read('PLAN.json'))+' NEW_FRESH_OUTPUT_DIRECTORY\nProposal only:128+512MiB work/reserve,own24MiB,16MiB complete logical+allocated output cap,17MiB freshfree,60s method ceiling. Root grant and independent source review required. Helper streams TAR/gzip full exact originals, checks SHA/length and compares decoded bytes directly against originals; finite physical/logical output observations occur after all writes. Root guard/cgroup/time accounting and actual independent preservation review still required; no actual archive claim.\nOriginal source128KiB prewrite refusals retained; Root approved proportional192KiB source family. All source/guard/history/closure bytes count; no deleting drafts. No Node/browser/game/build/Git/archive-body extraction/imagebackend execution in source phases. Source memory-only gzip estimate and capsule INDEX metadata streaming may update atime; no universal atime-preservation claim. Actual helper requestsO_NOATIME,EPERMfallback recorded. Originals never overwritten/deleted.\n').encode()
rows=[{'path':str(p.relative_to(P)),'bytes':p.stat().st_size,'sha256':sha(p.read_bytes())} for p in sorted(P.rglob('*')) if p.is_file()]
pins={'PLAN.json':sha(read('PLAN.json')),'preserve-checkpoint.py':sha(read('preserve-checkpoint.py'))};manifest={'sealed':True,'scope':'Source preservation plan only; independent review/Root actual admission still required','bodies':[{'name':n,'bytes':len(read(n)),'sha256':h} for n,h in pins.items()],'existingCanonicalArchiveSHA256':plan['existingCapsule']['archive']['sha256'],'sourceFamilyCapKiB':192,'original128KiBRefusalsRetained':True,'noPublicationRuntimeSelectionOrActualGrant':True}
closure={'status':'SOURCE_FINITE_CLOSED_NOT_ARCHIVE_EXECUTED','planSHA256':pins['PLAN.json'],'helperSHA256':pins['preserve-checkpoint.py'],'logicalBodyRows':len(plan['rows']),'newUniqueBodyCount':plan['proposedArchive']['newUniqueBodyCount'],'estimatedPerBodyGzipBytes':plan['proposedArchive']['perBodyGzipSumEstimateBytes'],'actualArchiveOutputCapBytes':16*1048576,'allOriginal128RefusalsAndSourceReconstructionHistoryPreserved':True,'syntheticBinaryUnicodeRawJSONTarGzipFullByteRoundtrip':True,'actualOriginalBodySHAStreamingGzipReadbackEstimateVerifiedInPlanPhase':True,'allOriginalMediaBodyAndNodeModulesExcludedExcept16OriginalActualJPEGs':True,'sourceFootprintIncludesEveryFailedSourceGuardSealAndHistory':True,'guardResults':guards,'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'finiteRows':rows}
out={'PROTOCOL.txt':protocol,'MANIFEST.json':(json.dumps(manifest,separators=(',',':'))+'\n').encode(),'CLOSURE.json':(json.dumps(closure,separators=(',',':'))+'\n').encode(),'SHA256SUMS':''.join(r['sha256']+'  '+r['path']+'\n' for r in rows).encode()};size=sum(r['bytes'] for r in rows)+sum(map(len,out.values()));assert size+8192<=192*1024,(size,'Stop BEFORE closure; reserve8KiB');assert resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
for n,b in out.items():assert not (P/n).exists();(P/n).write_bytes(b)
print(json.dumps({'sourceOnly':True,'logicalBeforeFinalGuardReceipt':size,'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'activePins':pins,'manifestSHA256':sha(out['MANIFEST.json']),'closureSHA256':sha(out['CLOSURE.json']),'sumsSHA256':sha(out['SHA256SUMS']),'TOOLS_CLOSED_ON_RETURN':True}))
