// Unshipped adapter + borrowed UI host callbacks; all saves are synthetic fixtures.
import {chromium} from '/workspace/Roguelike-deckbuilder/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync} from 'node:fs';

import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const scratch='/workspace/scratch/controller-v06-production-input/';
const root='/workspace/Roguelike-deckbuilder/';
const fixtures=JSON.parse(readFileSync(scratch+'probe-fixtures.json','utf8'));
const source=readFileSync(scratch+'emitted/adapter.js','utf8');
const expected='d6221bf764bad593b04981e87bead7ba6868b72cf361d70671af5c91aac39416';
const hash=path=>createHash('sha256').update(readFileSync(root+path)).digest('hex');
const runtimeFiles=['src/main.ts','src/style.css','index.html','src/engine.ts','src/arena.ts'];
const before=Object.fromEntries(runtimeFiles.map(path=>[path,hash(path)]));
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
const report={syntheticBrowserQA:true,adapterShipped:false,hostContextBorrowed:true,physicalController:false,checks:[],errors:[],beforeRuntimeHashes:before};
async function load(fixture=fixtures.full){const page=await browser.newPage({viewport:{width:1280,height:720}});page.on('pageerror',e=>report.errors.push(e.message));await page.addInitScript(s=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(s));localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion:false,mute:true,volume:0}));localStorage.setItem('hollowpact.tutorial.v2','true');},fixture);await page.goto('http://127.0.0.1:4173');const build=await page.evaluate(async()=>await(await fetch('./build-provenance.json')).json());assert.equal(build.sourceDigest,expected);report.build={version:build.version,digest:build.sourceDigest};await page.locator('[data-ui="resume"]').click();await page.evaluate(async source=>{
const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));const module=await import(url);URL.revokeObjectURL(url);
window.__pad={index:0,connected:true,mapping:'standard',axes:[0,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>{if(window.__padThrows)throw new DOMException('Synthetic API refusal','SecurityError');return [window.__pad];}});
window.__hostLock=false;window.__hostThrows=false;window.__activations=0;window.__modes=[];
const host={getContext(){if(window.__hostThrows)throw Error('Synthetic host refusal');return {phase:document.querySelector('#app').classList.contains('on-title')?'title':JSON.parse(localStorage.getItem('hollowpact.run.v2')).phase,settling:window.__hostLock,dialog:document.querySelector('#dialog').open?document.querySelector('#dialog'):null,targeting:!!document.querySelector('.battle-guidance.targeting')};},activate(element){window.__activations++;element.click();},back(){const close=document.querySelector('#dialog[open] [data-ui="close"]');const cancel=document.querySelector('[data-ui="cancel"]');if(close)close.click();else if(cancel)cancel.click();else document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));},inspect(element){if(element.dataset.unit)document.querySelector(`[data-ui="inspect-unit"][data-uid="${CSS.escape(element.dataset.unit)}"]`)?.click();else if(element.dataset.card){document.querySelector('[data-ui="deck"]').click();document.querySelector(`#dialog [data-ui="inspect"][data-card="${CSS.escape(element.dataset.card)}"]`)?.click();}},endTurn(){document.querySelector('[data-action="endTurn"]:not(:disabled)')?.click();},pause(){document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));},onInputMode(mode){window.__modes.push(mode);}};
window.__input=module.createInputAdapter(host,{autoPoll:false});window.__input.pollOnce(0);
},source);return page;}
async function step(page,now,{button,pressed,axes}={}){await page.evaluate(({now,button,pressed,axes})=>{if(button!==undefined)window.__pad.buttons[button]={pressed:!!pressed,value:pressed?1:0};if(axes)window.__pad.axes=axes;window.__input.pollOnce(now);},{now,button,pressed,axes});}
async function snap(page){return page.evaluate(()=>({save:localStorage.getItem('hollowpact.run.v2'),unit:document.activeElement.dataset.unit||null,card:document.activeElement.dataset.focus||null,tag:document.activeElement.tagName,selected:document.querySelectorAll('.unit.selected').length,dialog:document.querySelector('#dialog').open,activations:window.__activations}));}
try{
 let page=await load();const baseline=await snap(page);await page.keyboard.press('h');const hand=await snap(page);await page.keyboard.press('ArrowRight');const nextCard=await snap(page);await page.keyboard.press('b');const binding=await snap(page);await page.keyboard.press('ArrowRight');const enemy=await snap(page);assert.equal(hand.card,'card-0');assert.equal(nextCard.card,'card-1');assert.equal(binding.unit,fixtures.full.allies[0].uid);assert.equal(enemy.unit,fixtures.full.enemies[0].uid);assert.equal(enemy.save,baseline.save);const modified=await page.evaluate(()=>{const event=new KeyboardEvent('keydown',{key:'h',ctrlKey:true,bubbles:true,cancelable:true});document.activeElement.dispatchEvent(event);return {prevented:event.defaultPrevented,unit:document.activeElement.dataset.unit};});assert.equal(modified.prevented,false);assert.equal(modified.unit,enemy.unit);report.checks.push({name:'regional-and-spatial-keyboard',hand:hand.card,nextCard:nextCard.card,binding:binding.unit,hostile:enemy.unit,canonicalUnchanged:true,modifiedShortcutIgnored:true});await page.close();
 page=await load();await page.keyboard.press('b');const original=await snap(page);await step(page,20,{button:0,pressed:true});const selected=await snap(page);for(const now of [40,400,1000])await step(page,now);const held=await snap(page);assert.equal(selected.unit,fixtures.full.enemies[0].uid);assert.equal(held.save,original.save);assert.equal(held.activations,1);await step(page,1020,{button:0,pressed:false});await step(page,1040,{button:0,pressed:true});const committed=await snap(page);assert.deepEqual(JSON.parse(committed.save),fixtures.expectedCommand);assert.equal(committed.activations,2);await step(page,2000);assert.equal((await snap(page)).save,committed.save);report.checks.push({name:'legacy-canonical-command-button-edges',oneSelectionWhileHeld:true,oneFreshCommit:true,canonicalEqualsReducer:true});await page.close();
 page=await load(fixtures.kind2);await page.keyboard.press('h');const beforeSummon=await snap(page);await step(page,20,{button:0,pressed:true});await step(page,500);const summoned=await snap(page);assert.deepEqual(JSON.parse(summoned.save),fixtures.expectedSummon);assert.equal(summoned.activations,1);assert.notEqual(summoned.save,beforeSummon.save);report.checks.push({name:'kind2-canonical-immediate-summon',canonicalEqualsReducer:true,noSecondCardWhileHeld:true});await page.close();
 page=await load();await page.keyboard.press('b');const beforeInspect=await snap(page);await step(page,20,{button:2,pressed:true});assert.equal((await snap(page)).dialog,true);await step(page,40,{button:2,pressed:false});for(let i=0;i<3;i++){await step(page,80+i*40,{button:13,pressed:true});assert.equal(await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)),true);await step(page,100+i*40,{button:13,pressed:false});}await step(page,240,{button:1,pressed:true});assert.equal((await snap(page)).dialog,false);assert.equal((await snap(page)).save,beforeInspect.save);report.checks.push({name:'inspect-and-dialog-scope',dialogNavigationInside:true,backThroughHost:true,canonicalUnchanged:true});await page.close();
 page=await load();const beforeEnd=await snap(page);await step(page,20,{button:3,pressed:true});const confirmation=await snap(page);assert.equal(confirmation.dialog,true);assert.equal(confirmation.save,beforeEnd.save);assert.equal(await page.locator('#dialog-title').innerText(),'Unspent commands remain');await step(page,1000);assert.equal((await snap(page)).save,beforeEnd.save);report.checks.push({name:'endTurn-host-confirmation',confirmationPreserved:true,heldYDoesNotConfirm:true});await page.close();
 page=await load();await page.locator('[data-ui="settings"]').click();await page.locator('#volume').focus();const startVolume=Number(await page.locator('#volume').inputValue());await page.keyboard.press('ArrowRight');const keyboardVolume=Number(await page.locator('#volume').inputValue());assert.equal(keyboardVolume,startVolume+1);await step(page,20,{axes:[.8,0,0,0]});const controllerVolume=Number(await page.locator('#volume').inputValue());assert.equal(controllerVolume,keyboardVolume+10);await page.keyboard.press('Escape');await page.locator('[data-ui="home"]').click();await page.locator('[data-ui="new"]').click();await page.locator('#seed').fill('');await page.locator('#seed').pressSequentially('hbti');assert.equal(await page.locator('#seed').inputValue(),'hbti');report.checks.push({name:'native-widgets-and-text',keyboardRangeNativeStep:true,controllerRangeUsesExistingInput:true,regionalLettersDoNotOverrideText:true});await page.close();
 page=await load();await page.keyboard.press('b');const beforeLock=await snap(page);await page.evaluate(()=>window.__hostLock=true);await step(page,10);await step(page,20,{button:0,pressed:true});assert.equal((await snap(page)).selected,0);await step(page,40,{button:0,pressed:false});await step(page,60,{button:9,pressed:true});assert.equal((await snap(page)).dialog,true);assert.equal((await snap(page)).save,beforeLock.save);report.checks.push({name:'host-boolean-presentation-lock',confirmBlocked:true,safePauseStillAvailable:true,canonicalUnchanged:true,hostLockSimulated:true});await page.close();
 page=await load();await page.keyboard.press('b');const beforeFailure=await snap(page);await page.evaluate(()=>window.__padThrows=true);await step(page,20,{button:0,pressed:true});assert.equal((await snap(page)).save,beforeFailure.save);await page.keyboard.press('h');assert.equal((await snap(page)).card,'card-0');await page.evaluate(()=>window.__input.dispose());await page.locator('.ally').first().focus();await page.keyboard.press('ArrowRight');assert.equal((await snap(page)).unit,fixtures.full.allies[0].uid);await page.evaluate(()=>window.__padThrows=false);await step(page,60,{button:0,pressed:false});await step(page,80,{button:0,pressed:true});assert.equal((await snap(page)).save,beforeFailure.save);report.checks.push({name:'API-security-refusal-and-dispose',keyboardSurvivesAPIError:true,noAdapterKeysOrPadAfterDispose:true});await page.close();
 report.afterRuntimeHashes=Object.fromEntries(runtimeFiles.map(path=>[path,hash(path)]));report.runtimeUnchanged=JSON.stringify(before)===JSON.stringify(report.afterRuntimeHashes);assert.equal(report.runtimeUnchanged,true);assert.deepEqual(report.errors,[]);report.passed=report.checks.length;writeFileSync(scratch+`browser-evidence-${Date.now()}.json`,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
