import {chromium} from '/workspace/Roguelike-deckbuilder/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const root='/workspace/scratch/controller-v06-production-input/';const fixtures=JSON.parse(readFileSync(root+'probe-fixtures.json','utf8'));const source=readFileSync(root+'emitted/adapter.js','utf8');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
const evidence={syntheticPad:true,physicalHardware:false,realChromiumVisibility:false,visibilityTestMode:null,errors:[],contentEditableHarnessRepair:'The second attempt assigned an invalid empty IDL property; use the valid empty contenteditable HTML attribute.',priorAttempt:{result:'failed harness assertion',reason:'First attempt assumed bringToFront hides other headless tabs; they remained visible and a foreground A press correctly activated.'}};
try{const page=await browser.newPage();page.on('pageerror',e=>evidence.errors.push(e.message));await page.addInitScript(s=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(s));localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion:false,mute:true,volume:0}));localStorage.setItem('hollowpact.tutorial.v2','true');},fixtures.full);await page.goto('http://127.0.0.1:4173');const build=await page.evaluate(async()=>await(await fetch('./build-provenance.json')).json());assert.equal(build.sourceDigest,'d6221bf764bad593b04981e87bead7ba6868b72cf361d70671af5c91aac39416');evidence.build={version:build.version,digest:build.sourceDigest};await page.locator('[data-ui="resume"]').click();
await page.evaluate(async source=>{const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));const module=await import(url);URL.revokeObjectURL(url);window.__pad={index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[window.__pad]});window.__reads=0;window.__activations=0;window.__host={getContext:()=>({phase:'battle',settling:false,dialog:document.querySelector('#dialog').open?document.querySelector('#dialog'):null,targeting:!!document.querySelector('.battle-guidance.targeting')}),activate:el=>{window.__activations++;el.click();},back(){},inspect(){},endTurn(){},pause(){}};window.__factory=module.createInputAdapter;window.__adapter=module.createInputAdapter(window.__host,{readPads:()=>{window.__reads++;return navigator.getGamepads();}});},source);
await page.locator('.ally').first().focus();await page.waitForTimeout(100);const initial=await page.evaluate(()=>({reads:window.__reads,hidden:document.hidden,save:localStorage.getItem('hollowpact.run.v2')}));assert.ok(initial.reads>0);evidence.foregroundPollingWithMotionOff=initial.reads;
const other=await browser.newPage();await other.goto('about:blank');await other.bringToFront();await page.waitForTimeout(100);const hidden=await page.evaluate(()=>({hidden:document.hidden,reads:window.__reads}));evidence.realChromiumVisibility=hidden.hidden;evidence.visibilityTestMode=hidden.hidden?'native tab visibility':'explicit Document.hidden emulation';
if(!hidden.hidden){await page.evaluate(()=>{window.__reviewHidden=true;Object.defineProperty(document,'hidden',{configurable:true,get:()=>window.__reviewHidden});document.dispatchEvent(new Event('visibilitychange'));});hidden.reads=await page.evaluate(()=>window.__reads);}
await page.evaluate(()=>{window.__pad.buttons[0]={pressed:true,value:1};});await page.waitForTimeout(100);const hiddenLater=await page.evaluate(()=>({reads:window.__reads,activations:window.__activations}));
assert.equal(hiddenLater.reads,hidden.reads);assert.equal(hiddenLater.activations,0);await page.bringToFront();if(!hidden.hidden)await page.evaluate(()=>{window.__reviewHidden=false;document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(100);const resumed=await page.evaluate(()=>({reads:window.__reads,activations:window.__activations}));assert.equal(resumed.activations,0);evidence.heldInputIgnoredOnResume=true;evidence.pollsStoppedInHidden=hiddenLater.reads===hidden.reads;
await page.evaluate(()=>window.__pad.buttons[0]={pressed:false,value:0});await page.waitForTimeout(50);await page.evaluate(()=>window.__pad.buttons[0]={pressed:true,value:1});await page.waitForTimeout(50);const selected=await page.evaluate(()=>({activations:window.__activations,save:localStorage.getItem('hollowpact.run.v2')}));assert.equal(selected.activations,1);assert.equal(selected.save,initial.save);evidence.freshPressSelectsOnce=true;
await page.evaluate(()=>window.__adapter.dispose());const disposedReads=await page.evaluate(()=>window.__reads);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.__reads),disposedReads);evidence.disposeStopsScheduledPolling=true;
await page.evaluate(()=>{window.__pad.connected=false;window.__adapter=window.__factory(window.__host,{readPads:()=>{window.__reads++;throw new DOMException('Synthetic security refusal','SecurityError');}});});await page.waitForTimeout(100);const refusedReads=await page.evaluate(()=>window.__reads);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.__reads),refusedReads);evidence.APIRefusalUsesSlowRetry=true;await page.evaluate(()=>window.__adapter.dispose());
// Contenteditable without a literal true attribute must retain typed regional letters.
await page.evaluate(()=>{window.__adapter=window.__factory(window.__host,{autoPoll:false});const editor=document.createElement('div');editor.setAttribute('contenteditable','');editor.id='review-editor';editor.style.cssText='position:fixed;top:10px;left:10px;background:white;color:black';document.body.append(editor);editor.focus();});await page.locator('#review-editor').pressSequentially('hbti');assert.equal(await page.locator('#review-editor').innerText(),'hbti');evidence.contentEditableNativeTypingPreserved=true;await page.evaluate(()=>window.__adapter.dispose());
assert.deepEqual(evidence.errors,[]);writeFileSync(root+`lifecycle-evidence-${Date.now()}.json`,JSON.stringify(evidence,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(evidence,null,2));await other.close();
}finally{await browser.close();}
