from pathlib import Path
import subprocess,json,zipfile,hashlib
out=Path('reviews/release-pipeline-v0.6.1-evidence');repo=Path('/workspace/scratch/release-audit-v061-scope');repo.mkdir()
def git(args):return subprocess.check_output(['git','-C',str(repo),*args])
git(['init','-q']);git(['config','user.name','Independent release audit']);git(['config','user.email','audit@example.invalid'])
entries={'src/engine.ts':b'canonical rules\n','reviews/negative.json':b'{"rating":"rejected"}\n','assets/original.bin':bytes([0,255,12]),'releases/0.1.0/manifest.json':b'original immutable milestone\n','space name':b'spaced tracked root\n','extra\nroot/\u4fdd\u7ba1.dat':b'newline and unicode tracked root\n','--leading':b'leading dash root\n'}
for f,b in entries.items():p=repo/f;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
git(['add','--all']);git(['commit','-qm','Scratch archive scope fixture']);commit=git(['rev-parse','HEAD']).decode().strip();(repo/'untracked-evidence.txt').write_text('not in source commit\n')
quoted=git(['ls-tree','--name-only',commit]).decode().strip().split('\n');oldRoots=[r for r in quoted if r and r!='releases'];oldArchive=repo/'original-newline-policy.zip';proc=subprocess.run(['git','-C',str(repo),'archive','--format=zip',f'--output={oldArchive}',commit,'--',*oldRoots],capture_output=True,text=True)
roots=[r for r in git(['ls-tree','-z','--name-only',commit]).decode().split('\0') if r and r!='releases'];archive=repo/'nul-policy.zip';git(['archive','--format=zip',f'--output={archive}',commit,'--',*roots]);expected={f:b for f,b in entries.items() if not f.startswith('releases/')}
with zipfile.ZipFile(archive) as z:
 files={i.filename:z.read(i.filename) for i in z.infolist() if not i.is_dir()};assert files==expected;assert z.testzip() is None
tracked=git(['ls-files','-z']).decode().split('\0');assert (repo/'releases/0.1.0/manifest.json').read_bytes()==entries['releases/0.1.0/manifest.json'];assert proc.returncode!=0
realCommit=subprocess.check_output(['git','rev-parse','HEAD']).decode().strip();realRoots=subprocess.check_output(['git','ls-tree','-z','--name-only',realCommit]).decode().split('\0');realRoots=[r for r in realRoots if r and r!='releases'];realTracked=[f for f in subprocess.check_output(['git','ls-tree','-rz','--name-only',realCommit]).decode().split('\0') if f];included=[f for f in realTracked if f.split('/')[0] in realRoots];excluded=[f for f in realTracked if f.startswith('releases/')];assert len(included)+len(excluded)==len(realTracked)
result={'scope':'Independent scratch Git source-scope experiment; current-repository commit/tree oracle, no production archive written','fixtureCommit':commit,'newlineEnumerationReturnCode':proc.returncode,'newlineEnumerationError':proc.stderr.strip(),'nulEnumerationEntries':roots,'allIncludedFilesByteExact':list(files),'originalMilestoneUnchanged':True,'untrackedEvidenceOmitted':True,'realSourceCommit':realCommit,'realTopLevelScope':realRoots,'realTrackedCount':len(realTracked),'realIncludedCount':len(included),'realExcludedReleasesCount':len(excluded),'canonicalReviewsPresent':any(f.startswith('reviews/') for f in included),'canonicalOriginalArtPresent':any(f.startswith('assets/') for f in included),'runtimeSourcesPresent':all(f in included for f in ['src/engine.ts','src/input.ts','src/arena.ts','src/main.ts','scripts/build.mjs','scripts/release.mjs','package.json'])}
(out/'scope.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
