// Synthetic browser QA against a frozen production build, never hardware certification.
import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const base = process.env.HOLLOWPACT_REVIEW_URL || 'http://127.0.0.1:4173';
const expectedDigest = process.env.HOLLOWPACT_EXPECTED_DIGEST || '9f80af0d0053b992c7f0f39d6de106a8f318619ea92e94c00354933e07ebcf04';
const root = new URL('../../', import.meta.url);
const output = new URL(process.env.HOLLOWPACT_EVIDENCE_NAME || './keyboard-evidence.json', import.meta.url);
const full = JSON.parse(readFileSync(new URL('reviews/screenshots-v0.2/full-fixture.json',root),'utf8'));
const hash = path=>createHash('sha256').update(readFileSync(new URL(path,root))).digest('hex');
const beforeHashes = Object.fromEntries(['src/main.ts','src/style.css','index.html','desktop/main.cjs'].map(p=>[p,hash(p)]));
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
const results={syntheticBrowserQA:true,physicalControllerTested:false,expectedDigest,beforeHashes,checks:[],errors:[]};
async function focus(page){return page.evaluate(()=>{const e=document.activeElement;return {tag:e.tagName,ui:e.dataset.ui||null,unit:e.dataset.unit||null,focus:e.dataset.focus||null,aria:e.getAttribute('aria-label'),text:(e.textContent||'').trim().slice(0,90)};});}
async function load(fixture,motion=false){const page=await browser.newPage({viewport:{width:1280,height:720}});page.on('pageerror',e=>results.errors.push(e.message));await page.addInitScript(({fixture,motion})=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(fixture));localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion,mute:true,volume:0}));localStorage.setItem('hollowpact.tutorial.v2','true');},{fixture,motion});await page.goto(base);await page.locator('[data-ui="resume"]').focus();await page.keyboard.press('Enter');return page;}
async function save(page){return page.evaluate(()=>localStorage.getItem('hollowpact.run.v2'));}
try{
 const probe=await browser.newPage();await probe.goto(base);const provenance=await probe.evaluate(async()=>await(await fetch('./build-provenance.json')).json());if(provenance.sourceDigest!==expectedDigest)throw Error(`Unexpected build ${provenance.sourceDigest}`);results.actualDigest=provenance.sourceDigest;results.version=provenance.version;await probe.close();
 let page=await load(full);const traversal=[];for(let i=1;i<=50;i++){await page.keyboard.press('Tab');const item=await focus(page);traversal.push({tab:i,...item});if(item.ui==='play-card')break;}results.checks.push({name:'tab-to-first-hand-card-full-roster',traversal,firstHandTab:traversal.at(-1).ui==='play-card'?traversal.length:null});await page.close();
 page=await load(full);await page.locator('.ally').first().focus();const original=await focus(page);await page.keyboard.press('ArrowRight');results.checks.push({name:'arrow-key-button-navigation',before:original,after:await focus(page)});await page.keyboard.press('Enter');const selectedFocus=await focus(page);const preview=await page.locator('#consequence-preview').innerText();await page.keyboard.press('Escape');results.checks.push({name:'keyboard-selection-and-cancel',source:original,selectedFocus,preview,cancelFocus:await focus(page),selectedCount:await page.locator('.unit.selected').count()});await page.close();
 page=await load(full);await page.locator('[data-ui="settings"]').focus();await page.keyboard.press('Enter');const opened=await focus(page);const trap=[];for(let i=0;i<8;i++){await page.keyboard.press('Tab');trap.push({inside:await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)),focus:await focus(page)});}await page.locator('[data-ui=home]').evaluate(e=>e.focus());const attemptedUnderlyingFocus=await focus(page);await page.keyboard.press('Escape');results.checks.push({name:'native-dialog-trap-and-restore',opened,tabSequence:trap,underlyingControlFocused:attemptedUnderlyingFocus.ui==='home',restored:await focus(page)});await page.close();
 const nonterminal=structuredClone(full);nonterminal.enemies[0].hp=1;nonterminal.enemies[0].block=0;page=await load(nonterminal);await page.locator('.ally').first().focus();await page.keyboard.press('Enter');const preAttack=await focus(page);await page.keyboard.press('Enter');const stored=JSON.parse(await save(page));results.checks.push({name:'focus-after-nonterminal-enemy-death',target:preAttack,after:await focus(page),phase:stored.phase,enemyCount:stored.enemies.length});await page.close();
 for(const motion of [false,true]){const terminal=structuredClone(nonterminal);terminal.enemies=terminal.enemies.slice(0,1);page=await load(terminal,motion);await page.locator('.ally').first().focus();await page.keyboard.press('Enter');await page.keyboard.press('Enter');const immediate=await focus(page);await page.locator('[data-action="reward"]').first().waitFor();results.checks.push({name:'focus-after-terminal-command',motion,immediate,afterReward:await focus(page),phase:JSON.parse(await save(page)).phase});await page.close();}
 page=await load(full);await page.locator('.ally').first().focus();const beforeRepeat=await save(page);await page.keyboard.down('Enter');const firstPress=await focus(page);await page.keyboard.down('Enter');await page.keyboard.up('Enter');results.checks.push({name:'held-enter-selection-then-command',firstPress,saveChangedAfterRepeat:(await save(page))!==beforeRepeat,after:await focus(page)});await page.close();
 page=await load(full);const padBefore=await save(page);const padFocus=await focus(page);await page.evaluate(()=>{const buttons=Array.from({length:17},()=>({pressed:false,touched:false,value:0}));window.__virtualPad={id:'SYNTHETIC QA STANDARD PAD',index:0,mapping:'standard',connected:true,timestamp:performance.now(),axes:[0,0,0,0],buttons,vibrationActuator:null};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[window.__virtualPad]});window.dispatchEvent(new Event('gamepadconnected'));window.__virtualPad.buttons[0]={pressed:true,touched:true,value:1};});await page.waitForTimeout(250);const padAfter=await focus(page);results.checks.push({name:'injected-standard-gamepad-current-runtime',injectionVisible:await page.evaluate(()=>navigator.getGamepads()[0].buttons[0].pressed),focusBefore:padFocus,focusAfter:padAfter,saveChanged:(await save(page))!==padBefore,nativeGamepadHardware:false});await page.close();
 results.afterHashes=Object.fromEntries(Object.keys(beforeHashes).map(p=>[p,hash(p)]));results.runtimeUnchanged=JSON.stringify(results.beforeHashes)===JSON.stringify(results.afterHashes);writeFileSync(output,JSON.stringify(results,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({version:results.version,digest:results.actualDigest,runtimeUnchanged:results.runtimeUnchanged,checks:results.checks.map(c=>({name:c.name,firstHandTab:c.firstHandTab,after:c.after,saveChangedAfterRepeat:c.saveChangedAfterRepeat,motion:c.motion,afterReward:c.afterReward,saveChanged:c.saveChanged})),errors:results.errors},null,2));
}finally{await browser.close();}
