import type { CardDef } from "./engine";
const summon = (
  id: string,
  name: string,
  species: string,
  cost: number,
  hp: number,
  attack: number,
  text: string,
  color: string,
): CardDef => ({
  id,
  name,
  species,
  type: "summon",
  cost,
  hp,
  attack,
  text,
  color,
});
const spell = (
  id: string,
  name: string,
  cost: number,
  effect: string,
  value: number,
  text: string,
  color = "#e5bd68",
): CardDef => ({ id, name, type: "spell", cost, effect, value, text, color });
const base: CardDef[] = [
  summon(
    "mossling",
    "Mossling",
    "moss",
    1,
    8,
    3,
    "On summon: gain 3 hunter block.",
    "#91b978",
  ),
  summon(
    "cinderfox",
    "Cinder Fox",
    "fox",
    2,
    7,
    5,
    "On summon: deal 2 damage to every enemy.",
    "#e4925e",
  ),
  summon(
    "reedkin",
    "Reedkin",
    "reed",
    1,
    6,
    3,
    "On summon: draw 1 card.",
    "#74bab1",
  ),
  summon(
    "stonehart",
    "Stonehart",
    "stag",
    3,
    17,
    5,
    "On summon: gain 8 hunter block.",
    "#b3b8aa",
  ),
  summon(
    "moonmoth",
    "Moon Moth",
    "moth",
    2,
    6,
    3,
    "Whenever you cast a spell, gain 2 hunter block.",
    "#c5a4d5",
  ),
  summon(
    "bramblecat",
    "Bramble Cat",
    "cat",
    2,
    9,
    4,
    "Command: gain 2 hunter block.",
    "#a4bf7b",
  ),
  summon(
    "brookotter",
    "Brook Otter",
    "otter",
    2,
    10,
    3,
    "On summon: heal the hunter 3 HP.",
    "#80b5cb",
  ),
  summon(
    "thunderrook",
    "Thunder Rook",
    "rook",
    3,
    9,
    7,
    "On summon: other companions gain 1 attack this battle.",
    "#cbb5e6",
  ),
  summon(
    "lanternowl",
    "Lantern Owl",
    "owl",
    2,
    7,
    4,
    "On summon: gain 1 energy.",
    "#f0d18d",
  ),
  summon(
    "bogturtle",
    "Bog Turtle",
    "turtle",
    2,
    14,
    2,
    "On summon: all companions gain 4 block.",
    "#76a996",
  ),
  summon(
    "glimmerhare",
    "Glimmer Hare",
    "hare",
    1,
    5,
    2,
    "On summon: all other companions gain 2 block.",
    "#d6c99b",
  ),
  summon(
    "willowdrake",
    "Willow Drake",
    "drake",
    4,
    15,
    8,
    "On summon: deal 4 damage to every enemy.",
    "#6ab5ad",
  ),
  spell("spark", "Lantern Spark", 1, "damage", 6, "Deal 6 damage to an enemy."),
  spell("ward", "Woven Ward", 1, "block", 7, "Gain 7 hunter block.", "#94c7bf"),
  spell(
    "mend",
    "Dew Mend",
    1,
    "heal",
    5,
    "Heal a companion 5 HP and give it 2 block.",
    "#99c98e",
  ),
  spell(
    "rally",
    "Pack Rally",
    1,
    "rally",
    2,
    "All companions gain 2 attack this battle.",
    "#c5a4d5",
  ),
  spell(
    "gust",
    "Wild Gust",
    2,
    "aoe",
    4,
    "Deal 4 damage to every enemy.",
    "#88c8cb",
  ),
  spell(
    "recall",
    "Second Wind",
    1,
    "ready",
    2,
    "Ready a companion to command again; give it 2 block.",
    "#e5d0a3",
  ),
  spell(
    "siphon",
    "Moon Siphon",
    2,
    "siphon",
    7,
    "Deal 7 damage to an enemy. Heal the hunter 3 HP.",
    "#c5a4d5",
  ),
  spell("insight", "Firefly Reading", 1, "draw", 2, "Draw 2 cards.", "#eed590"),
  spell(
    "kindle",
    "Kindle",
    0,
    "energy",
    1,
    "Gain 1 energy. Lose 2 hunter HP.",
    "#f09e70",
  ),
  spell(
    "shelter",
    "Forest Shelter",
    2,
    "shelter",
    5,
    "Hunter and all companions gain 5 block.",
    "#94c7bf",
  ),
  spell(
    "thorns",
    "Briar Lance",
    2,
    "pack",
    5,
    "Deal 5 damage plus 2 per living companion to an enemy.",
    "#aac77b",
  ),
  spell(
    "communion",
    "Woodland Communion",
    2,
    "communion",
    3,
    "Heal the hunter 3 HP per living companion.",
    "#94c7bf",
  ),
];
export const CARDS: Record<string, CardDef> = Object.fromEntries(
  base.flatMap((c) => [
    [c.id, c],
    [
      c.id + "+",
      {
        ...c,
        id: c.id + "+",
        name: c.name + " +",
        hp: c.hp === undefined ? undefined : c.hp + 3,
        attack: c.attack === undefined ? undefined : c.attack + 1,
        value: c.value === undefined ? undefined : c.value + 2,
        text:
          c.type === "summon"
            ? c.text + " Enhanced: +3 HP, +1 attack."
            : upgradeText(c),
      },
    ],
  ]),
);
function upgradeText(c: CardDef): string {
  const v = (c.value ?? 0) + 2;
  return (
    {
      damage: `Deal ${v} damage to an enemy.`,
      block: `Gain ${v} hunter block.`,
      heal: `Heal a companion ${v} HP and give it 2 block.`,
      rally: `All companions gain ${v} attack this battle.`,
      aoe: `Deal ${v} damage to every enemy.`,
      ready: `Ready a companion to command again; give it ${v} block.`,
      siphon: `Deal ${v} damage to an enemy. Heal the hunter 3 HP.`,
      draw: `Draw ${v} cards.`,
      energy: `Gain ${v} energy. Lose 2 hunter HP.`,
      shelter: `Hunter and all companions gain ${v} block.`,
      pack: `Deal ${v} damage plus 2 per living companion to an enemy.`,
      communion: `Heal the hunter ${v} HP per living companion.`,
    } as Record<string, string>
  )[c.effect!];
}
export const BASE_CARD_IDS = base.map((c) => c.id);
export const STARTER_DECK = [
  "mossling",
  "mossling",
  "cinderfox",
  "reedkin",
  "lanternowl",
  "spark",
  "spark",
  "ward",
  "ward",
  "mend",
  "rally",
  "insight",
];
export const SHOP_PRICES = { summon: 55, spell: 40, remove: 35 };
export const RELICS: Record<string, { name: string; text: string }> = {
  "moon-charm": {
    name: "Moon Charm",
    text: "All spell damage increases by 1.",
  },
  "ember-seed": {
    name: "Ember Seed",
    text: "Your summoned companions have 2 additional HP.",
  },
  "brass-bell": {
    name: "Brass Bell",
    text: "Gain 1 additional energy on the first turn of each battle.",
  },
};
export const EVENT_CHOICES: Record<string, { name: string; text: string }> = {
  offering: {
    name: "Light the shrine",
    text: "Lose 8 HP. Receive Moon Charm (+1 spell damage).",
  },
  forage: { name: "Gather fallen coins", text: "Gain 25 gold." },
  leave: { name: "Leave the grove", text: "Continue safely." },
};
export const ENEMIES: Record<
  string,
  { name: string; species: string; hp: number; attack: number; color: string }
> = {
  briar: {
    name: "Briar Imp",
    species: "imp",
    hp: 13,
    attack: 4,
    color: "#ac8261",
  },
  wisp: {
    name: "Hollow Wisp",
    species: "wisp",
    hp: 10,
    attack: 4,
    color: "#b791cb",
  },
  wolf: {
    name: "Ash Wolf",
    species: "wolf",
    hp: 20,
    attack: 6,
    color: "#b5998a",
  },
  sentinel: {
    name: "Root Sentinel",
    species: "sentinel",
    hp: 28,
    attack: 5,
    color: "#879b71",
  },
  witch: {
    name: "Mire Witch",
    species: "witch",
    hp: 22,
    attack: 5,
    color: "#bc87b1",
  },
  crown: {
    name: "The Hollow Crown",
    species: "crown",
    hp: 110,
    attack: 10,
    color: "#d2b26d",
  },
};
