import assert from 'node:assert/strict';
import {chromium} from '/workspace/Roguelike-deckbuilder/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
const base='/workspace/scratch/gameplay-v06-input',endpoint='http://127.0.0.1:4173',digest=process.argv[2],runid=process.argv[3];assert.match(digest,/^[a-f0-9]{64}$/);assert.match(runid,/^[a-z0-9-]+$/);const output=base+'/'+runid+'.json';assert.ok(!existsSync(output));const refs=JSON.parse(gunzipSync(readFileSync(base+'/references.json.gz'))),hash=v=>createHash('sha256').update(v).digest('hex');
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const results=[];const canonical=p=>p.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('hollowpact.run.v2'))));
async function seek(p,selector){for(let i=0;i<180;i++){if(await p.evaluate(s=>document.activeElement.matches(s),selector))return i;await p.keyboard.press('Tab');}throw Error('Native Tab cannot reach '+selector);}
async function choose(p,selector,pad=false){await seek(p,selector);if(!pad)await p.keyboard.press('Enter');else{await p.evaluate(()=>window.__qaPad.buttons[0]={pressed:true,touched:true,value:1});await p.waitForTimeout(65);await p.evaluate(()=>window.__qaPad.buttons[0]={pressed:false,touched:false,value:0});await p.waitForTimeout(65);}}
function persist(){writeFileSync(output,JSON.stringify({scope:'Actual shipped production input; complete native-keyboard fresh campaign and gamepad-activated/native-Tab-navigated legacy campaign. No DOM click/focus teleport for action/navigation. Synthetic pad samples; not physical/controller-only certification. Reused archived model policy is not human enjoyment.',digest,harnessSHA:hash(readFileSync(import.meta.filename)),referenceSHA:hash(readFileSync(base+'/references.json.gz')),results},null,2)+'\n');}
try{for(const run of refs.campaigns){const kind=run.kind,fresh=kind===2,pad=!fresh;const c=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'no-preference'});await c.addInitScript(({start,fresh})=>{localStorage.setItem('hollowpact.tutorial.v2','yes');if(!localStorage.getItem('hollowpact.settings.v2'))localStorage.setItem('hollowpact.settings.v2',JSON.stringify({mute:true,volume:0,motion:true}));if(!fresh&&localStorage.getItem('hollowpact.run.v2')===null)localStorage.setItem('hollowpact.run.v2',JSON.stringify(start));window.__qaPad={index:0,connected:true,mapping:'standard',axes:[0,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,touched:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{value:()=>[window.__qaPad]});},{start:run.start,fresh});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const record={kind,seed:run.seed,fresh,motion:true,mode:pad?'Gamepad activation with native Tab navigation':'Native keyboard only, no DOM click/focus navigation',accepted:0,actionCounts:{},holds:[],reload:null,pass:false,trace:[]};results.push(record);
try{await p.goto(endpoint);assert.equal((await(await p.request.get(endpoint+'/build-provenance.json')).json()).sourceDigest,digest);await p.waitForTimeout(100);
if(fresh){await choose(p,'[data-ui="new"]');await seek(p,'#seed');await p.keyboard.press('Control+a');await p.keyboard.type(String(run.seed));await seek(p,'input[name="difficulty"][value="1"]');await p.keyboard.press('Space');await choose(p,'#new-run-form button[type="submit"], #dialog button[type="submit"]');}else await choose(p,'[data-ui="resume"]',pad);assert.equal(await canonical(p),JSON.stringify(run.start));
for(const t of run.trace){await p.waitForFunction(()=>!document.querySelector('#app').classList.contains('settling-combat'));const before=await canonical(p);assert.equal(hash(before),t.beforeHash,'Before action '+record.accepted);const a=t.action;
if(a.type==='play'){await p.keyboard.press('h');await choose(p,`[data-ui="play-card"][data-index="${a.index}"]`,pad);if(a.target)await choose(p,`[data-unit="${a.target}"]`,pad);}
else if(a.type==='attack'){await p.keyboard.press('b');await choose(p,`[data-unit="${a.unit}"]`,pad);await choose(p,`[data-unit="${a.target}"]`,pad);}
else if(a.type==='camp'&&a.choice==='train'){await choose(p,'[data-ui="train"]',pad);await choose(p,`[data-action="camp"][data-choice="train"][data-index="${a.index}"]`,pad);}
else if(['travel','camp','event'].includes(a.type))await choose(p,`[data-action="${a.type}"][data-choice="${a.choice}"]`,pad);
else if(a.type==='reward')await choose(p,`[data-action="reward"][data-card="${a.card??''}"]`,pad);
else if(a.type==='buy')await choose(p,`[data-action="buy"][data-card="${a.card}"]`,pad);
else if(a.type==='remove'){await choose(p,'[data-ui="remove"]',pad);await choose(p,`[data-action="remove"][data-index="${a.index}"]`,pad);}
else if(a.type==='leave')await choose(p,'[data-action="leave"]',pad);
else if(a.type==='endTurn'){if(pad){await p.evaluate(()=>window.__qaPad.buttons[3]={pressed:true,touched:true,value:1});await p.waitForTimeout(65);await p.evaluate(()=>window.__qaPad.buttons[3]={pressed:false,touched:false,value:0});await p.waitForTimeout(65);}else await p.keyboard.press('e');if(await p.locator('[data-ui="confirm-end"]').isVisible())await choose(p,'[data-ui="confirm-end"]',pad);}
else throw Error('Unhandled '+a.type);
const actual=await canonical(p);assert.equal(hash(actual),t.afterHash,'Actual action '+record.accepted+': '+JSON.stringify(a));record.accepted++;record.actionCounts[a.type]=(record.actionCounts[a.type]||0)+1;const s=JSON.parse(actual);assert.equal(s.schema,kind===1?2:3);assert.equal(Object.hasOwn(s,'engineKind'),kind===2);record.trace.push({action:a,afterHash:t.afterHash,focus:await p.evaluate(()=>({tag:document.activeElement.tagName,ui:document.activeElement.dataset.ui,unit:document.activeElement.dataset.unit})),phase:s.phase});
if(await p.locator('#app').evaluate(e=>e.classList.contains('settling-combat'))){const began=Date.now();await p.keyboard.press('e');assert.equal(await canonical(p),actual);await p.waitForFunction(()=>!document.querySelector('#app').classList.contains('settling-combat'));record.holds.push({step:record.accepted,phase:s.phase,canonicalImmediate:true,staleEUnchanged:true,observedRemainingMs:Date.now()-began});assert.notEqual(await p.evaluate(()=>document.activeElement.tagName),'BODY');}
if(!record.reload&&record.accepted>=15&&s.phase==='battle'){await p.reload();await choose(p,'[data-ui="resume"]',pad);assert.equal(await canonical(p),actual);record.reload={step:record.accepted,canonicalExact:true};}
if(record.accepted%25===0){persist();console.log(JSON.stringify({seed:run.seed,accepted:record.accepted,phase:s.phase}));}
}
const s=JSON.parse(await canonical(p));assert.equal(s.phase,run.final?.phase||run.phase);assert.equal(s.hp,run.final?.hp??run.hp);assert.deepEqual(errors,[]);record.pass=true;record.outcome={phase:s.phase,hp:s.hp};record.errors=errors;persist();console.log(JSON.stringify({seed:run.seed,accepted:record.accepted,pass:true}));
}catch(e){record.error=String(e.stack||e);record.errors=errors;record.actualSaveHash=hash(await canonical(p).catch(()=>''));persist();console.log(JSON.stringify({seed:run.seed,accepted:record.accepted,pass:false,error:e.message}));}finally{await c.close();}}
}finally{await browser.close();}persist();
