import os,json,pathlib,hashlib,resource,stat
P=pathlib.Path(__file__).parent
def pin(p):
 b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def put(n,j):
 b=(json.dumps(j,indent=2)+'\n').encode();assert sum(x.stat().st_size for x in P.rglob('*')if x.is_file())+len(b)+4500<=65536
 with (P/n).open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
d=json.loads((P/'PROOF.json').read_bytes());g=json.loads((P/'PROOF-R3-GUARD/RESULT.json').read_bytes());assert g['exit_code']==0 and g['failure'] is None
packs=[]
for leaf in ['pack-b3e7e0bb9ce2d0a4d41cdb2daf9b6c3412cebe58.pack','pack-9df113d0f8345ab53202de176f58359847fee9c1.pack']:
 p=pathlib.Path('/workspace/Roguelike-deckbuilder/.git/objects/pack')/leaf;s=p.lstat();assert stat.S_ISREG(s.st_mode)
 packs.append({'path':str(p),'metadata':{k:getattr(s,k) for k in ['st_dev','st_ino','st_mode','st_uid','st_gid','st_nlink','st_size','st_blocks','st_mtime_ns','st_ctime_ns','st_atime_ns']},'xattrs':{k:os.getxattr(p,k).hex() for k in os.listxattr(p)},'bodyOpened':False,'bodySHA256Verified':False,'authority':'Metadata-only optional cache-advice candidate, not body identity certification or Git integrity proof. Separate Root scope and pinned read-only descriptor/fstat validation required; no hint executed.'})
put('CACHE-METADATA-ONLY.json',{'gitPackCandidates':packs,'qualification':'No pack/release/protectedZIP body read, hash, verify, extraction, deletion, timestamp mutation or fadvise. Filename-first named pack stat only, separately requested by Root. Any advice is advisory, may be ignored and cannot reclaim disk. Ordinary canonical4513/atlas fully hashed candidates are in PROOF.json.'})
current=pathlib.Path('/workspace/Roguelike-deckbuilder/reviews/opening-native-aftermath-and-starter-art-2026-10-02/archive/INDEX.json');ci=json.loads(current.read_bytes());r=next(r for r in ci['existingCapsules']if r['archive']['sha256']==d['pair'][0]['sha256']);assert r['archive']['path']==d['pair'][1]['path']
put('GATE.json',{'decision':'ACCEPT_CONDITIONAL_ONE_PRIVATE_SCRATCH_4513_ENCODING_RETIREMENT_PREFERENCE_ONLY','actionAuthority':False,'cacheHintAuthority':False,'candidate':d['pair'][0],'replacement':d['pair'][1],'replacementPreference':'Pushed canonical exact container and index preserve all body/logical/right/source/rollback history and are used by latest checkpoint inheritance. No named current runtime source consumer required this extra scratch physical encoding in the fixed scan. Preserve the remaining scratch controls.','grossPrivateAllocatedBytes':d['pair'][0]['before']['st_blocks']*512,'netRecoveryOrBrowserAdmissionGuaranteed':False,'currentPublishedInheritance':{'index':pin(current),'row':r},'completeMemberAuthority':{'gate':d['completeMemberProof'],'index':d['indexes'][0],'scope':'Prior independently accepted952 logical/711 new body coverage inherited; fresh full container literal equality and SHA checked, no new member decode.'},'proof':pin(P/'PROOF.json'),'historicalScratchPathNeed':'INDEX.newArchive, original COMPLETE reader/gate, Root selection/publication/grant methods name this scratch path. Keep all originals unchanged and publish an append-only exact location mapping before action. Old reader replay requires separately reviewed fresh exact-byte reconstruction; no automatic restore, occupied-path overwrite, original inode/time restoration, or universal compatibility claim.','futureRequirements':['Publish this proposal, original metadata and exact scratch-to-canonical location map before action.','Fresh confirmed current clean push including proposal/map/method and preserve the prior9726 receipt as observed coverage, not a future grant.','Root separate producer judgment that canonical retention is preferable AND this private scratch encoding no longer needed.','Independent review of finite exact-one-path action and fresh complete pair/hash/meta/private-nlink1/namespace checks before any Root action.','Independent POST verifies canonical body and all retained controls; no other deletion authority.'],'failuresPreserved':['PROOF-GUARD exit1 original verbose proof per-file32768 serialization bound refused.','PROOF-R2-GUARD exit1 compact format still duplicated a50632-byte historical push receipt.','PROOF-R3-GUARD normal0 after using exact pinned receipt references. Neither failure was a body mismatch/resource stop; original scripts/logs retained.'],'limits':'307 fixed named source/doc/review/author/output files,4928897 bytes,26 matched files,0 skipped in this finite scan. No global consumer/FD/exclusive cgroup absence, rights reassignment, runtime performance/art/default/release/platform/fun claim. No cleanup or hints executed.','relationship':json.loads((P/'FINDING.json').read_bytes())['relationship']})
rows=[pin(p) for p in sorted(P.rglob('*'))if p.is_file() and 'SEAL-GUARD' not in p.parts]
put('MANIFEST.json',{'members':rows,'activeSealGuardExcludedUntilClosed':True,'allocationLogicalBytes':65536,'originalFailuresRetained':True})
rss=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*1024;assert rss<24*1048576
put('CLOSURE.json',{'guard':'SEAL-GUARD ordinary64+512/disk64; caller must observe normal completion before closure report','ownMaxRSSBytes':rss,'proofOwnMaxRSSBytes':d['ownMaxRSSBytes'],'operationScope':'Read-only finite triage and owned packet writes; no storage mutation, hint, Git or runtime','cgroupAttribution':'Shared cgroup samples nonexclusive','guardPins':pin(P/'PROOF-R3-GUARD/RESULT.json')})
for row in json.loads((P/'MANIFEST.json').read_bytes())['members']:assert pin(pathlib.Path(row['path']))==row
put('FINAL-SEAL.json',{'gate':pin(P/'GATE.json'),'manifest':pin(P/'MANIFEST.json'),'closure':pin(P/'CLOSURE.json'),'allocationLogicalBytes':65536,'scope':'Conditional preference only; all small immutable members full-readback. Active seal log/result excluded, actual normal completion reported separately.'})
fd=os.open(P,os.O_RDONLY|os.O_DIRECTORY);os.fsync(fd);os.close(fd)
print(json.dumps({'gate':pin(P/'GATE.json'),'finalSeal':pin(P/'FINAL-SEAL.json'),'ownRSSBytes':rss,'packetLogicalPreGuardTail':sum(p.stat().st_size for p in P.rglob('*')if p.is_file())}))
