import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {validateState} from '../../src/engine.ts';
const out='reviews/technical-v0.6-hints-evidence',base='http://127.0.0.1:4173',digest='0ec0187f0a42eb519000646695980dd91e1e026e1cb925b96935ee3e8646acde';
const fixture=JSON.parse(fs.readFileSync('reviews/screenshots-v0.2/full-fixture.json'));const drawIndex=fixture.draw.indexOf('scour');[fixture.hand[0],fixture.draw[drawIndex]]=[fixture.draw[drawIndex],fixture.hand[0]];assert.ok(validateState(fixture));
const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-gpu']}),report={digest,method:'Actual production host; valid diagnostic full inventory with Scour swapped from draw into hand. Virtual standard pad, no physical hardware.',checks:[],errors:[],remote:[]};
async function state(p){return p.evaluate(()=>({save:localStorage.getItem('hollowpact.run.v2'),text:document.querySelector('.keyboard-hint').textContent,mode:document.querySelector('.keyboard-hint').getAttribute('aria-label'),selected:document.querySelectorAll('.unit.selected,.game-card.selected').length,focus:document.activeElement.dataset.unit||document.activeElement.dataset.focus,target:document.activeElement.matches('.valid-target')}));}
async function pad(p,index){await p.evaluate(index=>window.pad.buttons[index]={pressed:true,value:1},index);await p.waitForTimeout(100);await p.evaluate(index=>window.pad.buttons[index]={pressed:false,value:0},index);await p.waitForTimeout(100);}
try{for(const kind of ['binding','targeted-card']){const ctx=await b.newContext({viewport:{width:1920,height:720}});await ctx.addInitScript(f=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(f));localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion:false,mute:true,volume:0}));localStorage.setItem('hollowpact.tutorial.v2','yes');window.pad={index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(window.pad,'id',{get(){throw Error('Identity must not be read');}});Object.defineProperty(navigator,'getGamepads',{value:()=>[window.pad]});},fixture);const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(base))report.remote.push(r.url());});await p.goto(base);assert.equal(await p.evaluate(async()=> (await(await fetch('./build-provenance.json')).json()).sourceDigest),digest);await p.locator('[data-ui=resume]').click();await p.waitForTimeout(150);const before=await state(p);
await p.keyboard.press('h');assert.ok(await p.evaluate(()=>document.activeElement.matches('.hand-cards button')));await p.keyboard.press('b');assert.ok(await p.evaluate(()=>document.activeElement.matches('.ally')));await p.keyboard.press('t');assert.ok((await state(p)).target===false);assert.ok(await p.evaluate(()=>document.activeElement.matches('.enemy')));assert.match((await state(p)).text,/H Hand.*B Bindings.*T Hostiles/);assert.equal((await state(p)).save,before.save);
const source=kind==='binding'?`[data-unit="${fixture.allies[0].uid}"]`:'[data-ui=play-card][data-card=scour]';await p.locator(source).focus();await p.keyboard.press('Enter');const selected=await state(p);assert.equal(selected.mode,'Keyboard controls');assert.match(selected.text,/Enter Choose.*Esc Cancel.*T Targets/);assert.doesNotMatch(selected.text,/H Hand|B Bindings/);assert.ok(selected.target);assert.equal(selected.save,before.save);const target=selected.focus;
for(const key of ['h','b']){await p.keyboard.press(key);const now=await state(p);assert.equal(now.focus,target);assert.equal(now.save,before.save);}await p.keyboard.press('ArrowDown');assert.ok((await state(p)).target);assert.notEqual((await state(p)).focus,target);await p.keyboard.press('t');assert.ok((await state(p)).target);assert.equal((await state(p)).save,before.save);
await pad(p,5);const controller=await state(p);assert.equal(controller.mode,'Controller controls');assert.match(controller.text,/D-pad Move.*Start Pause/);assert.doesNotMatch(controller.text,/LB\/RB Regions/);assert.ok(controller.target);assert.equal(controller.save,before.save);await pad(p,13);assert.ok((await state(p)).target);assert.equal((await state(p)).save,before.save);await p.keyboard.press('t');assert.equal((await state(p)).mode,'Keyboard controls');assert.match((await state(p)).text,/T Targets/);
const geometry=[];for(const viewport of [{width:1920,height:720},{width:1600,height:800},{width:1280,height:720}]){await p.setViewportSize(viewport);const rect=await p.evaluate(()=>{const hint=document.querySelector('.keyboard-hint'),dock=document.querySelector('#dock');return{hint:hint.getBoundingClientRect().toJSON(),dock:dock.getBoundingClientRect().toJSON(),spans:[...hint.children].map(s=>({text:s.textContent,width:s.clientWidth,scroll:s.scrollWidth,rect:s.getBoundingClientRect().toJSON()}))};});assert.ok(rect.hint.bottom<=rect.dock.bottom+1);for(const s of rect.spans){assert.ok(s.rect.right<=rect.hint.right+1);assert.ok(s.rect.bottom<=rect.hint.bottom+1);assert.ok(s.scroll<=s.width+1);}geometry.push({viewport,...rect});}
await pad(p,1);const canceled=await state(p);assert.equal(canceled.selected,0);assert.equal(canceled.save,before.save);assert.equal(canceled.mode,'Controller controls');assert.match(canceled.text,/LB\/RB Regions/);await p.keyboard.press('h');assert.equal((await state(p)).mode,'Keyboard controls');assert.match((await state(p)).text,/H Hand.*B Bindings.*T Hostiles/);assert.equal((await state(p)).save,before.save);await p.screenshot({path:`${out}/${kind}-normal-restored.png`});report.checks.push({kind,passed:true,normalRegionsAccurate:true,targetingHintsAccurate:true,selectedHBInert:true,targetNavigationReadonly:true,controllerRegionHintRemovedWhileSelected:true,controllerAndKeyboardRestoreNormalMode:true,saveByteExact:true,geometry});await ctx.close();}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.remote,[]);
}finally{await b.close();fs.writeFileSync(out+'/checks.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});}console.log(JSON.stringify({checks:report.checks.map(x=>({kind:x.kind,passed:x.passed})),errors:report.errors,remote:report.remote}));
