import{chromium}from'../node_modules/playwright/index.mjs';import{readFileSync,writeFileSync}from'node:fs';import{gunzipSync}from'node:zlib';import{createHash}from'node:crypto';
if(process.argv[2]!=='--go')throw Error('Wait for root freezeGO');const endpoint='http://127.0.0.1:4173',root=process.cwd(),legacy=JSON.parse(gunzipSync(readFileSync('reviews/solo-v0.3/silence-overflow-campaign.json.gz')).toString());const inputs=JSON.parse(gunzipSync(readFileSync('reviews/gameplay-v0.4-browser-inputs.json.gz')).toString());
const canonical=structuredClone(legacy.afterState);canonical.enemies[0].intent.label='Raise plated shield · gain 14 block · silenced (armor remains)';const continued=inputs.find(r=>r.knownCampaign).continued;
const b=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']}),records=[];
try{for(const mode of ['recover','backup-collision','reject-corrupt']){
 const state=structuredClone(legacy.afterState);if(mode==='reject-corrupt')state.deck.pop();const raw=JSON.stringify(state),context=await b.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({raw,mode})=>{if(!sessionStorage.getItem('reviewRecoverySetup')){localStorage.setItem('hollowpact.run.v2',raw);localStorage.setItem('hollowpact.settings.v2',JSON.stringify({mute:true,volume:0,motion:false}));localStorage.setItem('hollowpact.tutorial.v2','yes');if(mode==='backup-collision')localStorage.setItem('hollowpact.run.v2.backup.silence','PRIOR OTHER BACKUP - MUST SURVIVE');sessionStorage.setItem('reviewRecoverySetup','yes');}},{raw,mode});
 await page.goto(endpoint);const served=(await(await page.request.get(endpoint+'/build-provenance.json')).json()).sourceDigest;const notice=await page.locator('.save-notice').innerText(),values=await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage))),backupKeys=Object.keys(values).filter(k=>k.startsWith('hollowpact.run.v2.backup.silence'));
 let recovered=false,reloaded=false,backupOriginal=false;
 if(mode==='reject-corrupt'){if(await page.locator('[data-ui="resume"]').count())throw Error('Corrupt save resumed');if(values['hollowpact.run.v2']!==raw||backupKeys.length)throw Error('Corrupt save overwritten/backed up as valid');}
 else{if(JSON.stringify(JSON.parse(values['hollowpact.run.v2']))!==JSON.stringify(canonical))throw Error('Recovered state differs');backupOriginal=backupKeys.some(k=>values[k]===raw);if(!backupOriginal)throw Error('Raw backup missing');if(mode==='backup-collision'&&values['hollowpact.run.v2.backup.silence']!=='PRIOR OTHER BACKUP - MUST SURVIVE')throw Error('Earlier backup overwritten');await page.locator('[data-ui="resume"]').click();recovered=true;await page.locator('[data-action="endTurn"]').click();if(await page.locator('[data-ui="confirm-end"]').isVisible())await page.locator('[data-ui="confirm-end"]').click();const after=await page.evaluate(()=>localStorage.getItem('hollowpact.run.v2'));if(JSON.stringify(JSON.parse(after))!==JSON.stringify(continued))throw Error('Continuation differs');await page.reload();await page.locator('[data-ui="resume"]').click();if(after!==await page.evaluate(()=>localStorage.getItem('hollowpact.run.v2')))throw Error('Reload changed valid continuation');reloaded=true;}
 await page.screenshot({path:`${root}/reviews/gameplay-v0.4-recovery-${mode}.png`});records.push({mode,servedBuild:served,notice,recovered,reloaded,backupOriginal,backupKeys,originalRawSHA:createHash('sha256').update(raw).digest('hex'),errors,method:'Targeted finalproduction loader on a previously independently replayed legacy save. Original/canonical/continued bytes compared, existing backup collision preserved, unrelated card-copy corruption rejected. Separate from fresh full119-action browser replay.'});await context.close();
}const p='reviews/gameplay-v0.4-evidence.json',e=JSON.parse(readFileSync(p,'utf8'));e.recoveryBrowser=records;writeFileSync(p,JSON.stringify(e,null,2)+'\n');console.log(JSON.stringify(records));}finally{await b.close();}
