import assert from 'node:assert/strict';
import{chromium}from'/workspace/Roguelike-deckbuilder/node_modules/playwright/index.mjs';
import{readFileSync,writeFileSync}from'node:fs';
import{createHash}from'node:crypto';
const root='/workspace/Roguelike-deckbuilder',out=root+'/reviews/gameplay-v0.5-runtime',digest='d6221bf764bad593b04981e87bead7ba6868b72cf361d70671af5c91aac39416';
const path=root+'/reviews/arena-v0.5-facing/fixtures.json',cases=JSON.parse(readFileSync(path,'utf8'));
const expected={ 'warleader-melee-left':-1,'warleader-melee-right':1,'warleader-hunter-right':1,'warleader-right-blocked':1,'warleader-dense-far-right':1,'warleader-vertical-default':-1,'hound-crosscolumn-left':-1,'hound-crosscolumn-right':1,'hound-left-mutual-death':-1 };
const b=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']}),results=[];
try{for(const f of cases){
 const c=await b.newContext({viewport:{width:1280,height:720}});await c.addInitScript(s=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(s));localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion:true,mute:true,volume:0}));localStorage.setItem('hollowpact.tutorial.v2','yes');window.records=[];const d=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(...a){const r=d.apply(this,a),image=a[0];if(this.canvas.id==='arena'&&image instanceof HTMLImageElement&&a.length===9&&(image.src.endsWith('warleader-poses.png')||image.src.endsWith('hound-poses.png'))){const m=this.getTransform();records.push({t:performance.now(),url:image.src,source:a.slice(1,5),face:m.a,ground:{x:m.e,y:m.f},alpha:this.globalAlpha});}return r;};},f.before);
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173');assert.equal((await(await p.request.get('http://127.0.0.1:4173/build-provenance.json')).json()).sourceDigest,digest);await p.locator('[data-ui="resume"]').click();assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('hollowpact.run.v2'))),f.before);await p.waitForTimeout(150);await p.evaluate(()=>records=[]);
 const a=f.action;if(a.type==='endTurn'){await p.locator('[data-action="endTurn"]').click();const confirm=p.locator('[data-ui="confirm-end"]');if(await confirm.isVisible())await confirm.click();}else{await p.locator(`[data-unit="${a.unit}"]`).click();await p.locator(`[data-unit="${a.target}"]`).click();}
 assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('hollowpact.run.v2'))),f.state);
 await p.waitForTimeout(250);await p.locator('#arena').screenshot({path:out+'/d622-facing-'+f.name+'.png'});await p.waitForTimeout(650);const records=await p.evaluate(()=>records),family=f.name.startsWith('hound')?'hound-poses.png':'warleader-poses.png';
 const strikes=records.filter(r=>r.url.endsWith(family)&&r.source[0]>=1024&&r.source[1]<512&&r.alpha>.9);
 if(Object.hasOwn(expected,f.name)){assert.ok(strikes.length,'Missing actual attack frames '+f.name);assert.ok(strikes.every(r=>Math.sign(r.face)===expected[f.name]),'Wrong direction '+f.name);}
 const dead=records.filter(r=>r.url.endsWith(family)&&r.source[0]>=1024&&r.source[1]>=512&&r.alpha>.1);
 if(f.name==='hound-left-mutual-death'){assert.ok(dead.length);assert.ok(dead.every(r=>Math.sign(r.face)===-1));}
 await p.waitForFunction(()=>!document.querySelector('#app').classList.contains('settling-combat'));assert.deepEqual(errors,[]);
 results.push({name:f.name,build:digest,canonicalExact:true,expectedPhysicalFacing:expected[f.name]??null,actualAttackFaces:[...new Set(strikes.map(r=>Math.sign(r.face)))],attackDraws:strikes.length,deathFaces:[...new Set(dead.map(r=>Math.sign(r.face)))],expectedActualEvents:f.events,errors,records});writeFileSync(out+'/facing-results-d622.json',JSON.stringify({method:'Independent actual final production DOM actions and read-only atlas transform capture. These14positions are validated author diagnostics, not earned campaigns. Direction sign is checked for literal named target geometry, not claimed anatomical hitbox/contact precision.',inputSHA256:createHash('sha256').update(readFileSync(path)).digest('hex'),sourceArenaSHA:createHash('sha256').update(readFileSync(root+'/src/arena.ts')).digest('hex'),results},null,2)+'\n');await c.close();
}console.log(JSON.stringify(results.map(r=>({name:r.name,expected:r.expectedPhysicalFacing,attackFaces:r.actualAttackFaces,deathFaces:r.deathFaces,canonical:r.canonicalExact,errors:r.errors}))));}finally{await b.close();}
