import hashlib,json,os,pathlib,resource,time
P=pathlib.Path(__file__).parent;OLD=P.parent/'opening-cue-duplicate-retirement-independent-r1';CAP=64*1024;began=time.monotonic()
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  while b:=f.read(32768):h.update(b)
 return h.hexdigest()
def put(n,x):
 b=(json.dumps(x,separators=(',',':'))+'\n').encode();assert sum(p.stat().st_size for p in P.rglob('*') if p.is_file())+len(b)+4096<=CAP
 with (P/n).open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
old_files={str(p.relative_to(OLD)):{'sha256':sha(p),'bytes':p.stat().st_size} for p in OLD.rglob('*') if p.is_file()};assert sum(r['bytes'] for r in old_files.values())==62205
proof=json.loads((OLD/'PROOF.json').read_text());review=json.loads((OLD/'REVIEW.json').read_text());g=json.loads((OLD/'PROOF-GUARD-R3/RESULT.json').read_text());assert g['exit_code']==0 and g['failure'] is None and g['memory_events_before']==g['memory_events_after'];assert review['cleanupAuthority'] is False
put('R1-INVENTORY.json',{'root':str(OLD),'logicalBytes':62205,'originalCapBytes':65536,'allMemberBodiesFreshFullSHAReadback':True,'files':old_files,'originalSealReserveRefusal':'Stopped before GATE at62205B; old packet remains unchanged and has no completed64KiB gate/seal claim.'})
refs={n:{'path':str(OLD/n),'sha256':sha(OLD/n)} for n in ['PROOF.json','REVIEW.json','LOCATION-MAP.json','CONSUMER-SUPPLEMENT.json']}
gate={'decision':'ACCEPT_CONDITIONAL_TWO_PRIVATE_SCRATCH_CONTAINER_ENCODING_RETIREMENT_PREFERENCE_ONLY','phase':'NEW_R2_PROPOSAL_NO_BODY_RERUN_NO_ACTION_METHOD_ACCEPTANCE','basis':refs,'oldPacketInventorySHA256':sha(P/'R1-INVENTORY.json'),'exactCandidates':[{k:r[k] for k in ['id','scratchPath','canonicalPath','sha256','bytes','grossOnlyIfPrivateLastLink']} for r in proof['archivePairs']],'replacementBetterAndKnownCurrentEncodingNeed':'Prefer confirmed-pushed canonical evidence references used by4513/current preservation. Complete bodies/logical provenance/rights/rollback remain needed and retained there; known current workflow does not need an additional private scratch encoding. Metadata/history of old path/inode/times retained in exactR1 proof/location map. This is bounded dependency judgment, not universal consumer absence.','historicalPathQualification':'Old direct readers, f912 INDEX and COMPLETE receipts still name scratch archive paths. Future absence requires published explicit mapping or separately reviewed reconstruction of exact old container bytes from canonical into a fresh/missing path. No automatic restore, inode/time rollback or compatibility with every old reader claimed; historical runtime/source context may require separate reconstruction too. Never rewrite original index/reviews or overwrite occupied/user-changed paths.','mandatoryBeforeAnyAction':['Publish exact proposal/location map preserving original history and qualify old current-path statements','Fresh confirmed current clean push includes mapping/new checkpoint/retirement controls; old06007 receipt is historical coverage, not future cleanup grant','Recorded separate Root producer preference/no-longer-needed operational-copy judgment','Separate independent SOURCE review of Root finite exact2-path method with full fresh body/meta/namespace/nlink/canonical checks and mismatch failstop','Only then Root action and separately independent POST; preserve all other old controls/archives/art/versions/source/inputs/datasets'], 'limits':['No all-consumer/FD/OS/global actor absence','Fresh full pair equality/canonical member hash sets inherited from own closed normalR1 guard; no body rerun inR2','12,173,312B gross is not net recovery or fresh native/browser/Git admission','No newpreserver COMPLETE/selfcontained/release/fun/platform/art approval'],'roleDisclosure':proof['roleDisclosure'],'retireCanonicalArchiveOrOtherMaterials':False,'actionAuthority':False}
put('GATE.json',gate)
assert resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
put('CLOSURE.json',{'phase':'R2_FINAL_PROPOSAL_REFERENCE_SEAL_ONLY','R1FixedLogicalBytes':62205,'R1UnchangedInventorySHA256':sha(P/'R1-INVENTORY.json'),'normalR1BodyProofGuard':refs['PROOF.json'],'normalR1GuardResultSHA256':sha(OLD/'PROOF-GUARD-R3/RESULT.json'),'R1FailuresPreserved':['rows versuslogicalBodies assumption','blob-only versus embeddedINDEX assumption','final64KiB reserve refusal beforeGATE'],'R2NoArchiveBodyOrSourceRuntimeReread':True,'R2OwnRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'resources':'Ordinary64+512/disk64/own24 unchanged, shared-cgroup attribution nonexclusive','familyLogicalCapBytes':CAP,'originalFamilyNotRaisedOrWritten':True,'sourceGateRequiresLaterRootMethodPushProducerPOST':True,'newCleanupOrReconstructionAuthority':False,'terminalClosure':'Only after outerR2 SEAL-GUARD normal0 may caller reportTOOL_GUARD_CLOSED; late log/RESULT excluded from immutable inventory.'})
put('MANIFEST.json',{'files':{str(p.relative_to(P)):{'sha256':sha(p),'bytes':p.stat().st_size} for p in P.rglob('*') if p.is_file() and 'SEAL-GUARD' not in p.parts},'lateOutsideInventory':['SEAL-GUARD/*','MANIFEST.json','FINAL-SEAL.json']})
put('FINAL-SEAL.json',{'GATE_SHA256':sha(P/'GATE.json'),'R1_INVENTORY_SHA256':sha(P/'R1-INVENTORY.json'),'MANIFEST_SHA256':sha(P/'MANIFEST.json'),'CLOSURE_SHA256':sha(P/'CLOSURE.json'),'originalR1NotModified':True,'capLogicalBytes':CAP,'actionAuthority':False,'outerNormalReturnRequired':True})
assert (P/'GATE.json').stat().st_size+(P/'CLOSURE.json').stat().st_size+(P/'FINAL-SEAL.json').stat().st_size<=8192
print(json.dumps({'normal':True,'GATE_SHA256':sha(P/'GATE.json'),'FINAL_SHA256':sha(P/'FINAL-SEAL.json'),'logicalBeforeWrapperResult':sum(p.stat().st_size for p in P.rglob('*') if p.is_file()),'ownRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'elapsedSeconds':time.monotonic()-began}))
