import json,hashlib,resource
from pathlib import Path
P=Path(__file__).parent
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
a=json.loads((P/'AUDIT.json').read_bytes());r=json.loads((P/'audit-guard/RESULT.json').read_bytes());assert r['exit_code']==0 and r['failure'] is None and r['memory_events_before']==r['memory_events_after']
gate={'decision':a['decision'],'accepted':True,'COMPLETE':True,'preservationOnly':True,'archivePath':'/workspace/Roguelike-deckbuilder/reviews/opening-native-aftermath-and-starter-art-2026-10-02/archive/evidence-'+a['archiveSHA256']+'.tar.gz','archiveSHA256':a['archiveSHA256'],'archiveBytes':a['archiveBytes'],'indexSHA256':'a7b01a97c4185ebd9f82faf084e8f3145ff4bdb40e2b0034f0590269eaa9000f','readObservationsSHA256':'febf7ef93ed6a821c8361265f53d3999b9135ab71771840343d9ebcc85be8d99','inputManifestSHA256':'91c82de1139c861da723ad8ec5208eac3791da16a6e67d32659865584b01ddc3','rootGrantSHA256':'3e2a148546534eeecbd8dc8d8595cddca10aa0cbeb28a9303d3510f5293604e2','sourceGateSHA256':'698daceaa2775a0934f825fdf20020050937cf7d2450cf962fe7114a8485fd97','RootManifestGateSHA256':'ea90c86b77554a5da0a848f99d132291b47e43abd9452923f49f10b75937f46f','logicalRows':1278,'fullNewUniqueOriginalByteEqualityCount':1116,'runtimeCodeRows':86,'eightOriginalJPEGsPreserved':True,'twelveFullSavedPairsPreserved':True,'fourGzipDomainsFullyDecodedHashed':True,'allSixOriginalActualReviewGatesRetained':True,'newArtApproval':False,'gameRuntimeDefaultReleaseSelected':False,'AUDIT_SHA256':sha(P/'AUDIT.json'),'normalReviewerGuardSHA256':sha(P/'audit-guard/RESULT.json'),'actualVsInheritedQualification':a['sourceAuditVsActual'],'priorArchiveBodyOpened':False,'mediaExternalQualification':a['mediaExternal'],'failureHistoriesQualification':'Exact fixed source/review/control tree failure bodies retained. Root manifest R1/R2 generation failures and this independent reviewer packet outside fixed TAR scope remain original and require separately pinned publication copies; no broader all-workspace completeness claim.','closureQualification':'Root outer guard normal0, observed child group closed and memory events unchanged. Reviewer guards normal0. No universal unobserved descendant ownership claim.','metadataQualification':a['metadataQualification'],'sourceAuthorshipDisclosure':a['roleDisclosure'],'proofScope':'Finite preservation engineering only; historical acceptance/rejection/limits remain unchanged. Prior4513 verified index/COMPLETE inheritance and STAT-only archive.'}
assert gate['archiveSHA256']=='8cdf546a8429e949fe88611d781aca341566f473135fbcbe44b5373beabd7aa8'
(P/'GATE.json').open('x').write(json.dumps(gate,separators=(',',':'))+'\n')
(P/'REVIEW.md').open('x').write('Complete preservation accepted for the exact new 8cdf archive. Independently streamed all 1,116 regular new blob members and compared full decoded bytes, SHA256 and lengths against their original representative files; no extraction or rerun. Archive hash, INDEX/R3 manifest equality, grant/spec/active method/current-push receipt, two exact 43-code frozen maps, original reviews and art verdicts retained. Eight original JPEGs and twelve full engine save pairs preserved; four stored gzip domains independently decoded in bounded chunks to exact original hashes/lengths. No image decode or visual/gameplay reevaluation.\n\nEarlier Source audit fully hashed all 1,278 logical paths and checked complete memberships/230 literal alias chains/support60/tool metadata8. Actual review renewed all 1,116 new unique representatives and stat-checked all rows; duplicate paths and prior4513 inherited bodies were not all rehashed anew. Prior4513 pinned INDEX/COMPLETE inherited; prior archive body unopened, STAT only. Unchanged media/node_modules remain explicit external dependencies, not a full dependency Merkle or self-contained release. Historical six-view art rejection and corrected Ash review remain their original verdicts; no new art/default/runtime/fun approval.\n\nRoot terminal proof followed all archive writes: 1.1194373439939227 seconds, own17,498,112 bytes; 6,292,888 logical /6,311,936 allocated archive bytes. Archive plus outer guard tails independently measured within12MiB; outer guard normal0, events unchanged, observed child-group closure. Original frozen files read with O_NOATIME and inode/size/mtime checks; no full stat/xattr restoration claim. All fixed tree failures retained; Root manifest generation R1/R2 failures remain external original history requiring pinned publication copies. Reviewer earlier converter/witness/helper authorship disclosed; preserver is a different author.\n')
files={str(q.relative_to(P)):{'bytes':q.stat().st_size,'sha256':sha(q)} for q in P.rglob('*') if q.is_file()}
(P/'MANIFEST.json').open('x').write(json.dumps({'files':files,'logicalCapBytes':131072,'allocatedCapClaimed':False,'tailReserveBytes':8192,'ownRSSKiBLimit':24576,'workMiB':64,'reserveMiB':512,'diskAdmissionMiB':64,'closure':'All earlier guards pinned; final seal guard ADMISSION/RESULT/EXECUTION follows and is separately returned.'},separators=(',',':'))+'\n')
n=sum(q.stat().st_size for q in P.rglob('*') if q.is_file());assert n+8192<=131072 and resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
print(json.dumps({'gateSHA256':sha(P/'GATE.json'),'manifestSHA256':sha(P/'MANIFEST.json'),'reviewSHA256':sha(P/'REVIEW.md'),'auditSHA256':sha(P/'AUDIT.json'),'logicalBeforeSealGuardTail':n,'tailReserved':8192,'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'rawPairEqualityCount':sum(p['fullRawPairEqual'] for x in a['actualEvidence'] for p in x['fullSavedPairs']),'originalArtGateDecisions':a['nativeArtGatesRetainedWithoutNewApproval']}))
