import fs from 'node:fs';import crypto from 'node:crypto';import {chromium}from'@playwright/test';import{createGame,applyAction,validateState}from'./src/engine';
const out='evidence-r1';fs.mkdirSync(out);const results=[];
const fixture=applyAction(createGame(121),{type:'travel',choice:'battle'});fixture.enemies=fixture.enemies.slice(0,1);fixture.enemies[0].hp=1;fixture.enemies[0].block=0;const pile=[...fixture.hand,...fixture.draw,...fixture.discard];fixture.hand=[pile.splice(pile.indexOf('scour'),1)[0]];fixture.draw=pile;fixture.discard=[];if(!validateState(fixture))throw Error('Invalidfixture');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
try{for(const trial of ['keyboard-settle','keyboard-pause','reduced-motion']){
 const page=await browser.newPage({viewport:{width:1440,height:900}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({fixture,trial})=>{localStorage.setItem('hollowpact.run.v2',JSON.stringify(fixture));localStorage.setItem('hollowpact.tutorial.v2','yes');localStorage.setItem('hollowpact.settings.v2',JSON.stringify({mute:true,volume:0,motion:trial!=='reduced-motion'}));},{fixture,trial});
 await page.goto('http://127.0.0.1:4189');await page.locator('[data-ui="resume"]').click();await page.locator('[data-ui="play-card"]').click();await page.locator('.enemy.valid-target').click();
 const immediate=await page.evaluate(()=>({saved:localStorage.getItem('hollowpact.run.v2'),held:document.getElementById('app')!.classList.contains('settling-combat'),hint:document.querySelector('.keyboard-hint')?.textContent,busy:document.getElementById('scene-ui')!.getAttribute('aria-busy')}));
 const canonical=JSON.stringify(applyAction(fixture,{type:'play',index:0,target:fixture.enemies[0].uid}));if(immediate.saved!==canonical)throw Error('Canonical mismatch');
 if(trial!=='reduced-motion'){if(!immediate.held||immediate.hint?.trim()!=='Final impact resolvingEsc Pause'||immediate.busy!=='true')throw Error('Heldhint mismatch '+JSON.stringify(immediate));await page.screenshot({path:out+'/'+trial+'.png'});await page.keyboard.press('e');if(await page.evaluate(()=>localStorage.getItem('hollowpact.run.v2'))!==canonical)throw Error('Stale action');if(trial==='keyboard-pause'){await page.keyboard.press('Escape');if(!await page.locator('dialog').evaluate(e=>(e as HTMLDialogElement).open))throw Error('Escape didnotpause');await page.locator('[data-ui="close"]').first().click();}}
 await page.locator('[data-action="reward"]').first().waitFor({state:'visible'});const final=await page.evaluate(()=>({saved:localStorage.getItem('hollowpact.run.v2'),held:document.getElementById('app')!.classList.contains('settling-combat')}));if(final.saved!==canonical||final.held||errors.length)throw Error('Final mismatch');results.push({trial,immediate,final,errors});await page.close();
}}finally{await browser.close();}
fs.writeFileSync(out+'/results.json',JSON.stringify({status:'passed',fixture:'validcustomHP1 Scour terminal; diagnostic notearnedrun',results,sourceHashes:Object.fromEntries(['src/main.ts','src/input.ts','src/arena.ts','src/style.css'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]))},null,2)+'\n',{flag:'wx'});console.log('Passed3 actual terminalhint/pause/canonical paths');
