import {chromium} from '/workspace/Roguelike-deckbuilder/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const out='/workspace/Roguelike-deckbuilder/reviews/arena-v0.4-evidence/candidate';mkdirSync(out,{recursive:true});
const fixtures={early:JSON.parse(readFileSync('/tmp/review-v03-earlylethal.json')),weak:JSON.parse(readFileSync('/workspace/Roguelike-deckbuilder/reviews/screenshots-v0.3/weak-binding-fixture.json'))};
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-gpu']});
const page=await browser.newPage({viewport:{width:1280,height:640}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/src/arena.ts');await page.setContent('<style>body{margin:0;background:#111}canvas{width:1280px;height:540px;display:block}</style><canvas id="arena"></canvas>');
await page.evaluate(async()=>{
 window.clock=1000;window.q=new Map();window.serial=0;window.requestAnimationFrame=cb=>{const id=++window.serial;window.q.set(id,cb);return id};window.cancelAnimationFrame=id=>window.q.delete(id);
 window.step=ms=>{for(let t=0;t<ms;t+=16.6666667){window.clock+=Math.min(16.6666667,ms-t);const c=[...window.q.values()];window.q.clear();for(const cb of c)cb(window.clock)}};
 const arena=await import('/src/arena.ts'),engine=await import('/src/engine.ts');window.make=arena.createArena;window.engine=engine;window.a=window.make(document.querySelector('canvas'));window.draws=[];
 const proto=CanvasRenderingContext2D.prototype,orig=proto.drawImage;proto.drawImage=function(...args){if(args[0]?.src?.includes('hound-poses'))window.draws.push({t:clock,source:args.slice(1,5),dest:args.slice(5),transform:[this.getTransform().e,this.getTransform().f],alpha:this.globalAlpha});return orig.apply(this,args)};
});
await page.waitForTimeout(500);
const result={method:'Own v0.4 implementation QA; standalone Canvas2D renderer using actual local source and artwork. Controlled16.67ms RAF for repeatable pose captures; not a measured display cadence or independent review.',errors,cases:[]};
for(const [name,before]of Object.entries(fixtures)){
 const res=await page.evaluate(before=>{window.a.cancelPresentation();window.a.dispose();window.a=window.make(document.querySelector('canvas'));window.a.render(before);window.step(450);window.draws=[];const action={type:'endTurn'},r=engine.applyActionWithEvents(before,action);a.playAction(action,before,r.state,r.events);window.after=r.state;return{events:r.events,phase:r.state.phase,busy:a.busyMs()};},before);
 await page.evaluate(()=>step(280));await page.locator('canvas').screenshot({path:`${out}/${name}-contact.png`});
 res.draws=await page.evaluate(()=>draws);await page.evaluate(()=>step(1300));res.settled=await page.evaluate(()=>a.busyMs());result.cases.push({name,...res});
}
const duel=structuredClone(fixtures.weak);duel.allies=[{...duel.allies[0],species:'hound',hp:20,maxHp:20,attack:7,block:0,acted:false}];duel.enemies=[{...duel.enemies[0],hp:30,maxHp:30,block:0}];duel.log=[];
await page.evaluate(before=>{a.dispose();window.a=make(document.querySelector('canvas'));a.render(before);step(500);window.draws=[];window.before=before},duel);
await page.locator('canvas').screenshot({path:`${out}/hound-idle.png`});
const attack=await page.evaluate(()=>{const action={type:'attack',unit:before.allies[0].uid,target:before.enemies[0].uid},r=engine.applyActionWithEvents(before,action);a.playAction(action,before,r.state,r.events);window.after=r.state;return{action,events:r.events,busy:a.busyMs()}});
for(const [ms,label]of [[85,'anticipation'],[150,'attack'],[190,'recovery'],[600,'settled']]){await page.evaluate(ms=>step(ms),ms);await page.locator('canvas').screenshot({path:`${out}/hound-${label}.png`});}
attack.draws=await page.evaluate(()=>draws);result.cases.push({name:'hound-duel',...attack});
const terminal=structuredClone(duel);terminal.allies[0].hp=2;terminal.allies[0].maxHp=8;terminal.enemies[0].hp=2;terminal.enemies[0].maxHp=8;terminal.enemies[0].block=3;terminal.enemies[0].species='warlord';terminal.enemies[0].cardId='ironjaw';
const death=await page.evaluate(before=>{a.dispose();window.a=make(document.querySelector('canvas'));a.render(before);step(450);window.draws=[];const action={type:'attack',unit:before.allies[0].uid,target:before.enemies[0].uid};const r=engine.applyActionWithEvents(before,action);a.playAction(action,before,r.state,r.events);window.deathWait=false;a.waitForPresentation().then(()=>window.deathWait=true);return{events:r.events,phase:r.state.phase,busy:a.busyMs()};},terminal);
await page.evaluate(()=>step(420));await page.locator('canvas').screenshot({path:`${out}/terminal-retaliation.png`});death.draws=await page.evaluate(()=>draws);await page.evaluate(()=>step(850));await page.waitForTimeout(0);death.settled=await page.evaluate(()=>({busy:a.busyMs(),wait:window.deathWait}));result.cases.push({name:'terminal-retaliation',...death});
for(const card of ['silence','edict']){const spell=structuredClone(duel);spell.hand=[card];spell.deck.push(card);spell.energy=5;const cue=await page.evaluate(before=>{a.dispose();window.a=make(document.querySelector('canvas'));a.render(before);step(450);window.draws=[];const action={type:'play',index:0,...(before.hand[0]==='silence'?{target:before.enemies[0].uid}:{})},r=engine.applyActionWithEvents(before,action);a.playAction(action,before,r.state,r.events);const busy=a.busyMs();step(330);return{events:r.events,busy,draws};},spell);await page.locator('canvas').screenshot({path:`${out}/${card}-cue.png`});result.cases.push({name:card+'-cue',...cue});}
const reaction=structuredClone(duel);reaction.enemies[0].intent.target=reaction.allies[0].uid;
const reactionResult=await page.evaluate(before=>{a.dispose();window.a=make(document.querySelector('canvas'));a.render(before);step(450);window.draws=[];const action={type:'endTurn'},r=engine.applyActionWithEvents(before,action);a.playAction(action,before,r.state,r.events);step(340);return{events:r.events,draws};},reaction);await page.locator('canvas').screenshot({path:`${out}/hound-reaction.png`});result.cases.push({name:'hound-reaction',...reactionResult});
const formation=structuredClone(duel);formation.allies=Array.from({length:3},(_,i)=>({...duel.allies[0],uid:'qaA'+i,species:['hound','stalker','colossus'][i]}));
const formationResult=await page.evaluate(before=>{a.dispose();window.a=make(document.querySelector('canvas'));a.render(before);step(450);window.draws=[];const after=structuredClone(before);after.allies.push({...before.allies[0],uid:'qaA3',species:'spider'});a.render(after);const at0=draws.at(-1)?.transform;step(160);const at160=draws.at(-1)?.transform;step(180);const at340=draws.at(-1)?.transform;window.full=after;return{at0,at160,at340,busy:a.busyMs()};},formation);await page.locator('canvas').screenshot({path:`${out}/formation-four.png`});result.cases.push({name:'formation-transition',...formationResult});
await page.evaluate(()=>{const state=structuredClone(full);state.allies=Array.from({length:6},(_,i)=>({...state.allies[0],uid:'fullA'+i,species:['hound','stalker','colossus','spider','hound','stalker'][i]}));state.enemies=Array.from({length:6},(_,i)=>({...state.enemies[0],uid:'fullE'+i,species:['warlord','necromancer','wraith','dragon','thrall','warlord'][i]}));a.dispose();window.a=make(document.querySelector('canvas'));a.render(state);step(500)});await page.locator('canvas').screenshot({path:`${out}/max12-desktop.png`});await page.setViewportSize({width:390,height:700});await page.evaluate(()=>{document.querySelector('canvas').style.width='390px';document.querySelector('canvas').style.height='500px';a.resize()});await page.locator('canvas').screenshot({path:`${out}/max12-narrow.png`});await page.setViewportSize({width:1280,height:640});await page.evaluate(()=>{document.querySelector('canvas').style.width='1280px';document.querySelector('canvas').style.height='540px';a.resize()});
const checks=await page.evaluate(async before=>{
 const reset=()=>{a.dispose();window.a=make(document.querySelector('canvas'));a.render(before);step(450);const action={type:'attack',unit:before.allies[0].uid,target:before.enemies[0].uid},r=engine.applyActionWithEvents(before,action);a.playAction(action,before,r.state,r.events)};
 reset();const promise=a.waitForPresentation();document.documentElement.dataset.reducedMotion='true';await Promise.resolve();await promise;const reducedBusy=a.busyMs(),first=document.querySelector('canvas').toDataURL();step(500);const stable=first===document.querySelector('canvas').toDataURL();document.documentElement.dataset.reducedMotion='false';await Promise.resolve();
 reset();const canceled=a.waitForPresentation();a.cancelPresentation();await canceled;const cancelBusy=a.busyMs();reset();const disposed=a.waitForPresentation();a.dispose();await disposed;return{reducedBusy,reducedPixelStable:stable,cancelBusy,disposedPromiseResolved:true};
},duel);result.checks=checks;
await page.evaluate(before=>{window.a=make(document.querySelector('canvas'));a.render(before);step(450);const action={type:'attack',unit:before.allies[0].uid,target:before.enemies[0].uid},r=engine.applyActionWithEvents(before,action);a.playAction(action,before,r.state,r.events)},duel);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>a.busyMs()===0);result.osMotion=await page.evaluate(()=>{const before=document.querySelector('canvas').toDataURL();step(500);return{busy:a.busyMs(),pixelStable:before===document.querySelector('canvas').toDataURL()}});await page.emulateMedia({reducedMotion:'no-preference'});
result.lifecycle=await page.evaluate(async before=>{const reset=()=>{a.dispose();window.a=make(document.querySelector('canvas'));a.render(before);step(450);const action={type:'attack',unit:before.allies[0].uid,target:before.enemies[0].uid},r=engine.applyActionWithEvents(before,action);const snapshot=JSON.stringify([before,r.state,r.events]);a.playAction(action,before,r.state,r.events);return{snapshot,after:r.state,events:r.events}};const first=reset();const unchanged=first.snapshot===JSON.stringify([before,first.after,first.events]);const hiddenWait=a.waitForPresentation();Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));await hiddenWait;const hiddenBusy=a.busyMs();delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));reset();const resizeWait=a.waitForPresentation();document.querySelector('canvas').style.width='1000px';a.resize();await resizeWait;const resizeBusy=a.busyMs();document.querySelector('canvas').style.width='1280px';a.resize();a.dispose();const canvas=document.querySelector('canvas'),getContext=canvas.getContext;canvas.getContext=()=>null;const fallback=make(canvas);const fallbackBusy=fallback.busyMs(),fallbackHidden=canvas.hidden,notice=document.querySelector('.arena-fallback')?.textContent;await fallback.waitForPresentation();fallback.dispose();canvas.getContext=getContext;return{inputsUnchanged:unchanged,simulatedHiddenBusy:hiddenBusy,resizeBusy,fallbackBusy,fallbackHidden,fallbackNotice:notice,fallbackDisposed:!canvas.hidden&&!document.querySelector('.arena-fallback')};},duel);
writeFileSync(out+'/qa.json',JSON.stringify(result,null,2));console.log(JSON.stringify({cases:result.cases.map(c=>({name:c.name,phase:c.phase,busy:c.busy,events:(c.events??[]).map(e=>[e.type,e.source,e.target]),settled:c.settled})),checks,errors}));await browser.close();
