import json,hashlib,resource
from pathlib import Path
P=Path(__file__).parent
def sha(q):return hashlib.sha256(q.read_bytes()).hexdigest()
a=json.loads((P/'AUDIT.json').read_bytes());r=json.loads((P/'review-guard/RESULT.json').read_bytes());assert r['exit_code']==0 and r['failure'] is None and r['memory_events_before']==r['memory_events_after']
gate={'decision':a['decision'],'exactTwoPathActionMethodEligible':True,'accepted':True,'actionAuthority':False,'methodPath':'/workspace/scratch/retire-opening-capsule-duplicates-root-r2.py','methodSHA256':a['methodSHA256'],'derivationSHA256':a['derivationSHA256'],'originalR1MethodSHA256':'ad37576f647b0018a3e6e4d14ac88c5460f394b4d1800c20db70425bed18a6a8','originalR1RejectedGateSHA256':'3e841ceb07c2ee5c5165070fb11646a441353636d31b557e414baa141c7f15ab','preferenceGateSHA256':'596577259f0b2455c03b3b3d160700f4c7f1f6a90c049e1ba2347752976ddd8c','locationMapSHA256':'7aa54ca2c8ab29604d5d334e5cac825b2bd6145fecbe90a656e255f771cdafb4','fullByteInverseVerified':True,'explicitOptimizedPythonRefusalVerifiedByCompileOnly':True,'localGitTimeoutSeconds':10,'cooperativeWholeSeconds':40,'ownRSSLimitKiB':24576,'remoteReceiptMaxAgeSeconds':120,'noNetworkCommandInHelper':True,'proof':a['proof'],'futureActionRequirements':a['futureActionRequirements'],'partialProgressLimits':a['partialProgressLimits'],'timeLimitQualification':a['timeLimitQualification'],'historicalReaderQualification':a['historicalReaderQualification'],'actualActionExecuted':False,'archiveBodyReadOrDecoded':False,'canonicalDeletionApproved':False,'artGameDefaultRuntimeApproved':False,'AUDIT_SHA256':sha(P/'AUDIT.json'),'normalSourceGuardSHA256':sha(P/'review-guard/RESULT.json'),'roleDisclosure':a['roleDisclosure']}
(P/'GATE.json').open('x').write(json.dumps(gate,separators=(',',':'))+'\n')
(P/'REVIEW.md').open('x').write('Conditional SOURCE method acceptance for exact Root R2 b1131f6c, not execution authority. Full11 replacement forward and reverse byte comparison to retained R1 verified. Compile-only optimized source reaches unconditional RuntimeError before authorization or unlink; no method module imported/executed. Three local Git commands timeout10s; network removed. Exact recent remote-confirmed push receipt age0..120s plus grant-bound receiptSHA/current localHEAD/clean remains mandatory. Original pair paths, fresh full hashes/full metadata+xattrs/private nlink1/distinctinode/parent checks and durable PRE/per-path POST unchanged outside the reviewed correction spans.\n\nChecks establish cooperative40s/own24MiB ceiling in chunk/phase/write and immediately before each unlink. Final fsynced RESULT is rehashed with check before terminal stdout; completed RESULT alone is provisional unless action/outer guard closes normal0 and independent actual POST passes. No arbitrary filesystem-block preemption/global FD or consumer absence claim. Sequential deletion can partially progress on failure; PRE/any POST and failure remain, no automatic restore. Canonical copies/source/art/reviews remain; historical direct scratch readers need published mapping or separately reviewed exact-byte reconstruction, without old inode/time restoration promises.\n\nBefore action: publish proposal/location/provenance/producer decision/current checkpoint/old rejection/new method/gate, commit and freshly confirm clean current push in finite upstream pipeline; bind new exact Root grant immediately. Source actors paused/sole writer confirmed; ordinary64+512 or separately granted finite combined128+512 retains original64MiB initial disk admission and512 reserve. No browser/native budget waiver or net recovery promise. This reviewer read only source/control JSON, no TAR/protected ZIP body or mutation. Preference author and Root method author distinct; prior preservation/utility/helper role disclosed.\n')
files={str(q.relative_to(P)):{'bytes':q.stat().st_size,'sha256':sha(q)} for q in P.rglob('*') if q.is_file()}
(P/'MANIFEST.json').open('x').write(json.dumps({'files':files,'logicalCapBytes':65536,'allocatedCapClaimed':False,'guardTailReserveBytes':8192,'workMiB':64,'reserveMiB':512,'diskAdmissionMiB':64,'ownRSSKiBLimit':24576,'finalSealGuard':'Separate ADMISSION/RESULT/EXECUTION follows manifest; exact final normal closure pin returned.'},separators=(',',':'))+'\n')
n=sum(q.stat().st_size for q in P.rglob('*') if q.is_file());assert n+8192<=65536 and resource.getrusage(resource.RUSAGE_SELF).ru_maxrss<=24576
print(json.dumps({'gateSHA256':sha(P/'GATE.json'),'manifestSHA256':sha(P/'MANIFEST.json'),'reviewSHA256':sha(P/'REVIEW.md'),'auditSHA256':sha(P/'AUDIT.json'),'logicalBeforeSealGuardTails':n,'tailReserveBytes':8192,'ownMaxRSSKiB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'actualActionExecuted':False}))
