import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';import {tsImport} from 'tsx/esm/api';import {chromium} from '@playwright/test';
const O='/workspace/Roguelike-deckbuilder/reviews/root-v0.9-event-availability-author/r2',S='/tmp/hollowpact-event-availability-v09-root-r1',B='/tmp/hollowpact-fallback-cards-v09-root-r1',H=b=>createHash('sha256').update(b).digest('hex'),E=await tsImport(pathToFileURL(S+'/src/engine.ts').href,import.meta.url),records=[],errors=[];
const cases=[['owned',{relics:['moon-charm']},'offering','Wraithglass Shard already owned','forage'],['oath-low',{hp:8},'offering','Requires at least 9 health','leave'],['oath-threshold',{hp:9},null,null,'offering'],['purge-low',{hp:4},'purge','Requires at least 5 health','forage'],['five-cards',{deck:E.createGame(1).deck.slice(0,5)},'purge','Keep at least 5 cards','leave'],['no-scour',{deck:E.createGame(1).deck.map(id=>id==='scour'?'ironward':id)},'purge','No unenhanced Scour to remove','forage'],['poor',{hp:50,gold:29},'bargain','Requires 30 gold','leave'],['full-health',{},'bargain','Already at full health','purge'],['capped-heal',{hp:64,gold:30},null,null,'bargain'],['full-heal',{hp:49,gold:65},null,null,'bargain']];
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
function write(n,v){fs.writeFileSync(O+'/'+n,JSON.stringify(v,null,2)+'\n',{flag:'wx'});}
async function audit(root,port){const p=JSON.parse(fs.readFileSync(root+'/dist/build-provenance.json'));for(const[n,h]of Object.entries(p.hashes))assert.equal(H(fs.readFileSync(root+'/'+n)),h,n);const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name]);const outputs={};for(const f of walk(root+'/dist')){const n=f.slice((root+'/dist/').length),b=fs.readFileSync(f);assert.deepEqual(Buffer.from(await(await fetch('http://127.0.0.1:'+port+'/'+n)).arrayBuffer()),b,n);outputs[n]={sha256:H(b),bytes:b.length};}return{runtime:p,outputs};}
try{write('IDENTITY-BEFORE.json',{candidate:await audit(S,4631),baseline:await audit(B,4630)});
for(const kind of[1,2])for(let i=0;i<cases.length;i++){
 const[name,patch,disabled,reason,choice]=cases[i],s={...E.createGame(381027,1,{engineKind:kind}),phase:'event',floor:2,route:['event'],...patch};assert(E.validateState(s),name);const raw=JSON.stringify(s),width=i%2?1440:360,ctx=await browser.newContext({viewport:{width,height:900},hasTouch:width===360}),page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(({raw})=>{if(!sessionStorage.getItem('fixture-seeded')){localStorage.setItem('hollowpact.run.v2',raw);localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion:false,mute:true,volume:0}));localStorage.setItem('hollowpact.tutorial.v2','yes');sessionStorage.setItem('fixture-seeded','yes');}},{raw});await page.goto('http://127.0.0.1:4631');await page.locator('[data-ui=resume]').click();
 const labels={};for(const id of['offering','forage','purge','bargain','leave']){const el=page.locator('[data-choice='+id+']'),legal=E.legalActions(s).some(a=>a.type==='event'&&a.choice===id);assert.equal(await el.isDisabled(),!legal,id);labels[id]=await el.textContent();}
 if(disabled){assert(labels[disabled].includes(reason));await page.locator('[data-choice='+disabled+']').dispatchEvent('click');assert.equal(await page.evaluate(()=>localStorage.getItem('hollowpact.run.v2')),raw,'Synthetic stale disabled event must preserve save');}
 if(choice==='bargain'){assert(labels.bargain.includes('+'+Math.min(16,s.maxHp-s.hp)+' health'));assert(labels.bargain.includes(s.gold+' → '+(s.gold-30)+' gold'));}
 const geometry=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,labels:[...document.querySelectorAll('.choice-card>span')].map(el=>{const r=el.getBoundingClientRect(),p=el.parentElement.getBoundingClientRect();return{text:el.textContent,inside:r.left>=p.left-1&&r.right<=p.right+1&&r.bottom<=p.bottom+1};})}));assert(geometry.document<=width);assert(geometry.labels.every(x=>x.inside));assert.equal(await page.evaluate(()=>localStorage.getItem('hollowpact.run.v2')),raw);
 if(kind===2&&['owned','capped-heal','full-health','purge-low'].includes(name))await page.screenshot({path:O+'/'+name+'-'+width+'.jpg',type:'jpeg',quality:68});
 const button=page.locator('[data-choice='+choice+']');await button.scrollIntoViewIfNeeded();if(width===360)await button.tap();else{await button.focus();await page.keyboard.press('Enter');}const expected=E.applyAction(s,{type:'event',choice});await page.waitForFunction(()=>document.querySelector('[data-ui=resume]')===null);assert.deepEqual(JSON.parse(await page.evaluate(()=>localStorage.getItem('hollowpact.run.v2'))),expected);await page.reload();await page.locator('[data-ui=resume]').click();assert.deepEqual(JSON.parse(await page.evaluate(()=>localStorage.getItem('hollowpact.run.v2'))),expected);records.push({kind,name,width,labels,geometry,action:{type:'event',choice},actualTouch:width===360,keyboard:width!==360,postSaveSHA256:H(JSON.stringify(expected)),reloadExact:true});write('context-'+kind+'-'+name+'.json',records.at(-1));await ctx.close();
}
write('IDENTITY-AFTER.json',{candidate:await audit(S,4631),baseline:await audit(B,4630)});assert.deepEqual(JSON.parse(fs.readFileSync(O+'/IDENTITY-BEFORE.json')),JSON.parse(fs.readFileSync(O+'/IDENTITY-AFTER.json')));assert.deepEqual(errors,[]);write('RESULTS.json',{contexts:records.length,actualActions:records.length,reloads:records.length,sourceOracleUsed:'Author diagnostic assertions only; not strategic playtest.',errors,baseline:'Identity/source correspondence; baseline oldcopy behavior is known from retained source/UIplaytest. No paired baseline browser contexts claimed.',records});console.log('PASS',records.length,'actual browser contexts/actions/reloads');
}catch(e){write('FAILURE-r1.json',{error:e.stack,completed:records.length,errors});throw e;}finally{await browser.close();}
