import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import {validateState,applyActionWithEvents} from '../../src/engine.ts';
const ROOT='/workspace/Roguelike-deckbuilder',OUT=ROOT+'/reviews/visual-v0.6-runtime/native',DIGEST=process.argv[2];if(!/^[a-f0-9]{64}$/.test(DIGEST??''))throw Error('Explicit final digest required');await fs.mkdir(OUT,{recursive:true});
const authored=JSON.parse(await fs.readFile(ROOT+'/reviews/arena-v0.6-contact-prototype/fixtures.json','utf8')).cases;const formation=JSON.parse(await fs.readFile(ROOT+'/reviews/arena-v0.6-contact-prototype/formation-fixture.json','utf8'));formation.name='formation-command-fourth-binding';const cases=[];
for(const base of authored){const r=applyActionWithEvents(base.before,base.action);cases.push({...base,state:r.state,events:r.events});}cases.push(formation);
const matrix=cases.map(item=>({item,width:1280,height:720,build:'v6',url:'http://127.0.0.1:4173',digest:DIGEST}));
for(const width of [390,1920])for(const name of ['hound-leftward','hound-rightward','hound-near-left','hound-vertical','hound-far-left-mutual-death','hound-duel-short-range','formation-command-fourth-binding']){const item=cases.find(c=>c.name===name);matrix.push({item,width,height:width===390?844:720,build:'v6',url:'http://127.0.0.1:4173',digest:DIGEST});}
for(const [width,name]of[[1280,'hound-leftward'],[1280,'hound-rightward'],[390,'hound-duel-short-range'],[1280,'warleader-melee-right'],[1280,'two-dragons-fourteen-hits']])matrix.push({item:cases.find(c=>c.name===name),width,height:width===390?844:720,build:'v5-immutable',url:'http://127.0.0.1:5197',digest:'d6221bf764bad593b04981e87bead7ba6868b72cf361d70671af5c91aac39416'});
for(const c of cases)if(!validateState(c.before)||!validateState(c.state))throw Error('Invalid '+c.name);await fs.writeFile(OUT+'/fixtures.json',JSON.stringify({provenance:'Preserved renderer-author inputs plus independently derived valid left/right warleader target and reaction cases; not naturally reached runs',cases},null,2)+'\n');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const results=[];
try{for(const {item,width,height,build,url,digest} of matrix.filter(c=>!process.argv[3]||c.item.name===process.argv[3])){const dir=OUT+'/'+build+'-'+width+'-'+item.name;await fs.mkdir(dir,{recursive:true});const c=await browser.newContext({viewport:{width,height}});await c.addInitScript(s=>{
localStorage.setItem('hollowpact.run.v2',JSON.stringify(s));localStorage.setItem('hollowpact.settings.v2',JSON.stringify({motion:true,mute:true,volume:0}));window.visualFrames=[];window.visualCaptures=[];window.visualKeys=[];window.visualSeen={};window.visualBuckets={};window.visualEpoch=null;window.visualContactCaptured=false;window.visualCurrent={actors:[],impacts:[]};document.addEventListener('click',e=>{const el=e.target.closest('[data-action="endTurn"],[data-ui="confirm-end"],[data-unit]');if(el){window.visualEpoch=performance.now();window.visualSeen={};window.visualBuckets={};window.visualCaptures=[];window.visualFrames=[];window.visualKeys=[];window.visualContactCaptured=false;}},true);
const draw=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(...a){const r=draw.apply(this,a);if(this.canvas.id!=='arena')return r;const canvas=this.canvas;if(a[0] instanceof HTMLCanvasElement){window.visualCurrent={time:performance.now(),elapsed:window.visualEpoch===null?null:performance.now()-window.visualEpoch,canvas:{width:canvas.width,height:canvas.height,cssWidth:canvas.clientWidth,cssHeight:canvas.clientHeight},actors:[],impacts:[]};queueMicrotask(()=>{const f=window.visualCurrent;if(f.elapsed===null||f.elapsed<0||f.elapsed>1300)return;window.visualFrames.push(structuredClone(f));const contact=!window.visualContactCaptured&&f.impacts.some(i=>i.kind==='physical'&&i.color==='#f3d3a4');if(contact){window.visualContactCaptured=true;window.visualCaptures.push({bucket:'first-impact',frame:structuredClone(f),data:canvas.toDataURL('image/png')});}const bucket=[350,600,900,1150].find(t=>f.elapsed>=t&&!window.visualBuckets[t]);if(bucket){window.visualBuckets[bucket]=true;window.visualCaptures.push({bucket,frame:structuredClone(f),data:canvas.toDataURL('image/png')});}});}else if(a[0] instanceof HTMLImageElement&&a.length===9){const im=a[0],m=this.getTransform(),rec={url:im.src.split('/').at(-1),source:a.slice(1,5),destination:a.slice(5),transform:{a:m.a,b:m.b,c:m.c,d:m.d,e:m.e,f:m.f},alpha:this.globalAlpha};window.visualCurrent.actors.push(rec);if((rec.url==='warleader-poses.png'||rec.url==='hound-poses.png')&&rec.alpha>=.92){const key=rec.source.join('-');if(window.visualEpoch!==null&&!window.visualSeen[key]){window.visualSeen[key]=true;queueMicrotask(()=>window.visualKeys.push({key,elapsed:performance.now()-window.visualEpoch,actor:rec}));}}}return r};
const q=CanvasRenderingContext2D.prototype.quadraticCurveTo;CanvasRenderingContext2D.prototype.quadraticCurveTo=function(...a){if(this.canvas.id==='arena'&&a[1]===a[3]&&a[2]>a[0]+1){const r=(a[2]-a[0])/1.7;window.visualCurrent.impacts.push({kind:'physical',color:this.strokeStyle,x:a[0]+r,y:a[1]+r,radius:r});}return q.apply(this,a)};
const arc=CanvasRenderingContext2D.prototype.arc;CanvasRenderingContext2D.prototype.arc=function(...a){if(this.canvas.id==='arena'&&this.strokeStyle==='#ddbe80'&&a[2]>=9&&a[2]<35&&this.lineWidth===1.5)window.visualCurrent.impacts.push({kind:'magic',color:this.strokeStyle,x:a[0],y:a[1],radius:a[2]});return arc.apply(this,a)};
},item.before);const p=await c.newPage(),errors=[],bad=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)bad.push(r.url())});await p.goto(url);const provenance=await(await p.request.get(url+'/build-provenance.json')).json();if(provenance.sourceDigest!==digest)throw Error('Wrong frozenbuild');await p.locator('[data-ui=resume]').click();await p.waitForTimeout(450);await p.screenshot({path:dir+'/before.png'});
if(item.action.type==='endTurn'){await p.locator('[data-action=endTurn]').click();if(await p.locator('[data-ui=confirm-end]').isVisible())await p.locator('[data-ui=confirm-end]').click();}else if(item.action.type==='attack'){await p.locator(`[data-unit="${item.action.unit}"]`).click();await p.locator(`[data-unit="${item.action.target}"]`).click();}else throw Error('Unexpected action');
if(item.transitions){await p.waitForTimeout(90);const a=item.transitions[1].action;await p.locator(`[data-ui=play-card][data-index="${a.index}"]`).click();}await p.waitForTimeout(1300);const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('hollowpact.run.v2'))),probe=await p.evaluate(()=>({frames:window.visualFrames,captures:window.visualCaptures,keys:window.visualKeys}));for(const cap of probe.captures){await fs.writeFile(dir+`/frame-${cap.bucket}.png`,Buffer.from(cap.data.split(',')[1],'base64'));delete cap.data;}
const actorBounds=probe.frames.flatMap(f=>f.actors.filter(a=>a.url==='hound-poses.png'||a.url==='warleader-poses.png'||(a.url==='adversaries-atlas.png'&&a.source[0]>600&&a.source[1]>600)).map(a=>{const[x,y,w,h]=a.destination,m=a.transform,corners=[[x,y],[x+w,y],[x,y+h],[x+w,y+h]].map(([px,py])=>[m.a*px+m.c*py+m.e,m.b*px+m.d*py+m.f]);return{elapsed:f.elapsed,url:a.url,source:a.source,ground:{x:m.e,y:m.f},minX:Math.min(...corners.map(p=>p[0])),maxX:Math.max(...corners.map(p=>p[0])),minY:Math.min(...corners.map(p=>p[1])),maxY:Math.max(...corners.map(p=>p[1])),offscreen:Math.min(...corners.map(p=>p[1]))>=f.canvas.height||Math.max(...corners.map(p=>p[1]))<=0||Math.min(...corners.map(p=>p[0]))>=f.canvas.width||Math.max(...corners.map(p=>p[0]))<=0};}));
const report={method:'Independent frozen-production actual UI controls, native RAF read-only draw/curve probes and completed-frame PNGs. Diagnostic fixture, no FPS claims. Action epoch is captured actual click; render clock may differ by a frame.',name:item.name,build,viewport:{width,height},provenance,errors,badResponses:bad,savedMatchesExpected:JSON.stringify(saved)===JSON.stringify(item.state),expectedEvents:item.events,saved,probe,actorBounds};await fs.writeFile(dir+'/runtime.json',JSON.stringify(report,null,2)+'\n');await p.screenshot({path:dir+'/after.png'});results.push({name:item.name,build,viewport:{width,height},savedMatchesExpected:report.savedMatchesExpected,errors,bad,frames:probe.frames.length,keys:probe.keys.map(k=>k.key),offscreen:actorBounds.filter(x=>x.offscreen).length,maxMagicImpacts:Math.max(0,...probe.frames.map(f=>f.impacts.filter(i=>i.kind==='magic').length))});await c.close();}
await fs.writeFile(OUT+(process.argv[3]?'/summary-'+process.argv[3]+'.json':'/summary.json'),JSON.stringify({digest:DIGEST,results},null,2)+'\n');console.log(results);}finally{await browser.close();}
